/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin GlowMain_Internal_TextureFX [{Amount = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {AutoExposureFactor = InputFloat<ShaderFX.InputValueFloat.i5,PerUpdate>}, {Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {Exposure = InputFloat<ShaderFX.InputValueFloat.i3,PerUpdate>}, {HighlightBoost = InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>}, {MaxRadius = InputFloat<ShaderFX.InputValueFloat.i6,PerUpdate>}, {PreBlurWidth = InputFloat<ShaderFX.InputValueFloat.i7,PerUpdate>}, {Saturation = InputFloat<ShaderFX.InputValueFloat.i4,PerUpdate>}, {Shape = InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>}]
@P Amount: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Shape: InputFloat<ShaderFX.InputValueFloat.i1,PerUpdate>
@P HighlightBoost: InputFloat<ShaderFX.InputValueFloat.i2,PerUpdate>
@P Exposure: InputFloat<ShaderFX.InputValueFloat.i3,PerUpdate>
@P Saturation: InputFloat<ShaderFX.InputValueFloat.i4,PerUpdate>
@P AutoExposureFactor: InputFloat<ShaderFX.InputValueFloat.i5,PerUpdate>
@P MaxRadius: InputFloat<ShaderFX.InputValueFloat.i6,PerUpdate>
@P PreBlurWidth: InputFloat<ShaderFX.InputValueFloat.i7,PerUpdate>
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 48]
@C    InputValue_id98 => ShaderFX.InputValueFloat4
@C    InputValue_id99 => ShaderFX.InputValueFloat
@C    InputValue_id100 => ShaderFX.InputValueFloat.i5
@C    InputValue_id101 => ShaderFX.InputValueFloat.i3
@C    InputValue_id102 => ShaderFX.InputValueFloat.i2
@C    InputValue_id103 => ShaderFX.InputValueFloat.i6
@C    InputValue_id104 => ShaderFX.InputValueFloat.i7
@C    InputValue_id105 => ShaderFX.InputValueFloat.i4
@C    InputValue_id106 => ShaderFX.InputValueFloat.i1
cbuffer PerView [Size: 32]
@C    NearClipPlane_id74 => Camera.NearClipPlane
@C    FarClipPlane_id75 => Camera.FarClipPlane
@C    ZProjection_id76 => Camera.ZProjection
@C    ViewSize_id77 => Camera.ViewSize
@C    AspectRatio_id78 => Camera.AspectRatio
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (0-0)]
@R    Sampler1_id53 => Texturing.Sampler1 [Stage: Pixel, Slot: (1-1)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    Texture1_id16 => Texturing.Texture1 [Stage: Pixel, Slot: (1-1)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    PerView => PerView [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    GlowMain_Internal_TextureFX => 55d73d987ed4848717c0c95e3f43d23f
@S    GlowBase => cad95198c10bdc47ed5ee763f5c17968
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => f871947e9f604da432ea9fc3c9cb4363
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 231 "C:\SMxABB\Sources\SpaceMusic\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_56477055c260320a754777450cc5b14d.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 235
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 5642a8b1b13705685a02bee440d24658
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id98;            // Offset:    0 Size:    16
//   float InputValue_id99;             // Offset:   16 Size:     4
//   float InputValue_id100;            // Offset:   20 Size:     4 [unused]
//   float InputValue_id101;            // Offset:   24 Size:     4 [unused]
//   float InputValue_id102;            // Offset:   28 Size:     4
//   float InputValue_id103;            // Offset:   32 Size:     4
//   float InputValue_id104;            // Offset:   36 Size:     4 [unused]
//   float InputValue_id105;            // Offset:   40 Size:     4 [unused]
//   float InputValue_id106;            // Offset:   44 Size:     4
//
// }
//
// cbuffer PerView
// {
//
//   float NearClipPlane_id74;          // Offset:    0 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id75;           // Offset:    4 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id76;           // Offset:    8 Size:     8 [unused]
//   float2 ViewSize_id77;              // Offset:   16 Size:     8
//   float AspectRatio_id78;            // Offset:   24 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Sampler0_id52                     sampler      NA          NA             s0      1 
// Sampler1_id53                     sampler      NA          NA             s1      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// Texture1_id16                     texture  float4          2d             t1      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// PerView                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_constantbuffer CB1[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 8
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 210 "C:\SMxABB\Sources\SpaceMusic\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_56477055c260320a754777450cc5b14d.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r0.x <- <InTex0_id26 return value>.x; r0.y <- <InTex0_id26 return value>.y; r0.z <- <InTex0_id26 return value>.z; r0.w <- <InTex0_id26 return value>.w

#line 178
max r1.x, cb1[1].y, cb1[1].x
log r1.x, r1.x  // r1.x <- lod

#line 179
sample_indexable(texture2d)(float,float,float,float) r1.yzw, v1.xyxx, t1.wxyz, s1  // r1.y <- s.x; r1.z <- s.y; r1.w <- s.z

#line 183
mad r2.x, -cb0[2].x, r1.x, l(1.000000)
add r2.x, r1.x, -r2.x
min r2.x, r2.x, l(14.000000)

#line 185
mul r2.yz, v1.yyxy, cb1[1].yyxy
mul r3.xyzw, r2.zyzy, l(4.000000, 4.000000, 4.000000, 4.000000)
ge r3.xyzw, r3.xyzw, -r3.zwzw
movc r3.xyzw, r3.xyzw, l(4.000000,4.000000,0.250000,0.250000), l(-4.000000,-4.000000,-0.250000,-0.250000)
mul r2.yz, r2.yyzy, r3.wwzw
frc r2.yz, r2.yyzy
mad r2.yz, r3.yyxy, r2.yyzy, l(0.000000, -1.500000, -1.500000, 0.000000)
mov r3.w, l(1.000000)

#line 183
mov r4.xyzw, l(0,0,0,0)  // r4.x <- g.x; r4.y <- g.y; r4.z <- g.z; r4.w <- g.w
mov r2.w, l(0)  // r2.w <- i
loop 
  ge r5.x, r2.w, r2.x
  breakc_nz r5.x

#line 185
  mad r5.x, r2.w, l(0.250000), l(0.125000)

#line 167
  mul r5.x, r5.x, l(6.283185)

#line 168
  sincos r5.x, r6.x, r5.x
  mul r5.xy, r2.yzyy, r5.xxxx
  mad r7.x, r6.x, r2.z, r5.x  // r7.x <- <r2dlocal_id30 return value>.x
  mad r7.y, r6.x, r2.y, -r5.y  // r7.y <- <r2dlocal_id30 return value>.y

#line 185
  div r5.xy, r7.xyxx, cb1[1].xyxx
  mul r5.xy, r5.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  exp r5.z, r2.w
  mad r5.xy, r5.xyxx, r5.zzzz, v1.xyxx
  add r5.z, r2.w, l(1.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r3.xyz, r5.xyxx, t0.xyzw, s0, r5.z
  mad r5.x, r2.w, cb0[2].w, -r1.x
  add r5.x, r5.x, l(1.000000)
  exp r5.x, r5.x
  mul r6.xyzw, r3.xyzw, r5.xxxx
  max r6.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  log r6.xyzw, r6.xyzw
  mul r6.xyzw, r6.xyzw, l(0.800000, 0.800000, 0.800000, 0.800000)
  exp r6.xyzw, r6.xyzw
  mad r3.x, cb0[2].x, r1.x, -r2.w
  add_sat r3.x, r3.x, l(1.000000)
  mad r4.xyzw, r6.xyzw, r3.xxxx, r4.xyzw

#line 186
  mov r2.w, r5.z
endloop 

#line 187
div r2.xyz, r4.xyzx, r4.wwww  // r2.x <- g.x; r2.y <- g.y; r2.z <- g.z

#line 190
mul r2.xyz, r2.xyzx, cb0[1].xxxx

#line 154
eq r3.xyz, r1.yzwy, l(0.000000, 0.000000, 0.000000, 0.000000)
and r3.xyz, r3.xyzx, l(0x3727c5ac, 0x3727c5ac, 0x3727c5ac, 0)
add r3.xyz, r1.yzwy, r3.xyzx  // r3.x <- x.x; r3.y <- x.y; r3.z <- x.z

#line 155
dp3 r1.x, r3.xyzx, r3.xyzx
rsq r1.x, r1.x
mul r3.xyz, r1.xxxx, r3.xyzx  // r3.x <- <safenormalize_id31 return value>.x; r3.y <- <safenormalize_id31 return value>.y; r3.z <- <safenormalize_id31 return value>.z

#line 193
mul r3.xyz, r3.xyzx, l(1.414214, 1.414214, 1.414214, 0.000000)
dp3 r1.x, r1.yzwy, r1.yzwy
sqrt r1.x, r1.x
mul r1.x, r1.x, l(0.707107)

#line 150
exp r1.y, cb0[1].w  // r1.y <- <PreGamma_id32 return value>

#line 193
log r1.x, r1.x
mul r1.x, r1.x, r1.y
exp r1.x, r1.x
mad r1.xyz, r3.xyzx, r1.xxxx, r2.xyzx
dp3 r1.x, r1.xyzx, r1.xyzx
mul r2.w, r1.x, r1.x  // r2.w <- c.w

#line 215
add r1.xyzw, -r0.xyzw, r2.xyzw
mad o0.xyzw, cb0[0].xyzw, r1.xyzw, r0.xyzw

#line 224
ret 
// Approximately 67 instruction slots used
***************************
*************************/
static const float PW_id96 = 4.0f;
static const float PW0_id97 = 7.0;
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id98;
    float InputValue_id99;
    float InputValue_id100;
    float InputValue_id101;
    float InputValue_id102;
    float InputValue_id103;
    float InputValue_id104;
    float InputValue_id105;
    float InputValue_id106;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float PreGamma_id32(float highlightBoost)
{
    return pow(2, highlightBoost);
}
float3 safenormalize_id31(float3 x)
{
    x = lerp(x, x + .00001, x == 0);
    return normalize(x);
}
float Compute_id39()
{
    return InputValue_id99;
}
float Compute_id38()
{
    return InputValue_id106;
}
float2 r2dlocal_id30(float2 x, float a)
{
    a *= acos(-1) * 2;
    return float2(cos(a) * x.x + sin(a) * x.y, cos(a) * x.y - sin(a) * x.x);
}
float Compute_id37()
{
    return InputValue_id103;
}
float4 GlowPass_id34(inout PS_STREAMS streams, float highlightBoost)
{
    float2 R = ViewSize_id77;
    float2 uv = streams.TexCoord_id62;
    float lod = log2(max(R.x, R.y));
    float4 s = Texture1_id16.Sample(Sampler1_id53, uv);
    float4 g = 0;
    float maxRadius = Compute_id37();

    for (float i = 0; i < min(lod - (1 - maxRadius * lod), 14); i++)
    {
        g += pow(max(0, float4(Texture0_id14.SampleLevel(Sampler0_id52, uv + r2dlocal_id30((uv * R) % 4 - 1.5, i * .25 + .125) / R * .5 * pow(2, i), i + 1).rgb, 1) * pow(2, i * Compute_id38() - lod + 1)), .8) * saturate(maxRadius * lod - i + 1);
    }
    g.rgb /= g.a;
    float srcAvg = length(Texture1_id16.SampleLevel(Sampler1_id53, uv, 33).rgb);
    float srcMax = pow(max(0, Texture0_id14.SampleLevel(Sampler0_id52, uv, 33).a), 1. / PW0_id97);
    g.rgb *= Compute_id39();
    float4 c = 0;
    c.rgb = g.rgb;
    c.a = pow(length(g.rgb + safenormalize_id31(s.rgb) * sqrt(2) * pow(length(s.rgb) / sqrt(2), PreGamma_id32(highlightBoost))), PW_id96);
    return c;
}
float Compute_id36()
{
    return InputValue_id102;
}
float4 Compute_id35()
{
    return InputValue_id98;
}
float4 Filter_id33(inout PS_STREAMS streams, float4 tex0col)
{
    return GlowPass_id34(streams, Compute_id36());
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id33(streams, col), Compute_id35());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
