/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:128 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_2053160965]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 256]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_61_id23 => input_61
@C    input_722_id25 => input_722
@C    input_667_id26 => input_667
@C    input_682_id27 => input_682
@C    input_660_id28 => input_660
@C    input_259_id29 => input_259
@C    input_813_id30 => input_813
@C    input_801_id31 => input_801
@C    input_530_id32 => input_530
@C    input_475_id33 => input_475
@C    input_490_id34 => input_490
@C    input_468_id35 => input_468
@C    input_256_id36 => input_256
@C    input_621_id37 => input_621
@C    input_609_id38 => input_609
@C    input_253_id39 => input_253
@C    input_262_id40 => input_262
@C    input_67_id41 => input_67
@C    input_856_id42 => input_856
@C    input_70_id43 => input_70
@C    input_250_id44 => input_250
@C    input_73_id45 => input_73
@C    input_153_id46 => input_153
@C    input_265_id47 => input_265
@C    input_271_id48 => input_271
@C    input_274_id49 => input_274
@C    input_268_id50 => input_268
@C    input_277_id51 => input_277
@C    input_150_id52 => input_150
@C    input_279_id53 => input_279
@C    input_247_id54 => input_247
@C    input_1313_id55 => input_1313
@C    input_282_id56 => input_282
@C    input_285_id57 => input_285
@C    input_288_id58 => input_288
@C    input_291_id59 => input_291
@C    input_294_id60 => input_294
***************************
******  Resources    ******
***************************
@R    input_1454_id24 => input_1454 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_2053160965 => 6f04ae73025ff0de35eb4ec393bacb2e
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCoreMathPCG => e529e3d6e7220073ba1b2dacab9e88b2
@S    FuseCommonNoise => 3f02e963c0659922f30af148bd892f2e
@S    FuseCommonNoiseSine => 55f799131307b926727835d76f9d9035
@S    FuseCoreMath => fdeacca3b2f02b9acb6430ed603f50b4
@S    FuseCoreMathHash => 42d92f741cb65685eaeb5283e61f2c82
@S    FuseCommonNoiseLUT => 0a545f8fb0b0163cd07ba942c45abbce
@S    FuseCommonNoiseValueNoise => 598ea3c9dd7c5fed506e079ef91b1d81
@S    FuseCommonNoiseGradientNoise => 275a1c68a04d0e8c934e4792e8de1a02
@S    FuseCommonNoiseSimplex => cff83c6dcba0e92106f65f2c730e3e35
@S    FuseCommonNoiseRandom => c9e5885d1263580889df6cfb5c437ec3
@S    FuseCommonNoiseWorley => c3806e1a0979a6fbc12110d25e4876f8
@S    FuseCoreMathMap => 07cc7a2921946bb474dce82779ab3f2b
@S    Global => f3a73f928089a02788395f11e18f679c
***************************
*****     Stages      *****
***************************
@G    Compute => 4a1c3d1cd8b7cd9375308f94e2ce805c
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int input_61_id23;                 // Offset:   12 Size:     4
//   int input_722_id25;                // Offset:   16 Size:     4
//   int input_667_id26;                // Offset:   20 Size:     4
//   int input_682_id27;                // Offset:   24 Size:     4
//   int input_660_id28;                // Offset:   28 Size:     4
//   float input_259_id29;              // Offset:   32 Size:     4
//   int input_813_id30;                // Offset:   36 Size:     4
//   int input_801_id31;                // Offset:   40 Size:     4
//   int input_530_id32;                // Offset:   44 Size:     4
//   int input_475_id33;                // Offset:   48 Size:     4
//   int input_490_id34;                // Offset:   52 Size:     4
//   int input_468_id35;                // Offset:   56 Size:     4
//   float input_256_id36;              // Offset:   60 Size:     4
//   int input_621_id37;                // Offset:   64 Size:     4
//   int input_609_id38;                // Offset:   68 Size:     4
//   float3 input_253_id39;             // Offset:   80 Size:    12
//   float input_262_id40;              // Offset:   92 Size:     4
//   bool input_67_id41;                // Offset:   96 Size:     4
//   int input_856_id42;                // Offset:  100 Size:     4
//   int input_70_id43;                 // Offset:  104 Size:     4
//   float input_250_id44;              // Offset:  108 Size:     4
//   float input_73_id45;               // Offset:  112 Size:     4
//   float input_153_id46;              // Offset:  116 Size:     4
//   float input_265_id47;              // Offset:  120 Size:     4
//   float3 input_271_id48;             // Offset:  128 Size:    12
//   float3 input_274_id49;             // Offset:  144 Size:    12
//   float3 input_268_id50;             // Offset:  160 Size:    12
//   float3 input_277_id51;             // Offset:  176 Size:    12
//   float input_150_id52;              // Offset:  188 Size:     4
//   bool input_279_id53;               // Offset:  192 Size:     4
//   bool input_247_id54;               // Offset:  196 Size:     4
//   float3 input_1313_id55;            // Offset:  208 Size:    12
//   float3 input_282_id56;             // Offset:  224 Size:    12
//   float input_285_id57;              // Offset:  236 Size:     4
//   float input_288_id58;              // Offset:  240 Size:     4
//   float input_291_id59;              // Offset:  244 Size:     4
//   float input_294_id60;              // Offset:  248 Size:     4
//
// }
//
// Resource bind info for input_1454_id24
// {
//
//   struct Particle
//   {
//       
//       float3 Velocity;               // Offset:    0
//       float3 Position;               // Offset:   12
//       float4 Color;                  // Offset:   24
//       float Drag;                    // Offset:   40
//       int Cycle;                     // Offset:   44
//       float Age;                     // Offset:   48
//       float LifeTime;                // Offset:   52
//       int Id;                        // Offset:   56
//       float3 AxisY;                  // Offset:   60
//       float3 AxisX;                  // Offset:   72
//       float3 AxisZ;                  // Offset:   84
//       float3 Size3;                  // Offset:   96
//
//   } $Element;                        // Offset:    0 Size:   108
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// input_1454_id24                       UAV  struct         r/w             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[16], immediateIndexed
dcl_uav_structured u0, 108
dcl_input vThreadID.x
dcl_temps 18
dcl_thread_group 128, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 204 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_ComputeFXEffect_8d328f7d4bbb95a6651b22d63fb59458.hlsl"
ilt r0.x, vThreadID.x, cb0[0].w
if_nz r0.x

#line 205
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw  // r0.x <- result_1456.Velocity.x; r0.y <- result_1456.Velocity.y; r0.z <- result_1456.Velocity.z; r0.w <- result_1456.Position.x
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(16), u0.xyzw  // r1.x <- result_1456.Position.y; r1.y <- result_1456.Position.z; r1.z <- result_1456.Color.x; r1.w <- result_1456.Color.y
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(32), u0.zwxy  // r2.z <- result_1456.Color.z; r2.w <- result_1456.Color.w; r2.x <- result_1456.Drag; r2.y <- result_1456.Cycle
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r3.xyz, vThreadID.x, l(48), u0.yzxx  // r3.z <- result_1456.Age; r3.x <- result_1456.LifeTime; r3.y <- result_1456.Id

#line 186
  imul null, r4.x, vThreadID.x, l(0x0019660d)
  imul null, r4.yz, cb0[1].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r4.xyz, r4.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r4.x <- v.x; r4.y <- v.y; r4.z <- v.z

#line 187
  imad r5.x, r4.y, r4.z, r4.x  // r5.x <- v.x

#line 188
  imad r5.y, r4.z, r5.x, r4.y  // r5.y <- v.y

#line 189
  imad r5.z, r5.x, r5.y, r4.z  // r5.z <- v.z

#line 190
  ushr r4.xyz, r5.xyzx, l(16, 16, 16, 0)
  xor r4.xyz, r4.xyzx, r5.xyzx  // r4.x <- v.x; r4.y <- v.y; r4.z <- v.z

#line 191
  imad r4.x, r4.y, r4.z, r4.x

#line 194
  utof r4.x, r4.x

#line 213
  mad r4.x, r4.x, l(0.000000), l(-1.000000)  // r4.x <- result_751

#line 214
  mul r4.x, r4.x, l(3.141593)  // r4.x <- result_754

#line 215
  sincos r4.x, r5.x, r4.x  // r4.x <- result_757; r5.x <- result_760

#line 186
  imul null, r6.x, vThreadID.x, l(0x0019660d)
  imul null, r6.yz, cb0[1].zzwz, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r5.yzw, r6.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r5.y <- v.x; r5.z <- v.y; r5.w <- v.z

#line 187
  imad r6.x, r5.z, r5.w, r5.y  // r6.x <- v.x

#line 188
  imad r6.y, r5.w, r6.x, r5.z  // r6.y <- v.y

#line 189
  imad r6.z, r6.x, r6.y, r5.w  // r6.z <- v.z

#line 190
  ushr r5.yzw, r6.xxyz, l(0, 16, 16, 16)
  xor r5.yzw, r5.yyzw, r6.xxyz  // r5.y <- v.x; r5.z <- v.y; r5.w <- v.z

#line 191
  imad r4.z, r5.z, r5.w, r5.y  // r4.z <- v.x

#line 194
  utof r4.z, r4.z

#line 223
  mad r6.z, r4.z, l(0.000000), l(-1.000000)  // r6.z <- result_711

#line 225
  mad r4.z, -r6.z, r6.z, l(1.000000)  // r4.z <- result_771

#line 226
  sqrt r4.z, r4.z  // r4.z <- result_774

#line 228
  mov r4.y, r5.x
  mul r6.xy, r4.zzzz, r4.xyxx  // r6.x <- result_780.x; r6.y <- result_780.y

#line 233
  mul r4.xyz, r6.xyzx, cb0[2].xxxx  // r4.x <- result_798.x; r4.y <- result_798.y; r4.z <- result_798.z

#line 186
  imul null, r5.x, vThreadID.x, l(0x0019660d)
  imul null, r5.yz, cb0[2].yyzy, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r5.xyz, r5.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 187
  imad r6.x, r5.y, r5.z, r5.x  // r6.x <- v.x

#line 188
  imad r6.y, r5.z, r6.x, r5.y  // r6.y <- v.y

#line 189
  imad r6.z, r6.x, r6.y, r5.z  // r6.z <- v.z

#line 190
  ushr r5.xyz, r6.xyzx, l(16, 16, 16, 0)
  xor r5.xyz, r5.xyzx, r6.xyzx  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 191
  imad r4.w, r5.y, r5.z, r5.x  // r4.w <- v.x

#line 194
  utof r4.w, r4.w
  mul r4.w, r4.w, l(0.000000)  // r4.w <- <pcg3d_id81 return value>.x

#line 238
  log r4.w, r4.w
  mul r4.w, r4.w, l(0.333333)
  exp r4.w, r4.w  // r4.w <- result_839

#line 240
  mul r4.xyz, r4.wwww, r4.xyzx  // r4.x <- result_845.x; r4.y <- result_845.y; r4.z <- result_845.z

#line 186
  imul null, r5.x, vThreadID.x, l(0x0019660d)
  imul null, r5.y, cb0[2].w, l(0x0019660d)
  imul null, r5.z, cb0[3].x, l(0x0019660d)
  iadd r5.xyz, r5.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 187
  imad r6.x, r5.y, r5.z, r5.x  // r6.x <- v.x

#line 188
  imad r6.y, r5.z, r6.x, r5.y  // r6.y <- v.y

#line 189
  imad r6.z, r6.x, r6.y, r5.z  // r6.z <- v.z

#line 190
  ushr r5.xyz, r6.xyzx, l(16, 16, 16, 0)
  xor r5.xyz, r5.xyzx, r6.xyzx  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 191
  imad r4.w, r5.y, r5.z, r5.x  // r4.w <- v.x

#line 194
  utof r4.w, r4.w

#line 248
  mad r4.w, r4.w, l(0.000000), l(-1.000000)  // r4.w <- result_559

#line 249
  mul r4.w, r4.w, l(3.141593)  // r4.w <- result_562

#line 250
  sincos r5.x, r6.x, r4.w  // r5.x <- result_565; r6.x <- result_568

#line 186
  imul null, r7.x, vThreadID.x, l(0x0019660d)
  imul null, r7.yz, cb0[3].yyzy, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r6.yzw, r7.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r6.y <- v.x; r6.z <- v.y; r6.w <- v.z

#line 187
  imad r7.x, r6.z, r6.w, r6.y  // r7.x <- v.x

#line 188
  imad r7.y, r6.w, r7.x, r6.z  // r7.y <- v.y

#line 189
  imad r7.z, r7.x, r7.y, r6.w  // r7.z <- v.z

#line 190
  ushr r6.yzw, r7.xxyz, l(0, 16, 16, 16)
  xor r6.yzw, r6.yyzw, r7.xxyz  // r6.y <- v.x; r6.z <- v.y; r6.w <- v.z

#line 191
  imad r4.w, r6.z, r6.w, r6.y  // r4.w <- v.x

#line 194
  utof r4.w, r4.w

#line 258
  mad r7.z, r4.w, l(0.000000), l(-1.000000)  // r7.z <- result_519

#line 260
  mad r4.w, -r7.z, r7.z, l(1.000000)  // r4.w <- result_579

#line 261
  sqrt r4.w, r4.w  // r4.w <- result_582

#line 263
  mov r5.y, r6.x
  mul r7.xy, r4.wwww, r5.xyxx  // r7.x <- result_588.x; r7.y <- result_588.y

#line 268
  mul r5.xyz, r7.xyzx, cb0[3].wwww  // r5.x <- result_606.x; r5.y <- result_606.y; r5.z <- result_606.z

#line 186
  imul null, r6.x, vThreadID.x, l(0x0019660d)
  imul null, r6.yz, cb0[4].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r6.xyz, r6.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 187
  imad r7.x, r6.y, r6.z, r6.x  // r7.x <- v.x

#line 188
  imad r7.y, r6.z, r7.x, r6.y  // r7.y <- v.y

#line 189
  imad r7.z, r7.x, r7.y, r6.z  // r7.z <- v.z

#line 190
  ushr r6.xyz, r7.xyzx, l(16, 16, 16, 0)
  xor r6.xyz, r6.xyzx, r7.xyzx  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 191
  imad r4.w, r6.y, r6.z, r6.x  // r4.w <- v.x

#line 194
  utof r4.w, r4.w
  mul r4.w, r4.w, l(0.000000)  // r4.w <- <pcg3d_id81 return value>.x

#line 273
  log r4.w, r4.w
  mul r4.w, r4.w, l(0.333333)
  exp r4.w, r4.w  // r4.w <- result_647

#line 276
  mad r5.xyz, r5.xyzx, r4.wwww, cb0[5].xyzx  // r5.x <- result_657.x; r5.y <- result_657.y; r5.z <- result_657.z

#line 280
  iadd r4.w, r2.y, l(1)  // r4.w <- result_1009

#line 186
  imul null, r6.x, vThreadID.x, l(0x0019660d)
  imul null, r6.yz, cb0[6].yyzy, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r6.xyz, r6.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 187
  imad r7.x, r6.y, r6.z, r6.x  // r7.x <- v.x

#line 188
  imad r7.y, r6.z, r7.x, r6.y  // r7.y <- v.y

#line 189
  imad r7.z, r7.x, r7.y, r6.z  // r7.z <- v.z

#line 190
  ushr r6.xyz, r7.xyzx, l(16, 16, 16, 0)
  xor r6.xyz, r6.xyzx, r7.xyzx  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 191
  imad r6.x, r6.y, r6.z, r6.x

#line 194
  utof r6.x, r6.x
  mul r6.x, r6.x, l(0.000000)  // r6.x <- <pcg3d_id81 return value>.x

#line 289
  lt r6.x, r6.x, cb0[6].w  // r6.x <- result_1029

#line 290
  ieq r6.y, r2.y, l(0)  // r6.y <- result_1056

#line 291
  lt r6.z, r3.z, l(0.000000)  // r6.z <- result_1060

#line 292
  or r6.y, r6.z, r6.y  // r6.y <- result_1062

#line 295
  ine r6.z, cb0[6].x, l(0)
  and r6.x, r6.x, r6.z
  and r6.x, r6.y, r6.x  // r6.x <- result_1068

#line 306
  mov r7.xy, r1.zwzz
  mov r7.zw, r2.zzzw
  movc r7.xyzw, r6.xxxx, l(1.000000,1.000000,1.000000,1.000000), r7.zwxy  // r7.x <- result_1480.z; r7.y <- result_1480.w; r7.z <- result_1480.x; r7.w <- result_1480.y
  movc r8.x, r6.x, l(1.000000), r2.x  // r8.x <- result_1488
  movc r8.y, r6.x, r4.w, r2.y  // r8.y <- result_1496
  movc r8.z, r6.x, cb0[5].w, r3.x  // r8.z <- result_1512
  movc r8.w, r6.x, vThreadID.x, r3.y  // r8.w <- result_1520
  movc r0.xyz, r6.xxxx, r4.xyzx, r0.xyzx  // r0.x <- result_1464.x; r0.y <- result_1464.y; r0.z <- result_1464.z
  mov r5.w, l(0)
  mov r3.x, r0.w
  mov r3.yw, r1.xxxy
  movc r1.xyzw, r6.xxxx, r5.xyzw, r3.xywz  // r1.x <- result_1472.x; r1.y <- result_1472.y; r1.z <- result_1472.z; r1.w <- result_1504

#line 310
  mul r2.xyz, r1.xyzx, cb0[7].yyyy  // r2.x <- result_1093.x; r2.y <- result_1093.y; r2.z <- result_1093.z

#line 319
  mul r2.xyz, r2.xyzx, cb0[8].xyzx  // r2.x <- result_1200.x; r2.y <- result_1200.y; r2.z <- result_1200.z
  mov r2.w, cb0[7].z  // r2.w <- result_1200.w

#line 155
  add r3.xyzw, r2.xyzw, l(17.000000, 17.000000, 17.000000, 17.000000)  // r3.x <- p2.x; r3.y <- p2.y; r3.z <- p2.z; r3.w <- p2.w

#line 156
  add r4.xyzw, r2.xyzw, l(-43.700001, -43.700001, -43.700001, -43.700001)  // r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z; r4.w <- p3.w

#line 114
  dp4 r0.w, r2.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r5.xyzw, r0.wwww, r2.xyzw
  round_ni r5.xyzw, r5.xyzw  // r5.x <- i.x; r5.y <- i.y; r5.z <- i.z; r5.w <- i.w

#line 115
  add r2.xyzw, r2.xyzw, -r5.xyzw
  dp4 r0.w, r5.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r2.xyzw, r0.wwww, r2.xyzw  // r2.x <- x0.x; r2.y <- x0.y; r2.z <- x0.z; r2.w <- x0.w

#line 117
  ge r6.xyz, r2.xxxx, r2.yzwy
  and r9.xyz, r6.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r9.x <- isX.x; r9.y <- isX.y; r9.z <- isX.z

#line 118
  ge r10.xyz, r2.yyzy, r2.zwwz
  and r11.xyz, r10.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r11.x <- isYZ.x; r11.y <- isYZ.y; r11.z <- isYZ.z

#line 119
  add r0.w, r9.y, r9.x
  add r9.x, r9.z, r0.w  // r9.x <- i0.x

#line 120
  movc r6.xyz, r6.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r6.x <- i0.y; r6.y <- i0.z; r6.z <- i0.w

#line 121
  add r0.w, r11.y, r11.x
  add r9.y, r0.w, r6.x  // r9.y <- i0.y

#line 124
  movc r10.xyz, r10.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 122
  add r6.xy, r6.yzyy, r10.xyxx
  mov r11.w, l(1.000000)
  add r6.xz, r6.yyxy, r11.wwzw  // r6.x <- i0.w

#line 123
  add r9.z, r6.z, l(1.000000)  // r9.z <- i0.z

#line 124
  add r6.w, r10.z, r6.x
  add r9.w, r6.w, l(1.000000)  // r9.w <- i0.w

#line 125
  min r10.xyzw, r9.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r10.x <- i3.y; r10.y <- i3.z; r10.z <- i3.x; r10.w <- i3.w

#line 126
  mov r6.xy, r9.xyxx
  add_sat r9.xyzw, r6.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r9.x <- i2.x; r9.y <- i2.y; r9.z <- i2.z; r9.w <- i2.w

#line 127
  add r6.xyzw, r6.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r6.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r6.x <- i1.x; r6.y <- i1.y; r6.z <- i1.z; r6.w <- i1.w

#line 128
  add r11.xyzw, r2.xyzw, -r6.xyzw
  add r11.xyzw, r11.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r11.x <- x1.x; r11.y <- x1.y; r11.z <- x1.z; r11.w <- x1.w

#line 129
  add r12.xyzw, r2.xyzw, -r9.xyzw
  add r12.xyzw, r12.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r12.x <- x2.x; r12.y <- x2.y; r12.z <- x2.z; r12.w <- x2.w

#line 130
  add r13.xyzw, r2.xyzw, -r10.zxyw
  add r13.xyzw, r13.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r13.x <- x3.x; r13.y <- x3.y; r13.z <- x3.z; r13.w <- x3.w

#line 131
  add r14.xyzw, r2.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)  // r14.x <- x4.x; r14.y <- x4.y; r14.z <- x4.z; r14.w <- x4.w

#line 83
  mul r15.xyzw, r5.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r5.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r5.xyzw  // r5.x <- <mod289_id19 return value>.x; r5.y <- <mod289_id19 return value>.y; r5.z <- <mod289_id19 return value>.z; r5.w <- <mod289_id19 return value>.w

#line 104
  mul r0.w, r5.w, r5.w
  mad r0.w, r0.w, l(34.000000), r5.w

#line 87
  mul r15.x, r0.w, l(0.003460)
  round_ni r15.x, r15.x
  mad r0.w, -r15.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.z, r0.w

#line 104
  mul r15.x, r0.w, r0.w
  mad r0.w, r15.x, l(34.000000), r0.w

#line 87
  mul r15.x, r0.w, l(0.003460)
  round_ni r15.x, r15.x
  mad r0.w, -r15.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.y, r0.w

#line 104
  mul r15.x, r0.w, r0.w
  mad r0.w, r15.x, l(34.000000), r0.w

#line 87
  mul r15.x, r0.w, l(0.003460)
  round_ni r15.x, r15.x
  mad r0.w, -r15.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.x, r0.w

#line 104
  mul r15.x, r0.w, r0.w
  mad r0.w, r15.x, l(34.000000), r0.w

#line 87
  mul r15.x, r0.w, l(0.003460)
  round_ni r15.x, r15.x
  mad r0.w, -r15.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 134
  mov r15.x, r6.w
  mov r15.y, r9.w
  mov r15.z, r10.w
  mov r15.w, l(1.000000)
  add r15.xyzw, r5.wwww, r15.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r15.xyzw, r5.zzzz, r15.xyzw
  mov r16.x, r6.z
  mov r16.y, r9.z
  mov r16.z, r10.y
  mov r16.w, l(1.000000)
  add r15.xyzw, r15.xyzw, r16.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r15.xyzw, r5.yyyy, r15.xyzw
  mov r16.x, r6.y
  mov r16.y, r9.y
  mov r16.z, r10.x
  mov r16.w, l(1.000000)
  add r15.xyzw, r15.xyzw, r16.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r5.xyzw, r5.xxxx, r15.xyzw
  mov r10.x, r6.x
  mov r10.y, r9.x
  mov r10.w, l(1.000000)
  add r5.xyzw, r5.xyzw, r10.xyzw

#line 100
  mul r6.xyzw, r5.xyzw, r5.xyzw
  mad r5.xyzw, r6.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r5.xyzw

#line 83
  mul r6.xyzw, r5.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r6.xyzw, r6.xyzw
  mad r5.xyzw, -r6.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r5.xyzw  // r5.x <- <mod289_id19 return value>.x; r5.y <- <mod289_id19 return value>.y; r5.z <- <mod289_id19 return value>.z; r5.w <- <mod289_id19 return value>.w

#line 93
  mul r6.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r9.w, -r0.w, l(1.500000)  // r9.w <- p.w

#line 95
  lt r10.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r9.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r10.xyz, r0.wwww, r10.xyzx
  itof r10.xyz, r10.xyzx
  add r9.xyz, r6.xyzx, -r10.xyzx  // r9.x <- p.x; r9.y <- p.y; r9.z <- p.z

#line 93
  mul r6.xyz, r5.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r10.w, -r0.w, l(1.500000)  // r10.w <- p.w

#line 95
  lt r15.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r10.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r10.xyz, r6.xyzx, -r15.xyzx  // r10.x <- p.x; r10.y <- p.y; r10.z <- p.z

#line 93
  mul r6.xyz, r5.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r15.w, -r0.w, l(1.500000)  // r15.w <- p.w

#line 95
  lt r16.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r15.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r15.xyz, r6.xyzx, -r16.xyzx  // r15.x <- p.x; r15.y <- p.y; r15.z <- p.z

#line 93
  mul r5.xyz, r5.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r6.w, -r0.w, l(1.500000)  // r6.w <- p.w

#line 95
  lt r16.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r6.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r6.xyz, r5.xyzx, -r16.xyzx  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 93
  mul r5.xyz, r5.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r16.w, -r0.w, l(1.500000)  // r16.w <- p.w

#line 95
  lt r17.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r16.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r17.xyz, r0.wwww, r17.xyzx
  itof r17.xyz, r17.xyzx
  add r16.xyz, r5.xyzx, -r17.xyzx  // r16.x <- p.x; r16.y <- p.y; r16.z <- p.z

#line 141
  dp4 r0.w, r9.xyzw, r9.xyzw
  dp4 r5.x, r10.xyzw, r10.xyzw
  dp4 r5.y, r15.xyzw, r15.xyzw
  dp4 r5.z, r6.xyzw, r6.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r5.x, r5.x  // r5.x <- norm.y
  rsq r5.y, r5.y  // r5.y <- norm.z
  rsq r5.z, r5.z  // r5.z <- norm.w

#line 142
  mul r9.xyzw, r0.wwww, r9.xyzw  // r9.x <- p0.x; r9.y <- p0.y; r9.z <- p0.z; r9.w <- p0.w

#line 143
  mul r10.xyzw, r5.xxxx, r10.xyzw  // r10.x <- p1.x; r10.y <- p1.y; r10.z <- p1.z; r10.w <- p1.w

#line 144
  mul r15.xyzw, r5.yyyy, r15.xyzw  // r15.x <- p2.x; r15.y <- p2.y; r15.z <- p2.z; r15.w <- p2.w

#line 145
  mul r5.xyzw, r5.zzzz, r6.xyzw  // r5.x <- p3.x; r5.y <- p3.y; r5.z <- p3.z; r5.w <- p3.w

#line 146
  dp4 r0.w, r16.xyzw, r16.xyzw
  rsq r0.w, r0.w
  mul r6.xyzw, r0.wwww, r16.xyzw  // r6.x <- p4.x; r6.y <- p4.y; r6.z <- p4.z; r6.w <- p4.w

#line 147
  dp4 r16.x, r2.xyzw, r2.xyzw
  dp4 r16.y, r11.xyzw, r11.xyzw
  dp4 r16.z, r12.xyzw, r12.xyzw
  add r16.xyz, -r16.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r16.xyz, r16.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r16.x <- m0.x; r16.y <- m0.y; r16.z <- m0.z

#line 148
  dp4 r17.x, r13.xyzw, r13.xyzw
  dp4 r17.y, r14.xyzw, r14.xyzw
  add r17.xy, -r17.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r17.xy, r17.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r17.x <- m1.x; r17.y <- m1.y

#line 149
  mul r16.xyz, r16.xyzx, r16.xyzx

#line 150
  mul r17.xy, r17.xyxx, r17.xyxx

#line 151
  mul r16.xyz, r16.xyzx, r16.xyzx
  dp4 r2.x, r9.xyzw, r2.xyzw
  dp4 r2.y, r10.xyzw, r11.xyzw
  dp4 r2.z, r15.xyzw, r12.xyzw
  dp3 r0.w, r16.xyzx, r2.xyzx
  mul r2.xy, r17.xyxx, r17.xyxx
  dp4 r5.x, r5.xyzw, r13.xyzw
  dp4 r5.y, r6.xyzw, r14.xyzw
  dp2 r2.x, r2.xyxx, r5.xyxx
  add r0.w, r0.w, r2.x
  mul r2.x, r0.w, l(49.000000)  // r2.x <- <simplexNoise_id63 return value>

#line 114
  dp4 r0.w, r3.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r5.xyzw, r0.wwww, r3.xyzw
  round_ni r5.xyzw, r5.xyzw  // r5.x <- i.x; r5.y <- i.y; r5.z <- i.z; r5.w <- i.w

#line 115
  add r3.xyzw, r3.xyzw, -r5.xyzw
  dp4 r0.w, r5.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r3.xyzw, r0.wwww, r3.xyzw  // r3.x <- x0.x; r3.y <- x0.y; r3.z <- x0.z; r3.w <- x0.w

#line 117
  ge r6.xyz, r3.xxxx, r3.yzwy
  and r9.xyz, r6.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r9.x <- isX.x; r9.y <- isX.y; r9.z <- isX.z

#line 118
  ge r10.xyz, r3.yyzy, r3.zwwz
  and r11.xyz, r10.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r11.x <- isYZ.x; r11.y <- isYZ.y; r11.z <- isYZ.z

#line 119
  add r0.w, r9.y, r9.x
  add r9.x, r9.z, r0.w  // r9.x <- i0.x

#line 120
  movc r6.xyz, r6.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r6.x <- i0.y; r6.y <- i0.z; r6.z <- i0.w

#line 121
  add r0.w, r11.y, r11.x
  add r9.y, r0.w, r6.x  // r9.y <- i0.y

#line 124
  movc r10.xyz, r10.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 122
  add r6.xy, r6.yzyy, r10.xyxx
  mov r11.w, l(1.000000)
  add r6.xz, r6.yyxy, r11.wwzw  // r6.x <- i0.w

#line 123
  add r9.z, r6.z, l(1.000000)  // r9.z <- i0.z

#line 124
  add r6.w, r10.z, r6.x
  add r9.w, r6.w, l(1.000000)  // r9.w <- i0.w

#line 125
  min r10.xyzw, r9.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r10.x <- i3.y; r10.y <- i3.z; r10.z <- i3.x; r10.w <- i3.w

#line 126
  mov r6.xy, r9.xyxx
  add_sat r9.xyzw, r6.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r9.x <- i2.x; r9.y <- i2.y; r9.z <- i2.z; r9.w <- i2.w

#line 127
  add r6.xyzw, r6.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r6.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r6.x <- i1.x; r6.y <- i1.y; r6.z <- i1.z; r6.w <- i1.w

#line 128
  add r11.xyzw, r3.xyzw, -r6.xyzw
  add r11.xyzw, r11.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r11.x <- x1.x; r11.y <- x1.y; r11.z <- x1.z; r11.w <- x1.w

#line 129
  add r12.xyzw, r3.xyzw, -r9.xyzw
  add r12.xyzw, r12.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r12.x <- x2.x; r12.y <- x2.y; r12.z <- x2.z; r12.w <- x2.w

#line 130
  add r13.xyzw, r3.xyzw, -r10.zxyw
  add r13.xyzw, r13.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r13.x <- x3.x; r13.y <- x3.y; r13.z <- x3.z; r13.w <- x3.w

#line 131
  add r14.xyzw, r3.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)

#line 83
  mul r15.xyzw, r5.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r5.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r5.xyzw  // r5.x <- <mod289_id19 return value>.x; r5.y <- <mod289_id19 return value>.y; r5.z <- <mod289_id19 return value>.z; r5.w <- <mod289_id19 return value>.w

#line 104
  mul r0.w, r5.w, r5.w
  mad r0.w, r0.w, l(34.000000), r5.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.z, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.y, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r5.x, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 134
  mov r15.x, r6.w
  mov r15.y, r9.w
  mov r15.z, r10.w
  mov r15.w, l(1.000000)
  add r15.xyzw, r5.wwww, r15.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r15.xyzw, r5.zzzz, r15.xyzw
  mov r16.x, r6.z
  mov r16.y, r9.z
  mov r16.z, r10.y
  mov r16.w, l(1.000000)
  add r15.xyzw, r15.xyzw, r16.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r15.xyzw, r5.yyyy, r15.xyzw
  mov r16.x, r6.y
  mov r16.y, r9.y
  mov r16.z, r10.x
  mov r16.w, l(1.000000)
  add r15.xyzw, r15.xyzw, r16.xyzw

#line 100
  mul r16.xyzw, r15.xyzw, r15.xyzw
  mad r15.xyzw, r16.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r15.xyzw

#line 83
  mul r16.xyzw, r15.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r16.xyzw, r16.xyzw
  mad r15.xyzw, -r16.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r15.xyzw  // r15.x <- <mod289_id19 return value>.x; r15.y <- <mod289_id19 return value>.y; r15.z <- <mod289_id19 return value>.z; r15.w <- <mod289_id19 return value>.w

#line 134
  add r5.xyzw, r5.xxxx, r15.xyzw
  mov r10.x, r6.x
  mov r10.y, r9.x
  mov r10.w, l(1.000000)
  add r5.xyzw, r5.xyzw, r10.xyzw

#line 100
  mul r6.xyzw, r5.xyzw, r5.xyzw
  mad r5.xyzw, r6.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r5.xyzw

#line 83
  mul r6.xyzw, r5.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r6.xyzw, r6.xyzw
  mad r5.xyzw, -r6.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r5.xyzw  // r5.x <- <mod289_id19 return value>.x; r5.y <- <mod289_id19 return value>.y; r5.z <- <mod289_id19 return value>.z; r5.w <- <mod289_id19 return value>.w

#line 93
  mul r6.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r9.w, -r0.w, l(1.500000)  // r9.w <- p.w

#line 95
  lt r10.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r9.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r10.xyz, r0.wwww, r10.xyzx
  itof r10.xyz, r10.xyzx
  add r9.xyz, r6.xyzx, -r10.xyzx  // r9.x <- p.x; r9.y <- p.y; r9.z <- p.z

#line 93
  mul r6.xyz, r5.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r10.w, -r0.w, l(1.500000)  // r10.w <- p.w

#line 95
  lt r15.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r10.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r10.xyz, r6.xyzx, -r15.xyzx  // r10.x <- p.x; r10.y <- p.y; r10.z <- p.z

#line 93
  mul r6.xyz, r5.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 94
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r15.w, -r0.w, l(1.500000)  // r15.w <- p.w

#line 95
  lt r16.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r15.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r15.xyz, r6.xyzx, -r16.xyzx  // r15.x <- p.x; r15.y <- p.y; r15.z <- p.z

#line 93
  mul r5.xyz, r5.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r6.w, -r0.w, l(1.500000)  // r6.w <- p.w

#line 95
  lt r16.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r6.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r6.xyz, r5.xyzx, -r16.xyzx  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 93
  mul r5.xyz, r5.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r16.w, -r0.w, l(1.500000)  // r16.w <- p.w

#line 95
  lt r17.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r16.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r17.xyz, r0.wwww, r17.xyzx
  itof r17.xyz, r17.xyzx
  add r16.xyz, r5.xyzx, -r17.xyzx  // r16.x <- p.x; r16.y <- p.y; r16.z <- p.z

#line 141
  dp4 r0.w, r9.xyzw, r9.xyzw
  dp4 r2.w, r10.xyzw, r10.xyzw
  dp4 r5.x, r15.xyzw, r15.xyzw
  dp4 r5.y, r6.xyzw, r6.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r2.w, r2.w  // r2.w <- norm.y
  rsq r5.x, r5.x  // r5.x <- norm.z
  rsq r5.y, r5.y  // r5.y <- norm.w

#line 142
  mul r9.xyzw, r0.wwww, r9.xyzw  // r9.x <- p0.x; r9.y <- p0.y; r9.z <- p0.z; r9.w <- p0.w

#line 143
  mul r10.xyzw, r2.wwww, r10.xyzw  // r10.x <- p1.x; r10.y <- p1.y; r10.z <- p1.z; r10.w <- p1.w

#line 144
  mul r15.xyzw, r5.xxxx, r15.xyzw  // r15.x <- p2.x; r15.y <- p2.y; r15.z <- p2.z; r15.w <- p2.w

#line 145
  mul r5.xyzw, r5.yyyy, r6.xyzw  // r5.x <- p3.x; r5.y <- p3.y; r5.z <- p3.z; r5.w <- p3.w

#line 146
  dp4 r0.w, r16.xyzw, r16.xyzw
  rsq r0.w, r0.w
  mul r6.xyzw, r0.wwww, r16.xyzw  // r6.x <- p4.x; r6.y <- p4.y; r6.z <- p4.z; r6.w <- p4.w

#line 147
  dp4 r16.x, r3.xyzw, r3.xyzw
  dp4 r16.y, r11.xyzw, r11.xyzw
  dp4 r16.z, r12.xyzw, r12.xyzw
  add r16.xyz, -r16.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r16.xyz, r16.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r16.x <- m0.x; r16.y <- m0.y; r16.z <- m0.z

#line 148
  dp4 r17.x, r13.xyzw, r13.xyzw
  dp4 r17.y, r14.xyzw, r14.xyzw
  add r17.xy, -r17.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r17.xy, r17.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r17.x <- m1.x; r17.y <- m1.y

#line 149
  mul r16.xyz, r16.xyzx, r16.xyzx

#line 150
  mul r17.xy, r17.xyxx, r17.xyxx

#line 151
  mul r16.xyz, r16.xyzx, r16.xyzx
  dp4 r3.x, r9.xyzw, r3.xyzw
  dp4 r3.y, r10.xyzw, r11.xyzw
  dp4 r3.z, r15.xyzw, r12.xyzw
  dp3 r0.w, r16.xyzx, r3.xyzx
  mul r3.xy, r17.xyxx, r17.xyxx
  dp4 r5.x, r5.xyzw, r13.xyzw
  dp4 r5.y, r6.xyzw, r14.xyzw
  dp2 r2.w, r3.xyxx, r5.xyxx
  add r0.w, r0.w, r2.w
  mul r2.y, r0.w, l(49.000000)  // r2.y <- <simplexNoise_id63 return value>

#line 114
  dp4 r0.w, r4.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r3.xyzw, r0.wwww, r4.xyzw
  round_ni r3.xyzw, r3.xyzw  // r3.x <- i.x; r3.y <- i.y; r3.z <- i.z; r3.w <- i.w

#line 115
  add r4.xyzw, -r3.xyzw, r4.xyzw
  dp4 r0.w, r3.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r4.xyzw, r0.wwww, r4.xyzw  // r4.x <- x0.x; r4.y <- x0.y; r4.z <- x0.z; r4.w <- x0.w

#line 117
  ge r5.xyz, r4.xxxx, r4.yzwy
  and r6.xyz, r5.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r6.x <- isX.x; r6.y <- isX.y; r6.z <- isX.z

#line 118
  ge r9.xyz, r4.yyzy, r4.zwwz
  and r10.xyz, r9.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r10.x <- isYZ.x; r10.y <- isYZ.y; r10.z <- isYZ.z

#line 119
  add r0.w, r6.y, r6.x
  add r6.x, r6.z, r0.w  // r6.x <- i0.x

#line 120
  movc r5.xyz, r5.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r5.x <- i0.y; r5.y <- i0.z; r5.z <- i0.w

#line 121
  add r0.w, r10.y, r10.x
  add r6.y, r0.w, r5.x  // r6.y <- i0.y

#line 124
  movc r9.xyz, r9.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 122
  add r5.xy, r5.yzyy, r9.xyxx
  mov r10.w, l(1.000000)
  add r5.xz, r5.yyxy, r10.wwzw  // r5.x <- i0.w

#line 123
  add r6.z, r5.z, l(1.000000)  // r6.z <- i0.z

#line 124
  add r5.w, r9.z, r5.x
  add r6.w, r5.w, l(1.000000)  // r6.w <- i0.w

#line 125
  min r9.xyzw, r6.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r9.x <- i3.y; r9.y <- i3.z; r9.z <- i3.x; r9.w <- i3.w

#line 126
  mov r5.xy, r6.xyxx
  add_sat r6.xyzw, r5.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r6.x <- i2.x; r6.y <- i2.y; r6.z <- i2.z; r6.w <- i2.w

#line 127
  add r5.xyzw, r5.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r5.xyzw, r5.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r5.x <- i1.x; r5.y <- i1.y; r5.z <- i1.z; r5.w <- i1.w

#line 128
  add r10.xyzw, r4.xyzw, -r5.xyzw
  add r10.xyzw, r10.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r10.x <- x1.x; r10.y <- x1.y; r10.z <- x1.z; r10.w <- x1.w

#line 129
  add r11.xyzw, r4.xyzw, -r6.xyzw
  add r11.xyzw, r11.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r11.x <- x2.x; r11.y <- x2.y; r11.z <- x2.z; r11.w <- x2.w

#line 130
  add r12.xyzw, r4.xyzw, -r9.zxyw
  add r12.xyzw, r12.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r12.x <- x3.x; r12.y <- x3.y; r12.z <- x3.z; r12.w <- x3.w

#line 131
  add r13.xyzw, r4.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)  // r13.x <- x4.x; r13.y <- x4.y; r13.z <- x4.z; r13.w <- x4.w

#line 83
  mul r14.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r3.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id19 return value>.x; r3.y <- <mod289_id19 return value>.y; r3.z <- <mod289_id19 return value>.z; r3.w <- <mod289_id19 return value>.w

#line 104
  mul r0.w, r3.w, r3.w
  mad r0.w, r0.w, l(34.000000), r3.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r3.z, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r3.y, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 133
  add r0.w, r3.x, r0.w

#line 104
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 87
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 134
  mov r14.x, r5.w
  mov r14.y, r6.w
  mov r14.z, r9.w
  mov r14.w, l(1.000000)
  add r14.xyzw, r3.wwww, r14.xyzw

#line 100
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 83
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 134
  add r14.xyzw, r3.zzzz, r14.xyzw
  mov r15.x, r5.z
  mov r15.y, r6.z
  mov r15.z, r9.y
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 100
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 83
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 134
  add r14.xyzw, r3.yyyy, r14.xyzw
  mov r15.x, r5.y
  mov r15.y, r6.y
  mov r15.z, r9.x
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 100
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 83
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 134
  add r3.xyzw, r3.xxxx, r14.xyzw
  mov r9.x, r5.x
  mov r9.y, r6.x
  mov r9.w, l(1.000000)
  add r3.xyzw, r3.xyzw, r9.xyzw

#line 100
  mul r5.xyzw, r3.xyzw, r3.xyzw
  mad r3.xyzw, r5.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r3.xyzw

#line 83
  mul r5.xyzw, r3.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r5.xyzw, r5.xyzw
  mad r3.xyzw, -r5.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r3.xyzw  // r3.x <- <mod289_id19 return value>.x; r3.y <- <mod289_id19 return value>.y; r3.z <- <mod289_id19 return value>.z; r3.w <- <mod289_id19 return value>.w

#line 93
  mul r5.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r6.w, -r0.w, l(1.500000)  // r6.w <- p.w

#line 95
  lt r9.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r6.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r9.xyz, r0.wwww, r9.xyzx
  itof r9.xyz, r9.xyzx
  add r6.xyz, r5.xyzx, -r9.xyzx  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 93
  mul r5.xyz, r3.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r9.w, -r0.w, l(1.500000)  // r9.w <- p.w

#line 95
  lt r14.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r9.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r14.xyz, r0.wwww, r14.xyzx
  itof r14.xyz, r14.xyzx
  add r9.xyz, r5.xyzx, -r14.xyzx  // r9.x <- p.x; r9.y <- p.y; r9.z <- p.z

#line 93
  mul r5.xyz, r3.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r5.xyz, r5.xyzx
  mul r5.xyz, r5.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r5.xyz, r5.xyzx
  mad r5.xyz, r5.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 94
  dp3 r0.w, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r14.w, -r0.w, l(1.500000)  // r14.w <- p.w

#line 95
  lt r15.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r14.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r14.xyz, r5.xyzx, -r15.xyzx  // r14.x <- p.x; r14.y <- p.y; r14.z <- p.z

#line 93
  mul r3.xyz, r3.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r3.xyz, r3.xyzx
  mul r3.xyz, r3.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r3.xyz, r3.xyzx
  mad r3.xyz, r3.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r3.x <- p.x; r3.y <- p.y; r3.z <- p.z

#line 94
  dp3 r0.w, -r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r5.w, -r0.w, l(1.500000)  // r5.w <- p.w

#line 95
  lt r15.xyz, r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r5.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r5.xyz, r3.xyzx, -r15.xyzx  // r5.x <- p.x; r5.y <- p.y; r5.z <- p.z

#line 93
  mul r3.xyz, r3.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r3.xyz, r3.xyzx
  mul r3.xyz, r3.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r3.xyz, r3.xyzx
  mad r3.xyz, r3.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r3.x <- p.x; r3.y <- p.y; r3.z <- p.z

#line 94
  dp3 r0.w, -r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r15.w, -r0.w, l(1.500000)  // r15.w <- p.w

#line 95
  lt r16.xyz, r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r15.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r15.xyz, r3.xyzx, -r16.xyzx  // r15.x <- p.x; r15.y <- p.y; r15.z <- p.z

#line 141
  dp4 r0.w, r6.xyzw, r6.xyzw
  dp4 r2.w, r9.xyzw, r9.xyzw
  dp4 r3.x, r14.xyzw, r14.xyzw
  dp4 r3.y, r5.xyzw, r5.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r2.w, r2.w  // r2.w <- norm.y
  rsq r3.x, r3.x  // r3.x <- norm.z
  rsq r3.y, r3.y  // r3.y <- norm.w

#line 142
  mul r6.xyzw, r0.wwww, r6.xyzw  // r6.x <- p0.x; r6.y <- p0.y; r6.z <- p0.z; r6.w <- p0.w

#line 143
  mul r9.xyzw, r2.wwww, r9.xyzw  // r9.x <- p1.x; r9.y <- p1.y; r9.z <- p1.z; r9.w <- p1.w

#line 144
  mul r14.xyzw, r3.xxxx, r14.xyzw  // r14.x <- p2.x; r14.y <- p2.y; r14.z <- p2.z; r14.w <- p2.w

#line 145
  mul r3.xyzw, r3.yyyy, r5.xyzw  // r3.x <- p3.x; r3.y <- p3.y; r3.z <- p3.z; r3.w <- p3.w

#line 146
  dp4 r0.w, r15.xyzw, r15.xyzw
  rsq r0.w, r0.w
  mul r5.xyzw, r0.wwww, r15.xyzw  // r5.x <- p4.x; r5.y <- p4.y; r5.z <- p4.z; r5.w <- p4.w

#line 147
  dp4 r15.x, r4.xyzw, r4.xyzw
  dp4 r15.y, r10.xyzw, r10.xyzw
  dp4 r15.z, r11.xyzw, r11.xyzw
  add r15.xyz, -r15.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r15.xyz, r15.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r15.x <- m0.x; r15.y <- m0.y; r15.z <- m0.z

#line 148
  dp4 r16.x, r12.xyzw, r12.xyzw
  dp4 r16.y, r13.xyzw, r13.xyzw
  add r16.xy, -r16.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r16.xy, r16.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r16.x <- m1.x; r16.y <- m1.y

#line 149
  mul r15.xyz, r15.xyzx, r15.xyzx

#line 150
  mul r16.xy, r16.xyxx, r16.xyxx

#line 151
  mul r15.xyz, r15.xyzx, r15.xyzx
  dp4 r4.x, r6.xyzw, r4.xyzw
  dp4 r4.y, r9.xyzw, r10.xyzw
  dp4 r4.z, r14.xyzw, r11.xyzw
  dp3 r0.w, r15.xyzx, r4.xyzx
  mul r4.xy, r16.xyxx, r16.xyxx
  dp4 r3.x, r3.xyzw, r12.xyzw
  dp4 r3.y, r5.xyzw, r13.xyzw
  dp2 r2.w, r4.xyxx, r3.xyxx
  add r0.w, r0.w, r2.w
  mul r2.z, r0.w, l(49.000000)  // r2.z <- <simplexNoise_id63 return value>

#line 323
  lt r3.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r2.xyzx
  lt r4.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r3.xyz, -r3.xyzx, r4.xyzx
  itof r3.xyz, r3.xyzx  // r3.x <- result_1221.x; r3.y <- result_1221.y; r3.z <- result_1221.z

#line 108
  lt r4.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[9].xyzx
  div r5.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[9].xyzx
  add r5.xyz, r5.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000)
  add r6.xyz, -|r2.xyzx|, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r5.xyz, r5.xyzx, r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r5.xyz, |r2.xyzx|, r5.xyzx
  div r9.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), |cb0[9].xyzx|
  add r9.xyz, r9.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000)
  mad r6.xyz, r9.xyzx, r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r2.xyz, |r2.xyzx|, r6.xyzx
  add r2.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  movc r2.xyz, r4.xyzx, r5.xyzx, r2.xyzx  // r2.z <- result

#line 326
  mul r2.xyz, r2.xyzx, r3.xyzx  // r2.x <- result_1224.x; r2.y <- result_1224.y; r2.z <- result_1224.z

#line 329
  mad r2.xyz, r2.xyzx, cb0[10].xyzx, cb0[11].xyzx  // r2.x <- result_1245.x; r2.y <- result_1245.y; r2.z <- result_1245.z

#line 331
  div r2.xyz, r2.xyzx, r8.xxxx  // r2.x <- result_1254.x; r2.y <- result_1254.y; r2.z <- result_1254.z

#line 333
  mul r0.w, cb0[7].x, cb0[11].w  // r0.w <- result_1257

#line 338
  mad r2.xyz, r2.xyzx, r0.wwww, r0.xyzx  // r2.x <- result_1297.x; r2.y <- result_1297.y; r2.z <- result_1297.z

#line 340
  movc r0.xyz, cb0[12].xxxx, r2.xyzx, r0.xyzx

#line 345
  mad r2.xyz, r0.xyzx, cb0[7].xxxx, r1.xyzx  // r2.x <- result_363.x; r2.y <- result_363.y; r2.z <- result_363.z

#line 347
  movc r2.xyw, cb0[12].yyyy, r2.yzyx, r1.yzyx  // r2.x <- result_1472.y; r2.y <- result_1472.z; r2.w <- result_1472.x

#line 350
  add r1.x, r1.w, cb0[7].x  // r1.x <- result_413

#line 351
  ilt r1.y, l(0), r8.y  // r1.y <- result_417

#line 352
  ge r1.z, r1.w, l(0.000000)  // r1.z <- result_421

#line 353
  lt r3.x, r1.w, r8.z  // r3.x <- result_424

#line 354
  and r1.y, r1.z, r1.y
  and r1.y, r3.x, r1.y  // r1.y <- result_426

#line 360
  movc r1.x, r1.y, r1.x, l(-1.000000)  // r1.x <- outputParam_441

#line 362
  movc r1.x, cb0[12].y, r1.x, r1.w  // r1.x <- result_1504

#line 364
  dp3 r3.x, r0.xyzx, r0.xyzx
  rsq r3.x, r3.x
  mul r3.xyw, r0.yzyx, r3.xxxx  // r3.x <- result_1394.y; r3.y <- result_1394.z; r3.w <- result_1394.x

#line 367
  mul r4.xyz, r2.wxyw, r3.xywx
  mad r4.xyz, r3.wxyw, r2.xywx, -r4.xyzx  // r4.x <- result_1400.z; r4.y <- result_1400.x; r4.z <- result_1400.y

#line 368
  dp3 r4.w, r4.xyzx, r4.xyzx  // r4.w <- result_1403

#line 369
  lt r5.x, r4.w, l(0.000010)  // r5.x <- result_1406

#line 370
  rsq r4.w, r4.w
  mul r4.xyz, r4.wwww, r4.xyzx  // r4.x <- result_1409.z; r4.y <- result_1409.x; r4.z <- result_1409.y

#line 379
  movc r4.xyz, r5.xxxx, cb0[13].zxyz, r4.xyzx  // r4.x <- result_1412.z; r4.y <- result_1412.x; r4.z <- result_1412.y

#line 382
  mul r5.xyz, r3.xywx, r4.xyzx
  mad r5.yzw, r4.zzxy, r3.yywx, -r5.xxyz  // r5.y <- result_1418.x; r5.z <- result_1418.y; r5.w <- result_1418.z

#line 385
  div_sat r4.w, r1.x, r8.z  // r4.w <- result_1429

#line 160
  add r6.x, -cb0[14].w, cb0[15].x
  add r6.y, r4.w, -cb0[14].w
  div r6.x, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
  mul_sat r6.x, r6.x, r6.y
  mad r6.y, r6.x, l(-2.000000), l(3.000000)
  mul r6.x, r6.x, r6.x
  mul r6.x, r6.x, r6.y
  add r6.y, -cb0[15].y, cb0[15].z
  add r4.w, r4.w, -cb0[15].y
  div r6.y, l(1.000000, 1.000000, 1.000000, 1.000000), r6.y
  mul_sat r4.w, r4.w, r6.y
  mad r6.y, r4.w, l(-2.000000), l(3.000000)
  mul r4.w, r4.w, r4.w
  mad r4.w, -r6.y, r4.w, l(1.000000)
  mul r4.w, r4.w, r6.x  // r4.w <- <smoothstep2_id74 return value>

#line 389
  mul r6.xyz, r4.wwww, cb0[14].xyzx  // r6.x <- result_1439.x; r6.y <- result_1439.y; r6.z <- result_1439.z

#line 405
  mov r0.w, r2.w
  store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
  mov r2.zw, r7.zzzw
  store_structured u0.xyzw, vThreadID.x, l(16), r2.xyzw
  mov r7.zw, r8.xxxy
  store_structured u0.xyzw, vThreadID.x, l(32), r7.xyzw
  mov r1.yz, r8.zzwz
  mov r1.w, r3.w
  store_structured u0.xyzw, vThreadID.x, l(48), r1.xyzw
  mov r3.zw, r4.yyyz
  store_structured u0.xyzw, vThreadID.x, l(64), r3.xyzw
  mov r5.x, r4.x
  store_structured u0.xyzw, vThreadID.x, l(80), r5.xyzw
  store_structured u0.xyz, vThreadID.x, l(96), r6.xyzx
endif 

#line 431
ret 
// Approximately 820 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
static const float3 vectorValuedNoiseOffsets_id22 = float3(17.0, -43.7, 67.0);
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Particle 
{
    float3 Velocity;
    float3 Position;
    float4 Color;
    float Drag;
    int Cycle;
    float Age;
    float LifeTime;
    int Id;
    float3 AxisY;
    float3 AxisX;
    float3 AxisZ;
    float3 Size3;
};
struct Global 
{
    float DeltaTime;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int input_61_id23;
    int input_722_id25;
    int input_667_id26;
    int input_682_id27;
    int input_660_id28;
    float input_259_id29;
    int input_813_id30;
    int input_801_id31;
    int input_530_id32;
    int input_475_id33;
    int input_490_id34;
    int input_468_id35;
    float input_256_id36;
    int input_621_id37;
    int input_609_id38;
    float3 input_253_id39;
    float input_262_id40;
    bool input_67_id41;
    int input_856_id42;
    int input_70_id43;
    float input_250_id44;
    float input_73_id45;
    float input_153_id46;
    float input_265_id47;
    float3 input_271_id48;
    float3 input_274_id49;
    float3 input_268_id50;
    float3 input_277_id51;
    float input_150_id52;
    bool input_279_id53;
    bool input_247_id54;
    float3 input_1313_id55;
    float3 input_282_id56;
    float input_285_id57;
    float input_288_id58;
    float input_291_id59;
    float input_294_id60;
};
RWStructuredBuffer<Particle> input_1454_id24;
RWStructuredBuffer<Global> input_1554_id61;
float4 mod289_id19(float4 x)
{
    return x - floor(x * 0.00346020761245674740484429065744f) * 289.0;
}
float mod289_id17(float x)
{
    return x - floor(x * 0.00346020761245674740484429065744f) * 289.0;
}
float4 grad4_id24(float j, float4 ip)
{
    const float4 ones = float4(1.0, 1.0, 1.0, -1.0);
    float4 p, s;
    p.xyz = floor(frac(j * ip.xyz) * 7.0) * ip.z - 1.0;
    p.w = 1.5 - dot(abs(p.xyz), ones.xyz);
    p.xyz -= sign(p.xyz) * (p.w < 0);
    return p;
}
float4 permute_id22(float4 x)
{
    return mod289_id19(x * x * 34.0 + x);
}
float permute_id23(float x)
{
    return mod289_id17(x * x * 34.0 + x);
}
float bias_id72(float x, float control = 0.5)
{
    float result = control > 0 ? (x / ((((1.0 / control) - 2.0) * (1.0 - x)) + 1.0)) : 1 - (x / ((((1.0 / abs(control)) - 2.0) * (1.0 - x)) + 1.0));
    return result;
}
float simplexNoise_id63(float4 v)
{
    const float4 C = float4(0.138196601125011, 0.276393202250021, 0.414589803375032, -0.447213595499958);
    float4 i = floor(v + dot(v, 0.309016994374947451));
    float4 x0 = v - i + dot(i, C.xxxx);
    float4 i0;
    float3 isX = step(x0.yzw, x0.xxx);
    float3 isYZ = step(x0.zww, x0.yyz);
    i0.x = isX.x + isX.y + isX.z;
    i0.yzw = 1.0 - isX;
    i0.y += isYZ.x + isYZ.y;
    i0.zw += 1.0 - isYZ.xy;
    i0.z += isYZ.z;
    i0.w += 1.0 - isYZ.z;
    float4 i3 = saturate(i0);
    float4 i2 = saturate(i0 - 1.0);
    float4 i1 = saturate(i0 - 2.0);
    float4 x1 = x0 - i1 + C.xxxx;
    float4 x2 = x0 - i2 + C.yyyy;
    float4 x3 = x0 - i3 + C.zzzz;
    float4 x4 = x0 + C.wwww;
    i = mod289_id19(i);
    float j0 = permute_id23(permute_id23(permute_id23(permute_id23(i.w) + i.z) + i.y) + i.x);
    float4 j1 = permute_id22(permute_id22(permute_id22(permute_id22(i.w + float4(i1.w, i2.w, i3.w, 1.0)) + i.z + float4(i1.z, i2.z, i3.z, 1.0)) + i.y + float4(i1.y, i2.y, i3.y, 1.0)) + i.x + float4(i1.x, i2.x, i3.x, 1.0));
    const float4 ip = float4(0.003401360544217687075, 0.020408163265306122449, 0.142857142857142857143, 0.0);
    float4 p0 = grad4_id24(j0, ip);
    float4 p1 = grad4_id24(j1.x, ip);
    float4 p2 = grad4_id24(j1.y, ip);
    float4 p3 = grad4_id24(j1.z, ip);
    float4 p4 = grad4_id24(j1.w, ip);
    float4 norm = rsqrt(float4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
    p0 *= norm.x;
    p1 *= norm.y;
    p2 *= norm.z;
    p3 *= norm.w;
    p4 *= rsqrt(dot(p4, p4));
    float3 m0 = max(0.6 - float3(dot(x0, x0), dot(x1, x1), dot(x2, x2)), 0.0);
    float2 m1 = max(0.6 - float2(dot(x3, x3), dot(x4, x4)), 0.0);
    m0 = m0 * m0;
    m1 = m1 * m1;
    return 49.0 * (dot(m0 * m0, float3(dot(p0, x0), dot(p1, x1), dot(p2, x2))) + dot(m1 * m1, float2(dot(p3, x3), dot(p4, x4))));
}
void noiseDomainOffset_id44(inout float4 p1, out float4 p2, out float4 p3)
{
    p2 = p1 + vectorValuedNoiseOffsets_id22.x;
    p3 = p1 + vectorValuedNoiseOffsets_id22.y;
}
float smoothstep2_id74(float input, float onMin, float onMax, float offMin, float offMax)
{
    return smoothstep(onMin, onMax, input) * (1 - smoothstep(offMin, offMax, input));
}
float3 bias_id86(float3 x, float3 control = 0.5)
{
    return float3(bias_id72(x.x, control.x), bias_id72(x.y, control.y), bias_id72(x.z, control.z));
}
float3 simplexNoise34_id85(float4 p)
{
    float4 p2, p3;
    noiseDomainOffset_id44(p, p2, p3);
    return float3(simplexNoise_id63(p), simplexNoise_id63(p2), simplexNoise_id63(p3));
}
float3 cast31_id84(float p)
{
    return p.xxx;
}
float cast11_id83(float p)
{
    return p;
}
float cast13_id82(float3 p)
{
    return p.x;
}
float3 pcg3d_id81(uint3 v)
{
    v = v * 1664525 + 1013904223;
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v = v ^ (v >> 16);
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    return float3(v) * (1.0 / float(0xffffffff));
}
void Compute_id4(inout CS_STREAMS streams)
{
    int result_1611 = streams.DispatchThreadId_id1.x;
    bool result_1614 = result_1611 >= input_61_id23;
    if (result_1614)
    {
        return;
    }
    int result_1452 = streams.DispatchThreadId_id1.x;
    Particle result_1456 = input_1454_id24[result_1452];
    float3 result_1464 = result_1456.Velocity;
    float result_671 = -1;
    int result_719 = streams.DispatchThreadId_id1.x;
    int3 result_736 = int3(result_719, input_722_id25, input_667_id26);
    float3 result_739 = pcg3d_id81(result_736);
    float result_742 = cast13_id82(result_739);
    float result_748 = cast11_id83(result_742);
    float result_751 = lerp(result_671, 1, result_748);
    float result_754 = 3.1415927 * result_751;
    float result_757 = sin(result_754);
    float result_760 = cos(result_754);
    float2 result_763 = float2(result_757, result_760);
    int result_679 = streams.DispatchThreadId_id1.x;
    int3 result_696 = int3(result_679, input_682_id27, input_660_id28);
    float3 result_699 = pcg3d_id81(result_696);
    float result_702 = cast13_id82(result_699);
    float result_708 = cast11_id83(result_702);
    float result_711 = lerp(result_671, 1, result_708);
    float result_766 = result_711 * result_711;
    float result_771 = 1 - result_766;
    float result_774 = sqrt(result_771);
    float2 result_777 = float2(result_774, result_774);
    float2 result_780 = result_763 * result_777;
    float result_784 = result_780.x;
    float result_788 = result_780.y;
    float3 result_791 = float3(result_784, result_788, result_711);
    float3 result_795 = cast31_id84(input_259_id29);
    float3 result_798 = result_791 * result_795;
    int result_810 = streams.DispatchThreadId_id1.x;
    int3 result_827 = int3(result_810, input_813_id30, input_801_id31);
    float3 result_830 = pcg3d_id81(result_827);
    float result_833 = cast13_id82(result_830);
    float result_839 = pow(result_833, 0.3333333);
    float3 result_842 = float3(result_839, result_839, result_839);
    float3 result_845 = result_798 * result_842;
    float3 result_1472 = result_1456.Position;
    float result_479 = -1;
    int result_527 = streams.DispatchThreadId_id1.x;
    int3 result_544 = int3(result_527, input_530_id32, input_475_id33);
    float3 result_547 = pcg3d_id81(result_544);
    float result_550 = cast13_id82(result_547);
    float result_556 = cast11_id83(result_550);
    float result_559 = lerp(result_479, 1, result_556);
    float result_562 = 3.1415927 * result_559;
    float result_565 = sin(result_562);
    float result_568 = cos(result_562);
    float2 result_571 = float2(result_565, result_568);
    int result_487 = streams.DispatchThreadId_id1.x;
    int3 result_504 = int3(result_487, input_490_id34, input_468_id35);
    float3 result_507 = pcg3d_id81(result_504);
    float result_510 = cast13_id82(result_507);
    float result_516 = cast11_id83(result_510);
    float result_519 = lerp(result_479, 1, result_516);
    float result_574 = result_519 * result_519;
    float result_579 = 1 - result_574;
    float result_582 = sqrt(result_579);
    float2 result_585 = float2(result_582, result_582);
    float2 result_588 = result_571 * result_585;
    float result_592 = result_588.x;
    float result_596 = result_588.y;
    float3 result_599 = float3(result_592, result_596, result_519);
    float3 result_603 = cast31_id84(input_256_id36);
    float3 result_606 = result_599 * result_603;
    int result_618 = streams.DispatchThreadId_id1.x;
    int3 result_635 = int3(result_618, input_621_id37, input_609_id38);
    float3 result_638 = pcg3d_id81(result_635);
    float result_641 = cast13_id82(result_638);
    float result_647 = pow(result_641, 0.3333333);
    float3 result_650 = float3(result_647, result_647, result_647);
    float3 result_653 = result_606 * result_650;
    float3 result_657 = result_653 + input_253_id39;
    float4 result_1480 = result_1456.Color;
    float result_1488 = result_1456.Drag;
    int result_1496 = result_1456.Cycle;
    int result_1009 = result_1496 + 1;
    float result_1504 = result_1456.Age;
    float result_1512 = result_1456.LifeTime;
    int result_1520 = result_1456.Id;
    int result_985 = streams.DispatchThreadId_id1.x;
    int result_853 = streams.DispatchThreadId_id1.x;
    int3 result_870 = int3(result_853, input_856_id42, input_70_id43);
    float3 result_873 = pcg3d_id81(result_870);
    float result_876 = cast13_id82(result_873);
    bool result_1029 = result_876 < input_250_id44;
    bool result_1056 = result_1496 == 0;
    bool result_1060 = result_1504 < 0;
    bool result_1062 = result_1056 || result_1060;
    bool result_1064 = !result_1062;
    bool result_1066 = !result_1064;
    bool result_1068 = input_67_id41 && result_1029 && result_1066;
    if (result_1068)
    {
        result_1464 = result_845;
        result_1472 = result_657;
        result_1480 = float4(1, 1, 1, 1);
        result_1488 = 1;
        result_1496 = result_1009;
        result_1504 = 0;
        result_1512 = input_262_id40;
        result_1520 = result_985;
    }
    float outputParam_1561 = 0;
    outputParam_1561 = input_73_id45;
    float3 result_1090 = float3(input_153_id46, input_153_id46, input_153_id46);
    float3 result_1093 = result_1472 * result_1090;
    float result_1156 = result_1093.x;
    float result_1160 = result_1093.y;
    float result_1164 = result_1093.z;
    float4 result_1167 = float4(result_1156, result_1160, result_1164, input_265_id47);
    float result_1173 = input_271_id48.x;
    float result_1177 = input_271_id48.y;
    float result_1181 = input_271_id48.z;
    float4 result_1184 = float4(result_1173, result_1177, result_1181, 1);
    float4 result_1200 = result_1167 * result_1184;
    float4 result_1191 = float4(0, 0, 0, 0);
    float4 result_1204 = result_1200 + result_1191;
    float3 result_1207 = simplexNoise34_id85(result_1204);
    float3 result_1221 = sign(result_1207);
    float3 result_1214 = abs(result_1207);
    float3 result_1218 = bias_id86(result_1214, input_274_id49);
    float3 result_1224 = result_1221 * result_1218;
    float3 result_1238 = result_1224 * input_268_id50;
    float3 result_1242 = result_1238 + float3(0, 0, 0);
    float3 result_1245 = result_1242 + input_277_id51;
    float3 result_1251 = cast31_id84(result_1488);
    float3 result_1254 = result_1245 / result_1251;
    float result_1248 = input_150_id52;
    float result_1257 = result_1248 * outputParam_1561;
    float3 result_1260 = cast31_id84(result_1257);
    float3 result_1263 = result_1254 * result_1260;
    if (input_279_id53)
    {
        float3 result_1297 = result_1464 + result_1263;
        result_1464 = result_1297;
    }
    if (input_247_id54)
    {
        float3 result_357 = cast31_id84(outputParam_1561);
        float3 result_360 = result_1464 * result_357;
        float3 result_363 = result_1472 + result_360;
        result_1472 = result_363;
    }
    if (input_247_id54)
    {
        float result_413 = result_1504 + outputParam_1561;
        bool result_417 = result_1496 > 0;
        bool result_421 = result_1504 >= 0;
        bool result_424 = result_1504 < result_1512;
        bool result_426 = result_417 && result_421 && result_424;
        float outputParam_441 = -1;
        if (result_426)
        {
            float result_434 = result_413 + 0;
            outputParam_441 = result_434;
        }
        result_1504 = outputParam_441;
    }
    float3 result_1528 = result_1456.AxisY;
    float3 result_1394 = normalize(result_1464);
    result_1528 = result_1394;
    float3 result_1536 = result_1456.AxisX;
    float3 result_1400 = cross(result_1528, result_1472);
    float result_1403 = dot(result_1400, result_1400);
    bool result_1406 = result_1403 < 1E-05;
    float3 result_1409 = normalize(result_1400);
    float3 result_1412;
    if (result_1406)
    {
        result_1412 = input_1313_id55;
    }
    else
    {
        result_1412 = result_1409;
    }
    result_1536 = result_1412;
    float3 result_1544 = result_1456.AxisZ;
    float3 result_1418 = cross(result_1536, result_1528);
    result_1544 = result_1418;
    float3 result_1552 = result_1456.Size3;
    float result_1426 = result_1504 / result_1512;
    float result_1429 = saturate(result_1426);
    float result_1432 = smoothstep2_id74(result_1429, input_285_id57, input_288_id58, input_291_id59, input_294_id60);
    float3 result_1436 = cast31_id84(result_1432);
    float3 result_1439 = input_282_id56 * result_1436;
    result_1552 = result_1439;
    Global result_1556 = input_1554_id61[result_1452];
    input_1554_id61[result_1452] = result_1556;
    result_1456.Velocity = result_1464;
    result_1456.Position = result_1472;
    result_1456.Color = result_1480;
    result_1456.Drag = result_1488;
    result_1456.Cycle = result_1496;
    result_1456.Age = result_1504;
    result_1456.LifeTime = result_1512;
    result_1456.Id = result_1520;
    result_1456.AxisY = result_1528;
    result_1456.AxisX = result_1536;
    result_1456.AxisZ = result_1544;
    result_1456.Size3 = result_1552;
    input_1454_id24[result_1452] = result_1456;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(128, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 128;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 128 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
