/**************************
***** Compiler Parameters *****
***************************
@P EffectName: DrawFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin DrawDCTriangles_DrawFX
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 416]
@C    World_id29 => Transformation.World
@C    WorldInverse_id30 => Transformation.WorldInverse
@C    WorldInverseTranspose_id31 => Transformation.WorldInverseTranspose
@C    WorldView_id32 => Transformation.WorldView
@C    WorldViewInverse_id33 => Transformation.WorldViewInverse
@C    WorldViewProjection_id34 => Transformation.WorldViewProjection
@C    WorldScale_id35 => Transformation.WorldScale
@C    EyeMS_id36 => Transformation.EyeMS
cbuffer Globals [Size: 32]
@C    Color_id52 => DrawDCTriangles_DrawFX.Color
@C    SizeMult_id53 => DrawDCTriangles_DrawFX.SizeMult
***************************
******  Resources    ******
***************************
@R    Vertices_id50 => DrawDCTriangles_DrawFX.Vertices [Stage: Geometry, Slot: (0-0)]
@R    Indices_id51 => DrawDCTriangles_DrawFX.Indices [Stage: Geometry, Slot: (1-1)]
@R    PerDraw => PerDraw [Stage: Geometry, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    DrawDCTriangles_DrawFX => 977459efeeec1fa7351cc612f7653819
@S    VS_PS_Base => f089dc4ce5d5868b962b08793ef74fd9
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    NormalStream => ea68512133899a045766d21afb59733a
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    SDFVertex => a55fb6c0cb5db6eac29bd614045e195f
***************************
*****     Stages      *****
***************************
@G    Vertex => 6fa932810f3c5923ae3e6e7c63958a08
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_InstanceID            0   x           0   INSTID    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_InstanceID            0   x           0     NONE    uint   x   
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input_sgv v0.x, instance_id
dcl_output o0.x
//
// Initial variable locations:
//   v0.x <- __input__; 
//   o0.x <- <VSMain return value>
//
#line 116 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_DrawFXEffect_03591c3f37504fa17b1197079bde9a1e.hlsl"
mov o0.x, v0.x
ret 
// Approximately 2 instruction slots used
@G    Geometry => c2ee244ebf0977c6332d05ae26f3e5b7
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id29;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id30;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id31;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id32;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id33;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id34; // Offset:  320 Size:    64
//   float3 WorldScale_id35;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id36;                 // Offset:  400 Size:    16 [unused]
//
// }
//
// Resource bind info for Vertices_id50
// {
//
//   struct Vertex
//   {
//       
//       float3 position;               // Offset:    0
//       float3 normal;                 // Offset:   12
//
//   } $Element;                        // Offset:    0 Size:    24
//
// }
//
// Resource bind info for Indices_id51
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Vertices_id50                     texture  struct         r/o             t0      1 
// Indices_id51                      texture  struct         r/o             t1      1 
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_InstanceID            0   x           0     NONE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[24], immediateIndexed
dcl_resource_structured t0, 24
dcl_resource_structured t1, 4
dcl_input v[1][0].x
dcl_temps 2
dcl_inputprimitive point 
dcl_stream m0
dcl_outputtopology trianglestrip 
dcl_output_siv o0.xyzw, position
dcl_maxout 3
//
// Initial variable locations:
//   m0 <- triangleStream; 
//   v[0][0].x <- input
//
#line 96 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_DrawFXEffect_03591c3f37504fa17b1197079bde9a1e.hlsl"
mov r0.w, l(1.000000)

#line 93
mov r1.x, l(0)  // r1.x <- i
loop 
  ige r1.y, r1.x, l(3)
  breakc_nz r1.y

#line 95
  imad r1.y, v[0][0].x, l(3), r1.x
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.y, l(0), t1.xxxx
  ld_structured_indexable(structured_buffer, stride=24)(mixed,mixed,mixed,mixed) r0.xyz, r1.y, l(0), t0.xyzx  // r0.x <- pos.x; r0.y <- pos.y; r0.z <- pos.z

#line 96
  dp4 r1.y, r0.xyzw, cb0[20].xyzw  // r1.y <- streams.ShadingPosition_id0.x
  dp4 r1.z, r0.xyzw, cb0[21].xyzw  // r1.z <- streams.ShadingPosition_id0.y
  dp4 r1.w, r0.xyzw, cb0[22].xyzw  // r1.w <- streams.ShadingPosition_id0.z
  dp4 r0.x, r0.xyzw, cb0[23].xyzw  // r0.x <- streams.ShadingPosition_id0.w

#line 101
  mov o0.x, r1.y
  mov o0.y, r1.z
  mov o0.z, r1.w
  mov o0.w, r0.x
  emit_stream m0

#line 103
  iadd r1.x, r1.x, l(1)
endloop 

#line 104
ret 
// Approximately 20 instruction slots used
@G    Pixel => 2ab39ddc2df6ad58f2a9283bd8bf0c34
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Globals
// {
//
//   float4 Color_id52;                 // Offset:    0 Size:    16
//   float SizeMult_id53;               // Offset:   16 Size:     4 [unused]
//      = 0x3f800000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Globals                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 84 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_DrawFXEffect_03591c3f37504fa17b1197079bde9a1e.hlsl"
mov o0.xyzw, cb0[0].xyzw
ret 
// Approximately 2 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
};
struct GS_STREAMS 
{
    uint InstanceID_id13;
    float4 ShadingPosition_id0;
};
struct GS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
};
struct GS_INPUT 
{
    uint InstanceID_id13 : SV_InstanceID;
};
struct VS_STREAMS 
{
    uint InstanceID_id13;
    float4 PositionWS_id15;
    float Size_id56;
};
struct VS_OUTPUT 
{
    uint InstanceID_id13 : SV_InstanceID;
};
struct VS_INPUT 
{
    uint InstanceID_id13 : SV_InstanceID;
};
struct Vertex 
{
    float3 position;
    float3 normal;
};
cbuffer PerDraw 
{
    float4x4 World_id29;
    float4x4 WorldInverse_id30;
    float4x4 WorldInverseTranspose_id31;
    float4x4 WorldView_id32;
    float4x4 WorldViewInverse_id33;
    float4x4 WorldViewProjection_id34;
    float3 WorldScale_id35;
    float4 EyeMS_id36;
};
cbuffer PerView 
{
    float4x4 View_id22;
    float4x4 ViewInverse_id23;
    float4x4 Projection_id24;
    float4x4 ProjectionInverse_id25;
    float4x4 ViewProjection_id26;
    float2 ProjScreenRay_id27;
    float4 Eye_id28;
    float NearClipPlane_id45 = 1.0f;
    float FarClipPlane_id46 = 100.0f;
    float2 ZProjection_id47;
    float2 ViewSize_id48;
    float AspectRatio_id49;
};
cbuffer Globals 
{
    float4 Color_id52;
    float SizeMult_id53 = 1;
};
StructuredBuffer<Vertex> Vertices_id50;
StructuredBuffer<uint> Indices_id51;
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.ColorTarget_id2 = Color_id52;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
[maxvertexcount(3)]
void GSMain(point GS_INPUT input[1], inout TriangleStream<GS_OUTPUT> triangleStream)
{
    GS_STREAMS streams = (GS_STREAMS)0;
    streams.InstanceID_id13 = input[0].InstanceID_id13;
    uint id = streams.InstanceID_id13 * 3;

    for (int i = 0; i < 3; i++)
    {
        float4 pos = float4(Vertices_id50[Indices_id51[id + i]].position, 1);
        streams.ShadingPosition_id0 = mul(pos, WorldViewProjection_id34);

        {
            GS_OUTPUT output = (GS_OUTPUT)0;
            output.ShadingPosition_id0 = streams.ShadingPosition_id0;
            triangleStream.Append(output);
        }
    }
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.InstanceID_id13 = __input__.InstanceID_id13;
    uint id = streams.InstanceID_id13;
    id = Indices_id51[id];
    float3 P_PosSize = Vertices_id50[id].position;
    streams.PositionWS_id15 = float4(P_PosSize.xyz, 1);
    streams.Size_id56 = 0.1;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.InstanceID_id13 = streams.InstanceID_id13;
    return __output__;
}
