/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:128 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_625109945]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 240]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_49_id25 => input_49
@C    input_644_id27 => input_644
@C    input_589_id28 => input_589
@C    input_604_id29 => input_604
@C    input_582_id30 => input_582
@C    input_211_id31 => input_211
@C    input_735_id32 => input_735
@C    input_723_id33 => input_723
@C    input_452_id34 => input_452
@C    input_397_id35 => input_397
@C    input_412_id36 => input_412
@C    input_390_id37 => input_390
@C    input_208_id38 => input_208
@C    input_543_id39 => input_543
@C    input_531_id40 => input_531
@C    input_205_id41 => input_205
@C    input_55_id42 => input_55
@C    input_778_id43 => input_778
@C    input_58_id44 => input_58
@C    input_202_id45 => input_202
@C    input_61_id46 => input_61
@C    input_141_id47 => input_141
@C    input_214_id48 => input_214
@C    input_217_id49 => input_217
@C    input_223_id50 => input_223
@C    input_220_id51 => input_220
@C    input_138_id52 => input_138
@C    input_225_id53 => input_225
@C    input_199_id54 => input_199
@C    input_1232_id55 => input_1232
@C    input_228_id56 => input_228
@C    input_231_id57 => input_231
@C    input_234_id58 => input_234
@C    input_237_id59 => input_237
***************************
******  Resources    ******
***************************
@R    input_1387_id26 => input_1387 [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_625109945 => 0cdae224878a7a8ae482bb8a09328ddd
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCoreMathPCG => e529e3d6e7220073ba1b2dacab9e88b2
@S    FuseCommonNoise => 3f02e963c0659922f30af148bd892f2e
@S    FuseCommonNoiseSine => 55f799131307b926727835d76f9d9035
@S    FuseCoreMath => fdeacca3b2f02b9acb6430ed603f50b4
@S    FuseCoreMathHash => 42d92f741cb65685eaeb5283e61f2c82
@S    FuseCommonNoiseLUT => 0a545f8fb0b0163cd07ba942c45abbce
@S    FuseCommonNoiseValueNoise => 598ea3c9dd7c5fed506e079ef91b1d81
@S    FuseCommonNoiseGradientNoise => 275a1c68a04d0e8c934e4792e8de1a02
@S    FuseCommonNoiseSimplex => cff83c6dcba0e92106f65f2c730e3e35
@S    FuseCommonNoiseRandom => c9e5885d1263580889df6cfb5c437ec3
@S    FuseCommonNoiseWorley => c3806e1a0979a6fbc12110d25e4876f8
@S    FuseCoreMathMap => 07cc7a2921946bb474dce82779ab3f2b
@S    FuseCoreColor => 429d282fd7693460aaf51f7b4746568f
@S    Global => f3a73f928089a02788395f11e18f679c
***************************
*****     Stages      *****
***************************
@G    Compute => fc7e4825d670477dbd1b340664a469f2
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int input_49_id25;                 // Offset:   12 Size:     4
//   int input_644_id27;                // Offset:   16 Size:     4
//   int input_589_id28;                // Offset:   20 Size:     4
//   int input_604_id29;                // Offset:   24 Size:     4
//   int input_582_id30;                // Offset:   28 Size:     4
//   float input_211_id31;              // Offset:   32 Size:     4
//   int input_735_id32;                // Offset:   36 Size:     4
//   int input_723_id33;                // Offset:   40 Size:     4
//   int input_452_id34;                // Offset:   44 Size:     4
//   int input_397_id35;                // Offset:   48 Size:     4
//   int input_412_id36;                // Offset:   52 Size:     4
//   int input_390_id37;                // Offset:   56 Size:     4
//   float input_208_id38;              // Offset:   60 Size:     4
//   int input_543_id39;                // Offset:   64 Size:     4
//   int input_531_id40;                // Offset:   68 Size:     4
//   float3 input_205_id41;             // Offset:   80 Size:    12
//   bool input_55_id42;                // Offset:   92 Size:     4
//   int input_778_id43;                // Offset:   96 Size:     4
//   int input_58_id44;                 // Offset:  100 Size:     4
//   float input_202_id45;              // Offset:  104 Size:     4
//   float input_61_id46;               // Offset:  108 Size:     4
//   float input_141_id47;              // Offset:  112 Size:     4
//   float input_214_id48;              // Offset:  116 Size:     4
//   float3 input_217_id49;             // Offset:  128 Size:    12
//   float3 input_223_id50;             // Offset:  144 Size:    12
//   float3 input_220_id51;             // Offset:  160 Size:    12
//   float input_138_id52;              // Offset:  172 Size:     4
//   bool input_225_id53;               // Offset:  176 Size:     4
//   bool input_199_id54;               // Offset:  180 Size:     4
//   float3 input_1232_id55;            // Offset:  192 Size:    12
//   float3 input_228_id56;             // Offset:  208 Size:    12
//   float input_231_id57;              // Offset:  220 Size:     4
//   float input_234_id58;              // Offset:  224 Size:     4
//   float input_237_id59;              // Offset:  228 Size:     4
//
// }
//
// Resource bind info for input_1387_id26
// {
//
//   struct Particle
//   {
//       
//       float3 Velocity;               // Offset:    0
//       float3 Position;               // Offset:   12
//       float4 Color;                  // Offset:   24
//       float Drag;                    // Offset:   40
//       int Cycle;                     // Offset:   44
//       float Age;                     // Offset:   48
//       float LifeTime;                // Offset:   52
//       int Id;                        // Offset:   56
//       float3 AxisY;                  // Offset:   60
//       float3 AxisX;                  // Offset:   72
//       float3 AxisZ;                  // Offset:   84
//       float3 Size3;                  // Offset:   96
//
//   } $Element;                        // Offset:    0 Size:   108
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// input_1387_id26                       UAV  struct         r/w             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_uav_structured u0, 108
dcl_input vThreadID.x
dcl_temps 17
dcl_thread_group 128, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 210 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_ComputeFXEffect_4de7d1a5570a133b15dfac4598695b12.hlsl"
ilt r0.x, vThreadID.x, cb0[0].w
if_nz r0.x

#line 211
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw  // r0.x <- result_1389.Velocity.x; r0.y <- result_1389.Velocity.y; r0.z <- result_1389.Velocity.z; r0.w <- result_1389.Position.x
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(16), u0.xyxx  // r1.x <- result_1389.Position.y; r1.y <- result_1389.Position.z
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(40), u0.xyzw  // r2.x <- result_1389.Drag; r2.y <- result_1389.Cycle; r2.z <- result_1389.Age; r2.w <- result_1389.LifeTime
  ld_structured_indexable(structured_buffer, stride=108)(mixed,mixed,mixed,mixed) r3.w, vThreadID.x, l(56), u0.xxxx  // r3.w <- result_1389.Id

#line 192
  imul null, r4.x, vThreadID.x, l(0x0019660d)
  imul null, r4.yz, cb0[1].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r4.xyz, r4.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r4.x <- v.x; r4.y <- v.y; r4.z <- v.z

#line 193
  imad r5.x, r4.y, r4.z, r4.x  // r5.x <- v.x

#line 194
  imad r5.y, r4.z, r5.x, r4.y  // r5.y <- v.y

#line 195
  imad r5.z, r5.x, r5.y, r4.z  // r5.z <- v.z

#line 196
  ushr r4.xyz, r5.xyzx, l(16, 16, 16, 0)
  xor r4.xyz, r4.xyzx, r5.xyzx  // r4.x <- v.x; r4.y <- v.y; r4.z <- v.z

#line 197
  imad r4.x, r4.y, r4.z, r4.x

#line 200
  utof r4.x, r4.x

#line 219
  mad r4.x, r4.x, l(0.000000), l(-1.000000)  // r4.x <- result_673

#line 220
  mul r4.x, r4.x, l(3.141593)  // r4.x <- result_676

#line 221
  sincos r4.x, r5.x, r4.x  // r4.x <- result_679; r5.x <- result_682

#line 192
  imul null, r6.x, vThreadID.x, l(0x0019660d)
  imul null, r6.yz, cb0[1].zzwz, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r5.yzw, r6.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r5.y <- v.x; r5.z <- v.y; r5.w <- v.z

#line 193
  imad r6.x, r5.z, r5.w, r5.y  // r6.x <- v.x

#line 194
  imad r6.y, r5.w, r6.x, r5.z  // r6.y <- v.y

#line 195
  imad r6.z, r6.x, r6.y, r5.w  // r6.z <- v.z

#line 196
  ushr r5.yzw, r6.xxyz, l(0, 16, 16, 16)
  xor r5.yzw, r5.yyzw, r6.xxyz  // r5.y <- v.x; r5.z <- v.y; r5.w <- v.z

#line 197
  imad r4.z, r5.z, r5.w, r5.y  // r4.z <- v.x

#line 200
  utof r4.z, r4.z

#line 229
  mad r6.z, r4.z, l(0.000000), l(-1.000000)  // r6.z <- result_633

#line 231
  mad r4.z, -r6.z, r6.z, l(1.000000)  // r4.z <- result_693

#line 232
  sqrt r4.z, r4.z  // r4.z <- result_696

#line 234
  mov r4.y, r5.x
  mul r6.xy, r4.zzzz, r4.xyxx  // r6.x <- result_702.x; r6.y <- result_702.y

#line 239
  mul r4.xyz, r6.xyzx, cb0[2].xxxx  // r4.x <- result_720.x; r4.y <- result_720.y; r4.z <- result_720.z

#line 192
  imul null, r5.x, vThreadID.x, l(0x0019660d)
  imul null, r5.yz, cb0[2].yyzy, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r5.xyz, r5.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 193
  imad r6.x, r5.y, r5.z, r5.x  // r6.x <- v.x

#line 194
  imad r6.y, r5.z, r6.x, r5.y  // r6.y <- v.y

#line 195
  imad r6.z, r6.x, r6.y, r5.z  // r6.z <- v.z

#line 196
  ushr r5.xyz, r6.xyzx, l(16, 16, 16, 0)
  xor r5.xyz, r5.xyzx, r6.xyzx  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 197
  imad r4.w, r5.y, r5.z, r5.x  // r4.w <- v.x

#line 200
  utof r4.w, r4.w
  mul r4.w, r4.w, l(0.000000)  // r4.w <- <pcg3d_id85 return value>.x

#line 244
  log r4.w, r4.w
  mul r4.w, r4.w, l(0.333333)
  exp r4.w, r4.w  // r4.w <- result_761

#line 246
  mul r4.xyz, r4.wwww, r4.xyzx  // r4.x <- result_767.x; r4.y <- result_767.y; r4.z <- result_767.z

#line 192
  imul null, r5.x, vThreadID.x, l(0x0019660d)
  imul null, r5.y, cb0[2].w, l(0x0019660d)
  imul null, r5.z, cb0[3].x, l(0x0019660d)
  iadd r5.xyz, r5.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 193
  imad r6.x, r5.y, r5.z, r5.x  // r6.x <- v.x

#line 194
  imad r6.y, r5.z, r6.x, r5.y  // r6.y <- v.y

#line 195
  imad r6.z, r6.x, r6.y, r5.z  // r6.z <- v.z

#line 196
  ushr r5.xyz, r6.xyzx, l(16, 16, 16, 0)
  xor r5.xyz, r5.xyzx, r6.xyzx  // r5.x <- v.x; r5.y <- v.y; r5.z <- v.z

#line 197
  imad r4.w, r5.y, r5.z, r5.x  // r4.w <- v.x

#line 200
  utof r4.w, r4.w

#line 254
  mad r4.w, r4.w, l(0.000000), l(-1.000000)  // r4.w <- result_481

#line 255
  mul r4.w, r4.w, l(3.141593)  // r4.w <- result_484

#line 256
  sincos r5.x, r6.x, r4.w  // r5.x <- result_487; r6.x <- result_490

#line 192
  imul null, r7.x, vThreadID.x, l(0x0019660d)
  imul null, r7.yz, cb0[3].yyzy, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r6.yzw, r7.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r6.y <- v.x; r6.z <- v.y; r6.w <- v.z

#line 193
  imad r7.x, r6.z, r6.w, r6.y  // r7.x <- v.x

#line 194
  imad r7.y, r6.w, r7.x, r6.z  // r7.y <- v.y

#line 195
  imad r7.z, r7.x, r7.y, r6.w  // r7.z <- v.z

#line 196
  ushr r6.yzw, r7.xxyz, l(0, 16, 16, 16)
  xor r6.yzw, r6.yyzw, r7.xxyz  // r6.y <- v.x; r6.z <- v.y; r6.w <- v.z

#line 197
  imad r4.w, r6.z, r6.w, r6.y  // r4.w <- v.x

#line 200
  utof r4.w, r4.w

#line 264
  mad r7.z, r4.w, l(0.000000), l(-1.000000)  // r7.z <- result_441

#line 266
  mad r4.w, -r7.z, r7.z, l(1.000000)  // r4.w <- result_501

#line 267
  sqrt r4.w, r4.w  // r4.w <- result_504

#line 269
  mov r5.y, r6.x
  mul r7.xy, r4.wwww, r5.xyxx  // r7.x <- result_510.x; r7.y <- result_510.y

#line 274
  mul r5.xyz, r7.xyzx, cb0[3].wwww  // r5.x <- result_528.x; r5.y <- result_528.y; r5.z <- result_528.z

#line 192
  imul null, r6.x, vThreadID.x, l(0x0019660d)
  imul null, r6.yz, cb0[4].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r6.xyz, r6.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 193
  imad r7.x, r6.y, r6.z, r6.x  // r7.x <- v.x

#line 194
  imad r7.y, r6.z, r7.x, r6.y  // r7.y <- v.y

#line 195
  imad r7.z, r7.x, r7.y, r6.z  // r7.z <- v.z

#line 196
  ushr r6.xyz, r7.xyzx, l(16, 16, 16, 0)
  xor r6.xyz, r6.xyzx, r7.xyzx  // r6.x <- v.x; r6.y <- v.y; r6.z <- v.z

#line 197
  imad r4.w, r6.y, r6.z, r6.x  // r4.w <- v.x

#line 200
  utof r4.w, r4.w
  mul r4.w, r4.w, l(0.000000)  // r4.w <- <pcg3d_id85 return value>.x

#line 279
  log r4.w, r4.w
  mul r4.w, r4.w, l(0.333333)
  exp r4.w, r4.w  // r4.w <- result_569

#line 282
  mad r5.xyz, r5.xyzx, r4.wwww, cb0[5].xyzx  // r5.x <- result_579.x; r5.y <- result_579.y; r5.z <- result_579.z

#line 286
  iadd r6.y, r2.y, l(1)  // r6.y <- result_931

#line 192
  imul null, r7.x, vThreadID.x, l(0x0019660d)
  imul null, r7.yz, cb0[6].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r7.xyz, r7.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r7.x <- v.x; r7.y <- v.y; r7.z <- v.z

#line 193
  imad r8.x, r7.y, r7.z, r7.x  // r8.x <- v.x

#line 194
  imad r8.y, r7.z, r8.x, r7.y  // r8.y <- v.y

#line 195
  imad r8.z, r8.x, r8.y, r7.z  // r8.z <- v.z

#line 196
  ushr r7.xyz, r8.xyzx, l(16, 16, 16, 0)
  xor r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- v.x; r7.y <- v.y; r7.z <- v.z

#line 197
  imad r4.w, r7.y, r7.z, r7.x  // r4.w <- v.x

#line 200
  utof r4.w, r4.w
  mul r4.w, r4.w, l(0.000000)  // r4.w <- <pcg3d_id85 return value>.x

#line 295
  lt r4.w, r4.w, cb0[6].z  // r4.w <- result_951

#line 296
  ieq r7.x, r2.y, l(0)  // r7.x <- result_978

#line 297
  lt r7.y, r2.z, l(0.000000)  // r7.y <- result_982

#line 298
  or r7.x, r7.y, r7.x  // r7.x <- result_984

#line 301
  ine r7.y, cb0[5].w, l(0)
  and r4.w, r4.w, r7.y
  and r4.w, r7.x, r4.w  // r4.w <- result_990

#line 312
  mov r6.xz, l(1.000000,0,3.000000,0)
  mov r6.w, vThreadID.x
  mov r3.xyz, r2.xywx
  movc r3.xyzw, r4.wwww, r6.xyzw, r3.xyzw  // r3.x <- result_1421; r3.y <- result_1429; r3.z <- result_1445; r3.w <- result_1453
  movc r0.xyz, r4.wwww, r4.xyzx, r0.xyzx  // r0.x <- result_1397.x; r0.y <- result_1397.y; r0.z <- result_1397.z
  mov r5.w, l(0)
  mov r1.z, r0.w
  mov r1.w, r2.z
  movc r1.xyzw, r4.wwww, r5.xyzw, r1.zxyw  // r1.x <- result_1405.x; r1.y <- result_1405.y; r1.z <- result_1405.z; r1.w <- result_1437

#line 316
  mul r2.xyz, r1.xyzx, cb0[7].xxxx  // r2.x <- result_1015.x; r2.y <- result_1015.y; r2.z <- result_1015.z

#line 325
  mul r2.xyz, r2.xyzx, cb0[8].xyzx  // r2.x <- result_1122.x; r2.y <- result_1122.y; r2.z <- result_1122.z
  mov r2.w, cb0[7].y  // r2.w <- result_1122.w

#line 160
  add r4.xyzw, r2.xyzw, l(17.000000, 17.000000, 17.000000, 17.000000)  // r4.x <- p2.x; r4.y <- p2.y; r4.z <- p2.z; r4.w <- p2.w

#line 161
  add r5.xyzw, r2.xyzw, l(-43.700001, -43.700001, -43.700001, -43.700001)  // r5.x <- p3.x; r5.y <- p3.y; r5.z <- p3.z; r5.w <- p3.w

#line 119
  dp4 r0.w, r2.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r6.xyzw, r0.wwww, r2.xyzw
  round_ni r6.xyzw, r6.xyzw  // r6.x <- i.x; r6.y <- i.y; r6.z <- i.z; r6.w <- i.w

#line 120
  add r2.xyzw, r2.xyzw, -r6.xyzw
  dp4 r0.w, r6.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r2.xyzw, r0.wwww, r2.xyzw  // r2.x <- x0.x; r2.y <- x0.y; r2.z <- x0.z; r2.w <- x0.w

#line 122
  ge r7.xyz, r2.xxxx, r2.yzwy
  and r8.xyz, r7.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r8.x <- isX.x; r8.y <- isX.y; r8.z <- isX.z

#line 123
  ge r9.xyz, r2.yyzy, r2.zwwz
  and r10.xyz, r9.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r10.x <- isYZ.x; r10.y <- isYZ.y; r10.z <- isYZ.z

#line 124
  add r0.w, r8.y, r8.x
  add r8.x, r8.z, r0.w  // r8.x <- i0.x

#line 125
  movc r7.xyz, r7.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r7.x <- i0.y; r7.y <- i0.z; r7.z <- i0.w

#line 126
  add r0.w, r10.y, r10.x
  add r8.y, r0.w, r7.x  // r8.y <- i0.y

#line 129
  movc r9.xyz, r9.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 127
  add r7.xy, r7.yzyy, r9.xyxx
  mov r10.w, l(1.000000)
  add r7.xz, r7.yyxy, r10.wwzw  // r7.x <- i0.w

#line 128
  add r8.z, r7.z, l(1.000000)  // r8.z <- i0.z

#line 129
  add r7.w, r9.z, r7.x
  add r8.w, r7.w, l(1.000000)  // r8.w <- i0.w

#line 130
  min r9.xyzw, r8.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r9.x <- i3.y; r9.y <- i3.z; r9.z <- i3.x; r9.w <- i3.w

#line 131
  mov r7.xy, r8.xyxx
  add_sat r8.xyzw, r7.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r8.x <- i2.x; r8.y <- i2.y; r8.z <- i2.z; r8.w <- i2.w

#line 132
  add r7.xyzw, r7.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r7.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r7.x <- i1.x; r7.y <- i1.y; r7.z <- i1.z; r7.w <- i1.w

#line 133
  add r10.xyzw, r2.xyzw, -r7.xyzw
  add r10.xyzw, r10.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r10.x <- x1.x; r10.y <- x1.y; r10.z <- x1.z; r10.w <- x1.w

#line 134
  add r11.xyzw, r2.xyzw, -r8.xyzw
  add r11.xyzw, r11.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r11.x <- x2.x; r11.y <- x2.y; r11.z <- x2.z; r11.w <- x2.w

#line 135
  add r12.xyzw, r2.xyzw, -r9.zxyw
  add r12.xyzw, r12.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r12.x <- x3.x; r12.y <- x3.y; r12.z <- x3.z; r12.w <- x3.w

#line 136
  add r13.xyzw, r2.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)  // r13.x <- x4.x; r13.y <- x4.y; r13.z <- x4.z; r13.w <- x4.w

#line 80
  mul r14.xyzw, r6.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r6.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r6.xyzw  // r6.x <- <mod289_id19 return value>.x; r6.y <- <mod289_id19 return value>.y; r6.z <- <mod289_id19 return value>.z; r6.w <- <mod289_id19 return value>.w

#line 101
  mul r0.w, r6.w, r6.w
  mad r0.w, r0.w, l(34.000000), r6.w

#line 84
  mul r14.x, r0.w, l(0.003460)
  round_ni r14.x, r14.x
  mad r0.w, -r14.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.z, r0.w

#line 101
  mul r14.x, r0.w, r0.w
  mad r0.w, r14.x, l(34.000000), r0.w

#line 84
  mul r14.x, r0.w, l(0.003460)
  round_ni r14.x, r14.x
  mad r0.w, -r14.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.y, r0.w

#line 101
  mul r14.x, r0.w, r0.w
  mad r0.w, r14.x, l(34.000000), r0.w

#line 84
  mul r14.x, r0.w, l(0.003460)
  round_ni r14.x, r14.x
  mad r0.w, -r14.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.x, r0.w

#line 101
  mul r14.x, r0.w, r0.w
  mad r0.w, r14.x, l(34.000000), r0.w

#line 84
  mul r14.x, r0.w, l(0.003460)
  round_ni r14.x, r14.x
  mad r0.w, -r14.x, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 139
  mov r14.x, r7.w
  mov r14.y, r8.w
  mov r14.z, r9.w
  mov r14.w, l(1.000000)
  add r14.xyzw, r6.wwww, r14.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r14.xyzw, r6.zzzz, r14.xyzw
  mov r15.x, r7.z
  mov r15.y, r8.z
  mov r15.z, r9.y
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r14.xyzw, r6.yyyy, r14.xyzw
  mov r15.x, r7.y
  mov r15.y, r8.y
  mov r15.z, r9.x
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r6.xyzw, r6.xxxx, r14.xyzw
  mov r9.x, r7.x
  mov r9.y, r8.x
  mov r9.w, l(1.000000)
  add r6.xyzw, r6.xyzw, r9.xyzw

#line 97
  mul r7.xyzw, r6.xyzw, r6.xyzw
  mad r6.xyzw, r7.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r6.xyzw

#line 80
  mul r7.xyzw, r6.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r7.xyzw, r7.xyzw
  mad r6.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r6.xyzw  // r6.x <- <mod289_id19 return value>.x; r6.y <- <mod289_id19 return value>.y; r6.z <- <mod289_id19 return value>.z; r6.w <- <mod289_id19 return value>.w

#line 90
  mul r7.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r8.w, -r0.w, l(1.500000)  // r8.w <- p.w

#line 92
  lt r9.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r8.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r9.xyz, r0.wwww, r9.xyzx
  itof r9.xyz, r9.xyzx
  add r8.xyz, r7.xyzx, -r9.xyzx  // r8.x <- p.x; r8.y <- p.y; r8.z <- p.z

#line 90
  mul r7.xyz, r6.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r9.w, -r0.w, l(1.500000)  // r9.w <- p.w

#line 92
  lt r14.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r9.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r14.xyz, r0.wwww, r14.xyzx
  itof r14.xyz, r14.xyzx
  add r9.xyz, r7.xyzx, -r14.xyzx  // r9.x <- p.x; r9.y <- p.y; r9.z <- p.z

#line 90
  mul r7.xyz, r6.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r14.w, -r0.w, l(1.500000)  // r14.w <- p.w

#line 92
  lt r15.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r14.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r14.xyz, r7.xyzx, -r15.xyzx  // r14.x <- p.x; r14.y <- p.y; r14.z <- p.z

#line 90
  mul r6.xyz, r6.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r7.w, -r0.w, l(1.500000)  // r7.w <- p.w

#line 92
  lt r15.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r7.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r7.xyz, r6.xyzx, -r15.xyzx  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 90
  mul r6.xyz, r6.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r15.w, -r0.w, l(1.500000)  // r15.w <- p.w

#line 92
  lt r16.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r15.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r15.xyz, r6.xyzx, -r16.xyzx  // r15.x <- p.x; r15.y <- p.y; r15.z <- p.z

#line 146
  dp4 r0.w, r8.xyzw, r8.xyzw
  dp4 r6.x, r9.xyzw, r9.xyzw
  dp4 r6.y, r14.xyzw, r14.xyzw
  dp4 r6.z, r7.xyzw, r7.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r6.x, r6.x  // r6.x <- norm.y
  rsq r6.y, r6.y  // r6.y <- norm.z
  rsq r6.z, r6.z  // r6.z <- norm.w

#line 147
  mul r8.xyzw, r0.wwww, r8.xyzw  // r8.x <- p0.x; r8.y <- p0.y; r8.z <- p0.z; r8.w <- p0.w

#line 148
  mul r9.xyzw, r6.xxxx, r9.xyzw  // r9.x <- p1.x; r9.y <- p1.y; r9.z <- p1.z; r9.w <- p1.w

#line 149
  mul r14.xyzw, r6.yyyy, r14.xyzw  // r14.x <- p2.x; r14.y <- p2.y; r14.z <- p2.z; r14.w <- p2.w

#line 150
  mul r6.xyzw, r6.zzzz, r7.xyzw  // r6.x <- p3.x; r6.y <- p3.y; r6.z <- p3.z; r6.w <- p3.w

#line 151
  dp4 r0.w, r15.xyzw, r15.xyzw
  rsq r0.w, r0.w
  mul r7.xyzw, r0.wwww, r15.xyzw  // r7.x <- p4.x; r7.y <- p4.y; r7.z <- p4.z; r7.w <- p4.w

#line 152
  dp4 r15.x, r2.xyzw, r2.xyzw
  dp4 r15.y, r10.xyzw, r10.xyzw
  dp4 r15.z, r11.xyzw, r11.xyzw
  add r15.xyz, -r15.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r15.xyz, r15.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r15.x <- m0.x; r15.y <- m0.y; r15.z <- m0.z

#line 153
  dp4 r16.x, r12.xyzw, r12.xyzw
  dp4 r16.y, r13.xyzw, r13.xyzw
  add r16.xy, -r16.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r16.xy, r16.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r16.x <- m1.x; r16.y <- m1.y

#line 154
  mul r15.xyz, r15.xyzx, r15.xyzx

#line 155
  mul r16.xy, r16.xyxx, r16.xyxx

#line 156
  mul r15.xyz, r15.xyzx, r15.xyzx
  dp4 r2.x, r8.xyzw, r2.xyzw
  dp4 r2.y, r9.xyzw, r10.xyzw
  dp4 r2.z, r14.xyzw, r11.xyzw
  dp3 r0.w, r15.xyzx, r2.xyzx
  mul r2.xy, r16.xyxx, r16.xyxx
  dp4 r6.x, r6.xyzw, r12.xyzw
  dp4 r6.y, r7.xyzw, r13.xyzw
  dp2 r2.x, r2.xyxx, r6.xyxx
  add r0.w, r0.w, r2.x
  mul r2.x, r0.w, l(49.000000)  // r2.x <- <simplexNoise_id63 return value>

#line 119
  dp4 r0.w, r4.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r6.xyzw, r0.wwww, r4.xyzw
  round_ni r6.xyzw, r6.xyzw  // r6.x <- i.x; r6.y <- i.y; r6.z <- i.z; r6.w <- i.w

#line 120
  add r4.xyzw, r4.xyzw, -r6.xyzw
  dp4 r0.w, r6.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r4.xyzw, r0.wwww, r4.xyzw  // r4.x <- x0.x; r4.y <- x0.y; r4.z <- x0.z; r4.w <- x0.w

#line 122
  ge r7.xyz, r4.xxxx, r4.yzwy
  and r8.xyz, r7.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r8.x <- isX.x; r8.y <- isX.y; r8.z <- isX.z

#line 123
  ge r9.xyz, r4.yyzy, r4.zwwz
  and r10.xyz, r9.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r10.x <- isYZ.x; r10.y <- isYZ.y; r10.z <- isYZ.z

#line 124
  add r0.w, r8.y, r8.x
  add r8.x, r8.z, r0.w  // r8.x <- i0.x

#line 125
  movc r7.xyz, r7.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r7.x <- i0.y; r7.y <- i0.z; r7.z <- i0.w

#line 126
  add r0.w, r10.y, r10.x
  add r8.y, r0.w, r7.x  // r8.y <- i0.y

#line 129
  movc r9.xyz, r9.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 127
  add r7.xy, r7.yzyy, r9.xyxx
  mov r10.w, l(1.000000)
  add r7.xz, r7.yyxy, r10.wwzw  // r7.x <- i0.w

#line 128
  add r8.z, r7.z, l(1.000000)  // r8.z <- i0.z

#line 129
  add r7.w, r9.z, r7.x
  add r8.w, r7.w, l(1.000000)  // r8.w <- i0.w

#line 130
  min r9.xyzw, r8.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r9.x <- i3.y; r9.y <- i3.z; r9.z <- i3.x; r9.w <- i3.w

#line 131
  mov r7.xy, r8.xyxx
  add_sat r8.xyzw, r7.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r8.x <- i2.x; r8.y <- i2.y; r8.z <- i2.z; r8.w <- i2.w

#line 132
  add r7.xyzw, r7.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r7.xyzw, r7.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r7.x <- i1.x; r7.y <- i1.y; r7.z <- i1.z; r7.w <- i1.w

#line 133
  add r10.xyzw, r4.xyzw, -r7.xyzw
  add r10.xyzw, r10.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r10.x <- x1.x; r10.y <- x1.y; r10.z <- x1.z; r10.w <- x1.w

#line 134
  add r11.xyzw, r4.xyzw, -r8.xyzw
  add r11.xyzw, r11.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r11.x <- x2.x; r11.y <- x2.y; r11.z <- x2.z; r11.w <- x2.w

#line 135
  add r12.xyzw, r4.xyzw, -r9.zxyw
  add r12.xyzw, r12.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r12.x <- x3.x; r12.y <- x3.y; r12.z <- x3.z; r12.w <- x3.w

#line 136
  add r13.xyzw, r4.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)

#line 80
  mul r14.xyzw, r6.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r6.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r6.xyzw  // r6.x <- <mod289_id19 return value>.x; r6.y <- <mod289_id19 return value>.y; r6.z <- <mod289_id19 return value>.z; r6.w <- <mod289_id19 return value>.w

#line 101
  mul r0.w, r6.w, r6.w
  mad r0.w, r0.w, l(34.000000), r6.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.z, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.y, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r6.x, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 139
  mov r14.x, r7.w
  mov r14.y, r8.w
  mov r14.z, r9.w
  mov r14.w, l(1.000000)
  add r14.xyzw, r6.wwww, r14.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r14.xyzw, r6.zzzz, r14.xyzw
  mov r15.x, r7.z
  mov r15.y, r8.z
  mov r15.z, r9.y
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r14.xyzw, r6.yyyy, r14.xyzw
  mov r15.x, r7.y
  mov r15.y, r8.y
  mov r15.z, r9.x
  mov r15.w, l(1.000000)
  add r14.xyzw, r14.xyzw, r15.xyzw

#line 97
  mul r15.xyzw, r14.xyzw, r14.xyzw
  mad r14.xyzw, r15.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r14.xyzw

#line 80
  mul r15.xyzw, r14.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r15.xyzw, r15.xyzw
  mad r14.xyzw, -r15.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r14.xyzw  // r14.x <- <mod289_id19 return value>.x; r14.y <- <mod289_id19 return value>.y; r14.z <- <mod289_id19 return value>.z; r14.w <- <mod289_id19 return value>.w

#line 139
  add r6.xyzw, r6.xxxx, r14.xyzw
  mov r9.x, r7.x
  mov r9.y, r8.x
  mov r9.w, l(1.000000)
  add r6.xyzw, r6.xyzw, r9.xyzw

#line 97
  mul r7.xyzw, r6.xyzw, r6.xyzw
  mad r6.xyzw, r7.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r6.xyzw

#line 80
  mul r7.xyzw, r6.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r7.xyzw, r7.xyzw
  mad r6.xyzw, -r7.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r6.xyzw  // r6.x <- <mod289_id19 return value>.x; r6.y <- <mod289_id19 return value>.y; r6.z <- <mod289_id19 return value>.z; r6.w <- <mod289_id19 return value>.w

#line 90
  mul r7.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r8.w, -r0.w, l(1.500000)  // r8.w <- p.w

#line 92
  lt r9.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r8.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r9.xyz, r0.wwww, r9.xyzx
  itof r9.xyz, r9.xyzx
  add r8.xyz, r7.xyzx, -r9.xyzx  // r8.x <- p.x; r8.y <- p.y; r8.z <- p.z

#line 90
  mul r7.xyz, r6.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r9.w, -r0.w, l(1.500000)  // r9.w <- p.w

#line 92
  lt r14.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r9.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r14.xyz, r0.wwww, r14.xyzx
  itof r14.xyz, r14.xyzx
  add r9.xyz, r7.xyzx, -r14.xyzx  // r9.x <- p.x; r9.y <- p.y; r9.z <- p.z

#line 90
  mul r7.xyz, r6.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r7.xyz, r7.xyzx
  mul r7.xyz, r7.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r7.xyz, r7.xyzx
  mad r7.xyz, r7.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 91
  dp3 r0.w, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r14.w, -r0.w, l(1.500000)  // r14.w <- p.w

#line 92
  lt r15.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r14.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r14.xyz, r7.xyzx, -r15.xyzx  // r14.x <- p.x; r14.y <- p.y; r14.z <- p.z

#line 90
  mul r6.xyz, r6.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r7.w, -r0.w, l(1.500000)  // r7.w <- p.w

#line 92
  lt r15.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r7.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r7.xyz, r6.xyzx, -r15.xyzx  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 90
  mul r6.xyz, r6.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r15.w, -r0.w, l(1.500000)  // r15.w <- p.w

#line 92
  lt r16.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r15.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r16.xyz, r0.wwww, r16.xyzx
  itof r16.xyz, r16.xyzx
  add r15.xyz, r6.xyzx, -r16.xyzx  // r15.x <- p.x; r15.y <- p.y; r15.z <- p.z

#line 146
  dp4 r0.w, r8.xyzw, r8.xyzw
  dp4 r2.w, r9.xyzw, r9.xyzw
  dp4 r6.x, r14.xyzw, r14.xyzw
  dp4 r6.y, r7.xyzw, r7.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r2.w, r2.w  // r2.w <- norm.y
  rsq r6.x, r6.x  // r6.x <- norm.z
  rsq r6.y, r6.y  // r6.y <- norm.w

#line 147
  mul r8.xyzw, r0.wwww, r8.xyzw  // r8.x <- p0.x; r8.y <- p0.y; r8.z <- p0.z; r8.w <- p0.w

#line 148
  mul r9.xyzw, r2.wwww, r9.xyzw  // r9.x <- p1.x; r9.y <- p1.y; r9.z <- p1.z; r9.w <- p1.w

#line 149
  mul r14.xyzw, r6.xxxx, r14.xyzw  // r14.x <- p2.x; r14.y <- p2.y; r14.z <- p2.z; r14.w <- p2.w

#line 150
  mul r6.xyzw, r6.yyyy, r7.xyzw  // r6.x <- p3.x; r6.y <- p3.y; r6.z <- p3.z; r6.w <- p3.w

#line 151
  dp4 r0.w, r15.xyzw, r15.xyzw
  rsq r0.w, r0.w
  mul r7.xyzw, r0.wwww, r15.xyzw  // r7.x <- p4.x; r7.y <- p4.y; r7.z <- p4.z; r7.w <- p4.w

#line 152
  dp4 r15.x, r4.xyzw, r4.xyzw
  dp4 r15.y, r10.xyzw, r10.xyzw
  dp4 r15.z, r11.xyzw, r11.xyzw
  add r15.xyz, -r15.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r15.xyz, r15.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r15.x <- m0.x; r15.y <- m0.y; r15.z <- m0.z

#line 153
  dp4 r16.x, r12.xyzw, r12.xyzw
  dp4 r16.y, r13.xyzw, r13.xyzw
  add r16.xy, -r16.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r16.xy, r16.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r16.x <- m1.x; r16.y <- m1.y

#line 154
  mul r15.xyz, r15.xyzx, r15.xyzx

#line 155
  mul r16.xy, r16.xyxx, r16.xyxx

#line 156
  mul r15.xyz, r15.xyzx, r15.xyzx
  dp4 r4.x, r8.xyzw, r4.xyzw
  dp4 r4.y, r9.xyzw, r10.xyzw
  dp4 r4.z, r14.xyzw, r11.xyzw
  dp3 r0.w, r15.xyzx, r4.xyzx
  mul r4.xy, r16.xyxx, r16.xyxx
  dp4 r6.x, r6.xyzw, r12.xyzw
  dp4 r6.y, r7.xyzw, r13.xyzw
  dp2 r2.w, r4.xyxx, r6.xyxx
  add r0.w, r0.w, r2.w
  mul r2.y, r0.w, l(49.000000)  // r2.y <- <simplexNoise_id63 return value>

#line 119
  dp4 r0.w, r5.xyzw, l(0.309017, 0.309017, 0.309017, 0.309017)
  add r4.xyzw, r0.wwww, r5.xyzw
  round_ni r4.xyzw, r4.xyzw  // r4.x <- i.x; r4.y <- i.y; r4.z <- i.z; r4.w <- i.w

#line 120
  add r5.xyzw, -r4.xyzw, r5.xyzw
  dp4 r0.w, r4.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)
  add r5.xyzw, r0.wwww, r5.xyzw  // r5.x <- x0.x; r5.y <- x0.y; r5.z <- x0.z; r5.w <- x0.w

#line 122
  ge r6.xyz, r5.xxxx, r5.yzwy
  and r7.xyz, r6.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r7.x <- isX.x; r7.y <- isX.y; r7.z <- isX.z

#line 123
  ge r8.xyz, r5.yyzy, r5.zwwz
  and r9.xyz, r8.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)  // r9.x <- isYZ.x; r9.y <- isYZ.y; r9.z <- isYZ.z

#line 124
  add r0.w, r7.y, r7.x
  add r7.x, r7.z, r0.w  // r7.x <- i0.x

#line 125
  movc r6.xyz, r6.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)  // r6.x <- i0.y; r6.y <- i0.z; r6.z <- i0.w

#line 126
  add r0.w, r9.y, r9.x
  add r7.y, r0.w, r6.x  // r7.y <- i0.y

#line 129
  movc r8.xyz, r8.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)

#line 127
  add r6.xy, r6.yzyy, r8.xyxx
  mov r9.w, l(1.000000)
  add r6.xz, r6.yyxy, r9.wwzw  // r6.x <- i0.w

#line 128
  add r7.z, r6.z, l(1.000000)  // r7.z <- i0.z

#line 129
  add r6.w, r8.z, r6.x
  add r7.w, r6.w, l(1.000000)  // r7.w <- i0.w

#line 130
  min r8.xyzw, r7.yzxw, l(1.000000, 1.000000, 1.000000, 1.000000)  // r8.x <- i3.y; r8.y <- i3.z; r8.z <- i3.x; r8.w <- i3.w

#line 131
  mov r6.xy, r7.xyxx
  add_sat r7.xyzw, r6.xyzw, l(-1.000000, -1.000000, 0.000000, 0.000000)  // r7.x <- i2.x; r7.y <- i2.y; r7.z <- i2.z; r7.w <- i2.w

#line 132
  add r6.xyzw, r6.xyzw, l(-2.000000, -2.000000, -1.000000, -1.000000)
  max r6.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)  // r6.x <- i1.x; r6.y <- i1.y; r6.z <- i1.z; r6.w <- i1.w

#line 133
  add r9.xyzw, r5.xyzw, -r6.xyzw
  add r9.xyzw, r9.xyzw, l(0.138197, 0.138197, 0.138197, 0.138197)  // r9.x <- x1.x; r9.y <- x1.y; r9.z <- x1.z; r9.w <- x1.w

#line 134
  add r10.xyzw, r5.xyzw, -r7.xyzw
  add r10.xyzw, r10.xyzw, l(0.276393, 0.276393, 0.276393, 0.276393)  // r10.x <- x2.x; r10.y <- x2.y; r10.z <- x2.z; r10.w <- x2.w

#line 135
  add r11.xyzw, r5.xyzw, -r8.zxyw
  add r11.xyzw, r11.xyzw, l(0.414590, 0.414590, 0.414590, 0.414590)  // r11.x <- x3.x; r11.y <- x3.y; r11.z <- x3.z; r11.w <- x3.w

#line 136
  add r12.xyzw, r5.xyzw, l(-0.447214, -0.447214, -0.447214, -0.447214)  // r12.x <- x4.x; r12.y <- x4.y; r12.z <- x4.z; r12.w <- x4.w

#line 80
  mul r13.xyzw, r4.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r13.xyzw, r13.xyzw
  mad r4.xyzw, -r13.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r4.xyzw  // r4.x <- <mod289_id19 return value>.x; r4.y <- <mod289_id19 return value>.y; r4.z <- <mod289_id19 return value>.z; r4.w <- <mod289_id19 return value>.w

#line 101
  mul r0.w, r4.w, r4.w
  mad r0.w, r0.w, l(34.000000), r4.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r4.z, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r4.y, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 138
  add r0.w, r4.x, r0.w

#line 101
  mul r2.w, r0.w, r0.w
  mad r0.w, r2.w, l(34.000000), r0.w

#line 84
  mul r2.w, r0.w, l(0.003460)
  round_ni r2.w, r2.w
  mad r0.w, -r2.w, l(289.000000), r0.w  // r0.w <- <mod289_id17 return value>

#line 139
  mov r13.x, r6.w
  mov r13.y, r7.w
  mov r13.z, r8.w
  mov r13.w, l(1.000000)
  add r13.xyzw, r4.wwww, r13.xyzw

#line 97
  mul r14.xyzw, r13.xyzw, r13.xyzw
  mad r13.xyzw, r14.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r13.xyzw

#line 80
  mul r14.xyzw, r13.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r13.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r13.xyzw  // r13.x <- <mod289_id19 return value>.x; r13.y <- <mod289_id19 return value>.y; r13.z <- <mod289_id19 return value>.z; r13.w <- <mod289_id19 return value>.w

#line 139
  add r13.xyzw, r4.zzzz, r13.xyzw
  mov r14.x, r6.z
  mov r14.y, r7.z
  mov r14.z, r8.y
  mov r14.w, l(1.000000)
  add r13.xyzw, r13.xyzw, r14.xyzw

#line 97
  mul r14.xyzw, r13.xyzw, r13.xyzw
  mad r13.xyzw, r14.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r13.xyzw

#line 80
  mul r14.xyzw, r13.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r13.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r13.xyzw  // r13.x <- <mod289_id19 return value>.x; r13.y <- <mod289_id19 return value>.y; r13.z <- <mod289_id19 return value>.z; r13.w <- <mod289_id19 return value>.w

#line 139
  add r13.xyzw, r4.yyyy, r13.xyzw
  mov r14.x, r6.y
  mov r14.y, r7.y
  mov r14.z, r8.x
  mov r14.w, l(1.000000)
  add r13.xyzw, r13.xyzw, r14.xyzw

#line 97
  mul r14.xyzw, r13.xyzw, r13.xyzw
  mad r13.xyzw, r14.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r13.xyzw

#line 80
  mul r14.xyzw, r13.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r14.xyzw, r14.xyzw
  mad r13.xyzw, -r14.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r13.xyzw  // r13.x <- <mod289_id19 return value>.x; r13.y <- <mod289_id19 return value>.y; r13.z <- <mod289_id19 return value>.z; r13.w <- <mod289_id19 return value>.w

#line 139
  add r4.xyzw, r4.xxxx, r13.xyzw
  mov r8.x, r6.x
  mov r8.y, r7.x
  mov r8.w, l(1.000000)
  add r4.xyzw, r4.xyzw, r8.xyzw

#line 97
  mul r6.xyzw, r4.xyzw, r4.xyzw
  mad r4.xyzw, r6.xyzw, l(34.000000, 34.000000, 34.000000, 34.000000), r4.xyzw

#line 80
  mul r6.xyzw, r4.xyzw, l(0.003460, 0.003460, 0.003460, 0.003460)
  round_ni r6.xyzw, r6.xyzw
  mad r4.xyzw, -r6.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000), r4.xyzw  // r4.x <- <mod289_id19 return value>.x; r4.y <- <mod289_id19 return value>.y; r4.z <- <mod289_id19 return value>.z; r4.w <- <mod289_id19 return value>.w

#line 90
  mul r6.xyz, r0.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r7.w, -r0.w, l(1.500000)  // r7.w <- p.w

#line 92
  lt r8.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r7.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r8.xyz, r0.wwww, r8.xyzx
  itof r8.xyz, r8.xyzx
  add r7.xyz, r6.xyzx, -r8.xyzx  // r7.x <- p.x; r7.y <- p.y; r7.z <- p.z

#line 90
  mul r6.xyz, r4.xxxx, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r8.w, -r0.w, l(1.500000)  // r8.w <- p.w

#line 92
  lt r13.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r8.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r13.xyz, r0.wwww, r13.xyzx
  itof r13.xyz, r13.xyzx
  add r8.xyz, r6.xyzx, -r13.xyzx  // r8.x <- p.x; r8.y <- p.y; r8.z <- p.z

#line 90
  mul r6.xyz, r4.yyyy, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r6.xyz, r6.xyzx
  mul r6.xyz, r6.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r6.xyz, r6.xyzx
  mad r6.xyz, r6.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 91
  dp3 r0.w, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r13.w, -r0.w, l(1.500000)  // r13.w <- p.w

#line 92
  lt r14.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r13.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r14.xyz, r0.wwww, r14.xyzx
  itof r14.xyz, r14.xyzx
  add r13.xyz, r6.xyzx, -r14.xyzx  // r13.x <- p.x; r13.y <- p.y; r13.z <- p.z

#line 90
  mul r4.xyz, r4.zzzz, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r4.xyz, r4.xyzx
  mul r4.xyz, r4.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r4.xyz, r4.xyzx
  mad r4.xyz, r4.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r4.x <- p.x; r4.y <- p.y; r4.z <- p.z

#line 91
  dp3 r0.w, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r6.w, -r0.w, l(1.500000)  // r6.w <- p.w

#line 92
  lt r14.xyz, r4.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r6.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r14.xyz, r0.wwww, r14.xyzx
  itof r14.xyz, r14.xyzx
  add r6.xyz, r4.xyzx, -r14.xyzx  // r6.x <- p.x; r6.y <- p.y; r6.z <- p.z

#line 90
  mul r4.xyz, r4.wwww, l(0.003401, 0.020408, 0.142857, 0.000000)
  frc r4.xyz, r4.xyzx
  mul r4.xyz, r4.xyzx, l(7.000000, 7.000000, 7.000000, 0.000000)
  round_ni r4.xyz, r4.xyzx
  mad r4.xyz, r4.xyzx, l(0.142857, 0.142857, 0.142857, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)  // r4.x <- p.x; r4.y <- p.y; r4.z <- p.z

#line 91
  dp3 r0.w, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  add r14.w, -r0.w, l(1.500000)  // r14.w <- p.w

#line 92
  lt r15.xyz, r4.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  lt r0.w, r14.w, l(0.000000)
  and r0.w, r0.w, l(1)
  imul null, r15.xyz, r0.wwww, r15.xyzx
  itof r15.xyz, r15.xyzx
  add r14.xyz, r4.xyzx, -r15.xyzx  // r14.x <- p.x; r14.y <- p.y; r14.z <- p.z

#line 146
  dp4 r0.w, r7.xyzw, r7.xyzw
  dp4 r2.w, r8.xyzw, r8.xyzw
  dp4 r4.x, r13.xyzw, r13.xyzw
  dp4 r4.y, r6.xyzw, r6.xyzw
  rsq r0.w, r0.w  // r0.w <- norm.x
  rsq r2.w, r2.w  // r2.w <- norm.y
  rsq r4.x, r4.x  // r4.x <- norm.z
  rsq r4.y, r4.y  // r4.y <- norm.w

#line 147
  mul r7.xyzw, r0.wwww, r7.xyzw  // r7.x <- p0.x; r7.y <- p0.y; r7.z <- p0.z; r7.w <- p0.w

#line 148
  mul r8.xyzw, r2.wwww, r8.xyzw  // r8.x <- p1.x; r8.y <- p1.y; r8.z <- p1.z; r8.w <- p1.w

#line 149
  mul r13.xyzw, r4.xxxx, r13.xyzw  // r13.x <- p2.x; r13.y <- p2.y; r13.z <- p2.z; r13.w <- p2.w

#line 150
  mul r4.xyzw, r4.yyyy, r6.xyzw  // r4.x <- p3.x; r4.y <- p3.y; r4.z <- p3.z; r4.w <- p3.w

#line 151
  dp4 r0.w, r14.xyzw, r14.xyzw
  rsq r0.w, r0.w
  mul r6.xyzw, r0.wwww, r14.xyzw  // r6.x <- p4.x; r6.y <- p4.y; r6.z <- p4.z; r6.w <- p4.w

#line 152
  dp4 r14.x, r5.xyzw, r5.xyzw
  dp4 r14.y, r9.xyzw, r9.xyzw
  dp4 r14.z, r10.xyzw, r10.xyzw
  add r14.xyz, -r14.xyzx, l(0.600000, 0.600000, 0.600000, 0.000000)
  max r14.xyz, r14.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r14.x <- m0.x; r14.y <- m0.y; r14.z <- m0.z

#line 153
  dp4 r15.x, r11.xyzw, r11.xyzw
  dp4 r15.y, r12.xyzw, r12.xyzw
  add r15.xy, -r15.xyxx, l(0.600000, 0.600000, 0.000000, 0.000000)
  max r15.xy, r15.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)  // r15.x <- m1.x; r15.y <- m1.y

#line 154
  mul r14.xyz, r14.xyzx, r14.xyzx

#line 155
  mul r15.xy, r15.xyxx, r15.xyxx

#line 156
  mul r14.xyz, r14.xyzx, r14.xyzx
  dp4 r5.x, r7.xyzw, r5.xyzw
  dp4 r5.y, r8.xyzw, r9.xyzw
  dp4 r5.z, r13.xyzw, r10.xyzw
  dp3 r0.w, r14.xyzx, r5.xyzx
  mul r5.xy, r15.xyxx, r15.xyxx
  dp4 r4.x, r4.xyzw, r11.xyzw
  dp4 r4.y, r6.xyzw, r12.xyzw
  dp2 r2.w, r5.xyxx, r4.xyxx
  add r0.w, r0.w, r2.w
  mul r2.z, r0.w, l(49.000000)  // r2.z <- <simplexNoise_id63 return value>

#line 329
  lt r4.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r2.xyzx
  lt r5.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r4.xyz, -r4.xyzx, r5.xyzx
  itof r4.xyz, r4.xyzx  // r4.x <- result_1143.x; r4.y <- result_1143.y; r4.z <- result_1143.z

#line 113
  lt r5.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), cb0[9].xyzx
  div r6.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[9].xyzx
  add r6.xyz, r6.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000)
  add r7.xyz, -|r2.xyzx|, l(1.000000, 1.000000, 1.000000, 0.000000)
  mad r6.xyz, r6.xyzx, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r6.xyz, |r2.xyzx|, r6.xyzx
  div r8.xyz, l(1.000000, 1.000000, 1.000000, 1.000000), |cb0[9].xyzx|
  add r8.xyz, r8.xyzx, l(-2.000000, -2.000000, -2.000000, 0.000000)
  mad r7.xyz, r8.xyzx, r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r2.xyz, |r2.xyzx|, r7.xyzx
  add r2.xyz, -r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  movc r2.xyz, r5.xyzx, r6.xyzx, r2.xyzx  // r2.z <- result

#line 332
  mul r2.xyz, r2.xyzx, r4.xyzx  // r2.x <- result_1146.x; r2.y <- result_1146.y; r2.z <- result_1146.z

#line 333
  mul r2.xyz, r2.xyzx, cb0[10].xyzx  // r2.x <- result_1160.x; r2.y <- result_1160.y; r2.z <- result_1160.z

#line 336
  div r2.xyz, r2.xyzx, r3.xxxx  // r2.x <- result_1173.x; r2.y <- result_1173.y; r2.z <- result_1173.z

#line 338
  mul r0.w, cb0[6].w, cb0[10].w  // r0.w <- result_1176

#line 343
  mad r2.xyz, r2.xyzx, r0.wwww, r0.xyzx  // r2.x <- result_1216.x; r2.y <- result_1216.y; r2.z <- result_1216.z

#line 345
  movc r0.xyz, cb0[11].xxxx, r2.xyzx, r0.xyzx

#line 350
  mad r2.xyz, r0.xyzx, cb0[6].wwww, r1.xyzx  // r2.x <- result_285.x; r2.y <- result_285.y; r2.z <- result_285.z

#line 352
  movc r2.xyw, cb0[11].yyyy, r2.yzyx, r1.yzyx  // r2.x <- result_1405.y; r2.y <- result_1405.z; r2.w <- result_1405.x

#line 355
  add r1.x, r1.w, cb0[6].w  // r1.x <- result_335

#line 356
  ilt r1.y, l(0), r3.y  // r1.y <- result_339

#line 357
  ge r1.z, r1.w, l(0.000000)  // r1.z <- result_343

#line 358
  lt r4.x, r1.w, r3.z  // r4.x <- result_346

#line 359
  and r1.y, r1.z, r1.y
  and r1.y, r4.x, r1.y  // r1.y <- result_348

#line 365
  movc r1.x, r1.y, r1.x, l(-1.000000)  // r1.x <- outputParam_363

#line 367
  movc r1.x, cb0[11].y, r1.x, r1.w  // r1.x <- result_1437

#line 369
  dp3 r4.x, r0.xyzx, r0.xyzx
  rsq r4.x, r4.x
  mul r4.xyw, r0.yzyx, r4.xxxx  // r4.x <- result_1313.y; r4.y <- result_1313.z; r4.w <- result_1313.x

#line 372
  mul r5.xyz, r2.wxyw, r4.xywx
  mad r5.xyz, r4.wxyw, r2.xywx, -r5.xyzx  // r5.x <- result_1319.z; r5.y <- result_1319.x; r5.z <- result_1319.y

#line 373
  dp3 r5.w, r5.xyzx, r5.xyzx  // r5.w <- result_1322

#line 374
  lt r6.x, r5.w, l(0.000010)  // r6.x <- result_1325

#line 375
  rsq r5.w, r5.w
  mul r5.xyz, r5.wwww, r5.xyzx  // r5.x <- result_1328.z; r5.y <- result_1328.x; r5.z <- result_1328.y

#line 384
  movc r5.xyz, r6.xxxx, cb0[12].zxyz, r5.xyzx  // r5.x <- result_1331.z; r5.y <- result_1331.x; r5.z <- result_1331.y

#line 387
  mul r6.xyz, r4.xywx, r5.xyzx
  mad r6.yzw, r5.zzxy, r4.yywx, -r6.xxyz  // r6.y <- result_1337.x; r6.z <- result_1337.y; r6.w <- result_1337.z

#line 391
  div_sat r5.w, r1.x, r3.z  // r5.w <- result_1351

#line 105
  frc r5.w, r5.w  // r5.w <- H

#line 108
  mad r7.xyz, r5.wwww, l(6.000000, 6.000000, 6.000000, 0.000000), l(-3.000000, -2.000000, -4.000000, 0.000000)

#line 109
  mad_sat r7.xyz, |r7.xyzx|, l(1.000000, -1.000000, -1.000000, 0.000000), l(-1.000000, 2.000000, 2.000000, 0.000000)  // r7.x <- <HUEtoRGB_id81 return value>.x; r7.y <- <HUEtoRGB_id81 return value>.y; r7.z <- <HUEtoRGB_id81 return value>.z

#line 166
  add r7.xyz, r7.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
  mad r7.xyz, r7.xyzx, cb0[13].wwww, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r7.xyz, r7.zxyz, cb0[14].xxxx  // r7.x <- <HSVtoRGB_id91 return value>.z; r7.y <- <HSVtoRGB_id91 return value>.x; r7.z <- <HSVtoRGB_id91 return value>.y

#line 412
  mov r0.w, r2.w
  store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
  mov r2.zw, r7.yyyz
  store_structured u0.xyzw, vThreadID.x, l(16), r2.xyzw
  mov r7.y, cb0[14].y
  mov r7.zw, r3.xxxy
  store_structured u0.xyzw, vThreadID.x, l(32), r7.xyzw
  mov r1.yz, r3.zzwz
  mov r1.w, r4.w
  store_structured u0.xyzw, vThreadID.x, l(48), r1.xyzw
  mov r4.zw, r5.yyyz
  store_structured u0.xyzw, vThreadID.x, l(64), r4.xyzw
  mov r6.x, r5.x
  store_structured u0.xyzw, vThreadID.x, l(80), r6.xyzw
  store_structured u0.xyz, vThreadID.x, l(96), cb0[13].xyzx

#line 414
endif 

#line 440
ret 
// Approximately 808 instruction slots used
***************************
*************************/
static const float PI_id12 = 3.1415926535897;
static const float3 vectorValuedNoiseOffsets_id22 = float3(17.0, -43.7, 67.0);
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Particle 
{
    float3 Velocity;
    float3 Position;
    float4 Color;
    float Drag;
    int Cycle;
    float Age;
    float LifeTime;
    int Id;
    float3 AxisY;
    float3 AxisX;
    float3 AxisZ;
    float3 Size3;
};
struct Global 
{
    float DeltaTime;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int input_49_id25;
    int input_644_id27;
    int input_589_id28;
    int input_604_id29;
    int input_582_id30;
    float input_211_id31;
    int input_735_id32;
    int input_723_id33;
    int input_452_id34;
    int input_397_id35;
    int input_412_id36;
    int input_390_id37;
    float input_208_id38;
    int input_543_id39;
    int input_531_id40;
    float3 input_205_id41;
    bool input_55_id42;
    int input_778_id43;
    int input_58_id44;
    float input_202_id45;
    float input_61_id46;
    float input_141_id47;
    float input_214_id48;
    float3 input_217_id49;
    float3 input_223_id50;
    float3 input_220_id51;
    float input_138_id52;
    bool input_225_id53;
    bool input_199_id54;
    float3 input_1232_id55;
    float3 input_228_id56;
    float input_231_id57;
    float input_234_id58;
    float input_237_id59;
};
RWStructuredBuffer<Particle> input_1387_id26;
RWStructuredBuffer<Global> input_1487_id60;
float4 mod289_id19(float4 x)
{
    return x - floor(x * 0.00346020761245674740484429065744f) * 289.0;
}
float mod289_id17(float x)
{
    return x - floor(x * 0.00346020761245674740484429065744f) * 289.0;
}
float4 grad4_id24(float j, float4 ip)
{
    const float4 ones = float4(1.0, 1.0, 1.0, -1.0);
    float4 p, s;
    p.xyz = floor(frac(j * ip.xyz) * 7.0) * ip.z - 1.0;
    p.w = 1.5 - dot(abs(p.xyz), ones.xyz);
    p.xyz -= sign(p.xyz) * (p.w < 0);
    return p;
}
float4 permute_id22(float4 x)
{
    return mod289_id19(x * x * 34.0 + x);
}
float permute_id23(float x)
{
    return mod289_id17(x * x * 34.0 + x);
}
float3 HUEtoRGB_id81(float H)
{
    H = frac(H);
    float R = abs(H * 6 - 3) - 1;
    float G = 2 - abs(H * 6 - 2);
    float B = 2 - abs(H * 6 - 4);
    return saturate(float3(R, G, B));
}
float bias_id72(float x, float control = 0.5)
{
    float result = control > 0 ? (x / ((((1.0 / control) - 2.0) * (1.0 - x)) + 1.0)) : 1 - (x / ((((1.0 / abs(control)) - 2.0) * (1.0 - x)) + 1.0));
    return result;
}
float simplexNoise_id63(float4 v)
{
    const float4 C = float4(0.138196601125011, 0.276393202250021, 0.414589803375032, -0.447213595499958);
    float4 i = floor(v + dot(v, 0.309016994374947451));
    float4 x0 = v - i + dot(i, C.xxxx);
    float4 i0;
    float3 isX = step(x0.yzw, x0.xxx);
    float3 isYZ = step(x0.zww, x0.yyz);
    i0.x = isX.x + isX.y + isX.z;
    i0.yzw = 1.0 - isX;
    i0.y += isYZ.x + isYZ.y;
    i0.zw += 1.0 - isYZ.xy;
    i0.z += isYZ.z;
    i0.w += 1.0 - isYZ.z;
    float4 i3 = saturate(i0);
    float4 i2 = saturate(i0 - 1.0);
    float4 i1 = saturate(i0 - 2.0);
    float4 x1 = x0 - i1 + C.xxxx;
    float4 x2 = x0 - i2 + C.yyyy;
    float4 x3 = x0 - i3 + C.zzzz;
    float4 x4 = x0 + C.wwww;
    i = mod289_id19(i);
    float j0 = permute_id23(permute_id23(permute_id23(permute_id23(i.w) + i.z) + i.y) + i.x);
    float4 j1 = permute_id22(permute_id22(permute_id22(permute_id22(i.w + float4(i1.w, i2.w, i3.w, 1.0)) + i.z + float4(i1.z, i2.z, i3.z, 1.0)) + i.y + float4(i1.y, i2.y, i3.y, 1.0)) + i.x + float4(i1.x, i2.x, i3.x, 1.0));
    const float4 ip = float4(0.003401360544217687075, 0.020408163265306122449, 0.142857142857142857143, 0.0);
    float4 p0 = grad4_id24(j0, ip);
    float4 p1 = grad4_id24(j1.x, ip);
    float4 p2 = grad4_id24(j1.y, ip);
    float4 p3 = grad4_id24(j1.z, ip);
    float4 p4 = grad4_id24(j1.w, ip);
    float4 norm = rsqrt(float4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
    p0 *= norm.x;
    p1 *= norm.y;
    p2 *= norm.z;
    p3 *= norm.w;
    p4 *= rsqrt(dot(p4, p4));
    float3 m0 = max(0.6 - float3(dot(x0, x0), dot(x1, x1), dot(x2, x2)), 0.0);
    float2 m1 = max(0.6 - float2(dot(x3, x3), dot(x4, x4)), 0.0);
    m0 = m0 * m0;
    m1 = m1 * m1;
    return 49.0 * (dot(m0 * m0, float3(dot(p0, x0), dot(p1, x1), dot(p2, x2))) + dot(m1 * m1, float2(dot(p3, x3), dot(p4, x4))));
}
void noiseDomainOffset_id44(inout float4 p1, out float4 p2, out float4 p3)
{
    p2 = p1 + vectorValuedNoiseOffsets_id22.x;
    p3 = p1 + vectorValuedNoiseOffsets_id22.y;
}
float3 HSVtoRGB_id91(float3 HSV)
{
    float3 RGB = HUEtoRGB_id81(HSV.x);
    return ((RGB - 1) * HSV.y + 1) * HSV.z;
}
float3 bias_id90(float3 x, float3 control = 0.5)
{
    return float3(bias_id72(x.x, control.x), bias_id72(x.y, control.y), bias_id72(x.z, control.z));
}
float3 simplexNoise34_id89(float4 p)
{
    float4 p2, p3;
    noiseDomainOffset_id44(p, p2, p3);
    return float3(simplexNoise_id63(p), simplexNoise_id63(p2), simplexNoise_id63(p3));
}
float3 cast31_id88(float p)
{
    return p.xxx;
}
float cast11_id87(float p)
{
    return p;
}
float cast13_id86(float3 p)
{
    return p.x;
}
float3 pcg3d_id85(uint3 v)
{
    v = v * 1664525 + 1013904223;
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v = v ^ (v >> 16);
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    return float3(v) * (1.0 / float(0xffffffff));
}
void Compute_id4(inout CS_STREAMS streams)
{
    int result_1505 = streams.DispatchThreadId_id1.x;
    bool result_1508 = result_1505 >= input_49_id25;
    if (result_1508)
    {
        return;
    }
    int result_1385 = streams.DispatchThreadId_id1.x;
    Particle result_1389 = input_1387_id26[result_1385];
    float3 result_1397 = result_1389.Velocity;
    float result_593 = -1;
    int result_641 = streams.DispatchThreadId_id1.x;
    int3 result_658 = int3(result_641, input_644_id27, input_589_id28);
    float3 result_661 = pcg3d_id85(result_658);
    float result_664 = cast13_id86(result_661);
    float result_670 = cast11_id87(result_664);
    float result_673 = lerp(result_593, 1, result_670);
    float result_676 = 3.1415927 * result_673;
    float result_679 = sin(result_676);
    float result_682 = cos(result_676);
    float2 result_685 = float2(result_679, result_682);
    int result_601 = streams.DispatchThreadId_id1.x;
    int3 result_618 = int3(result_601, input_604_id29, input_582_id30);
    float3 result_621 = pcg3d_id85(result_618);
    float result_624 = cast13_id86(result_621);
    float result_630 = cast11_id87(result_624);
    float result_633 = lerp(result_593, 1, result_630);
    float result_688 = result_633 * result_633;
    float result_693 = 1 - result_688;
    float result_696 = sqrt(result_693);
    float2 result_699 = float2(result_696, result_696);
    float2 result_702 = result_685 * result_699;
    float result_706 = result_702.x;
    float result_710 = result_702.y;
    float3 result_713 = float3(result_706, result_710, result_633);
    float3 result_717 = cast31_id88(input_211_id31);
    float3 result_720 = result_713 * result_717;
    int result_732 = streams.DispatchThreadId_id1.x;
    int3 result_749 = int3(result_732, input_735_id32, input_723_id33);
    float3 result_752 = pcg3d_id85(result_749);
    float result_755 = cast13_id86(result_752);
    float result_761 = pow(result_755, 0.3333333);
    float3 result_764 = float3(result_761, result_761, result_761);
    float3 result_767 = result_720 * result_764;
    float3 result_1405 = result_1389.Position;
    float result_401 = -1;
    int result_449 = streams.DispatchThreadId_id1.x;
    int3 result_466 = int3(result_449, input_452_id34, input_397_id35);
    float3 result_469 = pcg3d_id85(result_466);
    float result_472 = cast13_id86(result_469);
    float result_478 = cast11_id87(result_472);
    float result_481 = lerp(result_401, 1, result_478);
    float result_484 = 3.1415927 * result_481;
    float result_487 = sin(result_484);
    float result_490 = cos(result_484);
    float2 result_493 = float2(result_487, result_490);
    int result_409 = streams.DispatchThreadId_id1.x;
    int3 result_426 = int3(result_409, input_412_id36, input_390_id37);
    float3 result_429 = pcg3d_id85(result_426);
    float result_432 = cast13_id86(result_429);
    float result_438 = cast11_id87(result_432);
    float result_441 = lerp(result_401, 1, result_438);
    float result_496 = result_441 * result_441;
    float result_501 = 1 - result_496;
    float result_504 = sqrt(result_501);
    float2 result_507 = float2(result_504, result_504);
    float2 result_510 = result_493 * result_507;
    float result_514 = result_510.x;
    float result_518 = result_510.y;
    float3 result_521 = float3(result_514, result_518, result_441);
    float3 result_525 = cast31_id88(input_208_id38);
    float3 result_528 = result_521 * result_525;
    int result_540 = streams.DispatchThreadId_id1.x;
    int3 result_557 = int3(result_540, input_543_id39, input_531_id40);
    float3 result_560 = pcg3d_id85(result_557);
    float result_563 = cast13_id86(result_560);
    float result_569 = pow(result_563, 0.3333333);
    float3 result_572 = float3(result_569, result_569, result_569);
    float3 result_575 = result_528 * result_572;
    float3 result_579 = result_575 + input_205_id41;
    float4 result_1413 = result_1389.Color;
    float result_1421 = result_1389.Drag;
    int result_1429 = result_1389.Cycle;
    int result_931 = result_1429 + 1;
    float result_1437 = result_1389.Age;
    float result_1445 = result_1389.LifeTime;
    int result_1453 = result_1389.Id;
    int result_907 = streams.DispatchThreadId_id1.x;
    int result_775 = streams.DispatchThreadId_id1.x;
    int3 result_792 = int3(result_775, input_778_id43, input_58_id44);
    float3 result_795 = pcg3d_id85(result_792);
    float result_798 = cast13_id86(result_795);
    bool result_951 = result_798 < input_202_id45;
    bool result_978 = result_1429 == 0;
    bool result_982 = result_1437 < 0;
    bool result_984 = result_978 || result_982;
    bool result_986 = !result_984;
    bool result_988 = !result_986;
    bool result_990 = input_55_id42 && result_951 && result_988;
    if (result_990)
    {
        result_1397 = result_767;
        result_1405 = result_579;
        result_1413 = float4(1, 1, 1, 1);
        result_1421 = 1;
        result_1429 = result_931;
        result_1437 = 0;
        result_1445 = 3;
        result_1453 = result_907;
    }
    float outputParam_1494 = 0;
    outputParam_1494 = input_61_id46;
    float3 result_1012 = float3(input_141_id47, input_141_id47, input_141_id47);
    float3 result_1015 = result_1405 * result_1012;
    float result_1078 = result_1015.x;
    float result_1082 = result_1015.y;
    float result_1086 = result_1015.z;
    float4 result_1089 = float4(result_1078, result_1082, result_1086, input_214_id48);
    float result_1095 = input_217_id49.x;
    float result_1099 = input_217_id49.y;
    float result_1103 = input_217_id49.z;
    float4 result_1106 = float4(result_1095, result_1099, result_1103, 1);
    float4 result_1122 = result_1089 * result_1106;
    float4 result_1113 = float4(0, 0, 0, 0);
    float4 result_1126 = result_1122 + result_1113;
    float3 result_1129 = simplexNoise34_id89(result_1126);
    float3 result_1143 = sign(result_1129);
    float3 result_1136 = abs(result_1129);
    float3 result_1140 = bias_id90(result_1136, input_223_id50);
    float3 result_1146 = result_1143 * result_1140;
    float3 result_1160 = result_1146 * input_220_id51;
    float3 result_1164 = result_1160 + float3(0, 0, 0);
    float3 result_1170 = cast31_id88(result_1421);
    float3 result_1173 = result_1164 / result_1170;
    float result_1167 = input_138_id52;
    float result_1176 = result_1167 * outputParam_1494;
    float3 result_1179 = cast31_id88(result_1176);
    float3 result_1182 = result_1173 * result_1179;
    if (input_225_id53)
    {
        float3 result_1216 = result_1397 + result_1182;
        result_1397 = result_1216;
    }
    if (input_199_id54)
    {
        float3 result_279 = cast31_id88(outputParam_1494);
        float3 result_282 = result_1397 * result_279;
        float3 result_285 = result_1405 + result_282;
        result_1405 = result_285;
    }
    if (input_199_id54)
    {
        float result_335 = result_1437 + outputParam_1494;
        bool result_339 = result_1429 > 0;
        bool result_343 = result_1437 >= 0;
        bool result_346 = result_1437 < result_1445;
        bool result_348 = result_339 && result_343 && result_346;
        float outputParam_363 = -1;
        if (result_348)
        {
            float result_356 = result_335 + 0;
            outputParam_363 = result_356;
        }
        result_1437 = outputParam_363;
    }
    float3 result_1461 = result_1389.AxisY;
    float3 result_1313 = normalize(result_1397);
    result_1461 = result_1313;
    float3 result_1469 = result_1389.AxisX;
    float3 result_1319 = cross(result_1461, result_1405);
    float result_1322 = dot(result_1319, result_1319);
    bool result_1325 = result_1322 < 1E-05;
    float3 result_1328 = normalize(result_1319);
    float3 result_1331;
    if (result_1325)
    {
        result_1331 = input_1232_id55;
    }
    else
    {
        result_1331 = result_1328;
    }
    result_1469 = result_1331;
    float3 result_1477 = result_1389.AxisZ;
    float3 result_1337 = cross(result_1469, result_1461);
    result_1477 = result_1337;
    float3 result_1485 = result_1389.Size3;
    result_1485 = input_228_id56;
    float result_1348 = result_1437 / result_1445;
    float result_1351 = saturate(result_1348);
    float3 result_1354 = float3(result_1351, input_231_id57, input_234_id58);
    float3 result_1357 = HSVtoRGB_id91(result_1354);
    float result_1361 = result_1357.x;
    float result_1365 = result_1357.y;
    float result_1369 = result_1357.z;
    float4 result_1372 = float4(result_1361, result_1365, result_1369, input_237_id59);
    result_1413 = result_1372;
    result_1389.Velocity = result_1397;
    result_1389.Position = result_1405;
    result_1389.Color = result_1413;
    result_1389.Drag = result_1421;
    result_1389.Cycle = result_1429;
    result_1389.Age = result_1437;
    result_1389.LifeTime = result_1445;
    result_1389.Id = result_1453;
    result_1389.AxisY = result_1461;
    result_1389.AxisX = result_1469;
    result_1389.AxisZ = result_1477;
    result_1389.Size3 = result_1485;
    input_1387_id26[result_1385] = result_1389;
    Global result_1489 = input_1487_id60[result_1385];
    input_1487_id60[result_1385] = result_1489;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(128, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 128;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 128 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
