/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin DropShadow_TextureFX [{Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}]
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 16]
@C    InputValue_id94 => ShaderFX.InputValueFloat4
cbuffer PerView [Size: 32]
@C    NearClipPlane_id74 => Camera.NearClipPlane
@C    FarClipPlane_id75 => Camera.FarClipPlane
@C    ZProjection_id76 => Camera.ZProjection
@C    ViewSize_id77 => Camera.ViewSize
@C    AspectRatio_id78 => Camera.AspectRatio
cbuffer Globals [Size: 128]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    Blur_id88 => DropShadow_TextureFX.Blur
@C    Offset_id89 => DropShadow_TextureFX.Offset
@C    Angle_id90 => DropShadow_TextureFX.Angle
@C    Color_id91 => DropShadow_TextureFX.Color
@C    Alpha_id92 => DropShadow_TextureFX.Alpha
@C    Extension_id93 => DropShadow_TextureFX.Extension
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (0-0)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    PerView => PerView [Stage: Pixel, Slot: (1-1)]
@R    Globals => Globals [Stage: Pixel, Slot: (2-2)]
***************************
*****     Sources     *****
***************************
@S    DropShadow_TextureFX => e7130d044b0f5b84e5fb247f58005794
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => bc345c7d961ff4b1766c5b1d5e15bd5a
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 196 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_52fcd45d6bff30872b8ddcc02fe78954.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 200
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 6d14b0c7fcae08ee356a326c97080c04
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id94;            // Offset:    0 Size:    16
//
// }
//
// cbuffer PerView
// {
//
//   float NearClipPlane_id74;          // Offset:    0 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id75;           // Offset:    4 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id76;           // Offset:    8 Size:     8 [unused]
//   float2 ViewSize_id77;              // Offset:   16 Size:     8
//   float AspectRatio_id78;            // Offset:   24 Size:     4 [unused]
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   float Blur_id88;                   // Offset:   80 Size:     4
//      = 0x3f000000 
//   float Offset_id89;                 // Offset:   84 Size:     4
//      = 0x3d4ccccd 
//   float Angle_id90;                  // Offset:   88 Size:     4
//      = 0x3f666666 
//   float4 Color_id91;                 // Offset:   96 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x3f800000 
//   float Alpha_id92;                  // Offset:  112 Size:     4
//      = 0x3f800000 
//   float Extension_id93;              // Offset:  116 Size:     4
//      = 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Sampler0_id52                     sampler      NA          NA             s0      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// PerView                           cbuffer      NA          NA            cb1      1 
// Globals                           cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB1[2], immediateIndexed
dcl_constantbuffer CB2[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 155 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_52fcd45d6bff30872b8ddcc02fe78954.hlsl"
add r0.xyzw, cb2[5].zzzz, l(0.000000, -0.250000, 0.000000, -0.250000)
mul r0.xyzw, r0.xyzw, l(6.283185, 6.283185, 6.283185, 6.283185)
sincos r0.xyzw, null, r0.xyzw
mul r1.x, cb2[5].y, l(1.414214)
mad r0.xyzw, r1.xxxx, r0.xyzw, v1.xyxy  // r0.z <- sx.x; r0.w <- sx.y

#line 156
mul r1.xyzw, cb2[0].xyxy, l(0.500000, 0.500000, 0.500000, 0.500000)

#line 153
max r2.x, cb1[1].y, cb1[1].x
log r2.x, r2.x
mul r2.x, r2.x, cb2[5].x  // r2.x <- lod

#line 156
exp r2.y, r2.x
mul r1.xyzw, r1.xyzw, r2.yyyy
mov_sat r2.y, r2.x

#line 158
mad r2.zw, r1.zzzw, r2.yyyy, r0.zzzw
sample_l_indexable(texture2d)(float,float,float,float) r2.z, r2.zwzz, t0.xywz, s0, r2.x

#line 157
sample_l_indexable(texture2d)(float,float,float,float) r2.w, r0.zwzz, t0.xyzw, s0, r2.x  // r2.w <- col.w

#line 158
add r2.z, r2.z, r2.w  // r2.z <- col.w

#line 156
mul r3.xyzw, r1.xyzw, r2.yyyy  // r3.z <- off.x; r3.w <- off.y

#line 160
mad r1.xy, -r1.zwzz, r2.yyyy, r0.zwzz
sample_l_indexable(texture2d)(float,float,float,float) r1.x, r1.xyxx, t0.wxyz, s0, r2.x

#line 161
mad r4.xyzw, r3.zwzw, l(1.000000, -1.000000, -1.000000, 1.000000), r0.zwzw

#line 159
sample_l_indexable(texture2d)(float,float,float,float) r1.y, r4.xyxx, t0.xwyz, s0, r2.x

#line 161
sample_l_indexable(texture2d)(float,float,float,float) r1.z, r4.zwzz, t0.xywz, s0, r2.x

#line 159
add r1.y, r1.y, r2.z  // r1.y <- col.w

#line 160
add r1.x, r1.x, r1.y  // r1.x <- col.w

#line 161
add r1.x, r1.z, r1.x

#line 164
mad r4.xyzw, r3.zwzw, l(0.000000, 1.860000, 0.000000, -1.860000), r0.zwzw

#line 166
mad r0.xyzw, r3.xyzw, l(-1.860000, 0.000000, 1.860000, 0.000000), r0.xyzw

#line 163
sample_l_indexable(texture2d)(float,float,float,float) r1.y, r4.xyxx, t0.xwyz, s0, r2.x

#line 164
sample_l_indexable(texture2d)(float,float,float,float) r1.z, r4.zwzz, t0.xywz, s0, r2.x

#line 163
add r1.x, r1.y, r1.x

#line 164
add r1.x, r1.z, r1.x

#line 165
sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.wxyz, s0, r2.x

#line 166
sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.zwzz, t0.xwyz, s0, r2.x

#line 165
add r0.x, r0.x, r1.x  // r0.x <- col.w

#line 166
add r0.x, r0.y, r0.x

#line 167
mul r0.x, r0.x, l(0.111111)

#line 168
exp r0.y, cb2[7].y
mul_sat r0.x, r0.x, r0.y
mul r0.w, r0.x, cb2[7].x
mov r0.xyz, l(1.000000,1.000000,1.000000,0)
mul r1.xyzw, r0.xyzw, cb2[6].xyzw  // r1.x <- col.x; r1.y <- col.y; r1.z <- col.z; r1.w <- col.w

#line 175
sample_l_indexable(texture2d)(float,float,float,float) r2.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r2.x <- <InTex0_id26 return value>.x; r2.y <- <InTex0_id26 return value>.y; r2.z <- <InTex0_id26 return value>.z; r2.w <- <InTex0_id26 return value>.w

#line 169
mad r0.xyz, -cb2[6].xyzx, r0.xyzx, r2.xyzx
mad r0.xyz, r2.wwww, r0.xyzx, r1.xyzx  // r0.x <- col.x; r0.y <- col.y; r0.z <- col.z

#line 170
max r0.w, r1.w, r2.w  // r0.w <- col.w

#line 180
add r0.xyzw, -r2.xyzw, r0.xyzw
mad o0.xyzw, cb0[0].xyzw, r0.xyzw, r2.xyzw

#line 189
ret 
// Approximately 48 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id94;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    float Blur_id88 = 0.5f;
    float Offset_id89 = 0.05f;
    float Angle_id90 = 0.9f;
    float4 Color_id91 = float4(0.0f, 0.0f, 0.0f, 1.0f);
    float Alpha_id92 = 1.0f;
    float Extension_id93 = 0.0f;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float4 Compute_id30()
{
    return InputValue_id94;
}
float4 Filter_id29(inout PS_STREAMS streams, float4 tex0col)
{
    float2 uv = streams.TexCoord_id62;
    float2 R = ViewSize_id77;
    float4 c0 = Texture0_id14.SampleLevel(Sampler0_id52, uv, 0);
    float lod = (Blur_id88) * log2(max(R.x, R.y));
    float4 col = 0;
    float2 sx = uv + sqrt(2) * Offset_id89 * sin((Angle_id90 + float2(0, -0.25)) * acos(-1) * 2);
    float2 off = .5 * Texture0TexelSize_id15 * pow(2, lod) * saturate(lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(0, 0) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(1, 1) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(1, -1) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(-1, -1) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(-1, 1) * off, lod);
    off *= 1.86;
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(0, 1) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(0, -1) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(-1, 0) * off, lod);
    col += Texture0_id14.SampleLevel(Sampler0_id52, sx + float2(1, 0) * off, lod);
    col /= 9;
    col = Color_id91 * float4(1, 1, 1, saturate(pow(2, Extension_id93) * col.a) * Alpha_id92);
    col.rgb = lerp(col.rgb, c0.rgb, c0.a);
    col.a = max(col.a, c0.a);
    return col;
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id29(streams, col), Compute_id30());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
