/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ShaderFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin GPUDamperVector3Piv_ShaderFX [{Damping = InputFloat3<ShaderFX.InputValueFloat3.i1,PerUpdate>}, {Index = InputUInt<ShaderFX.InputValueUInt,PerUpdate>}, {Value = InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>}]
@P Value: InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>
@P Damping: InputFloat3<ShaderFX.InputValueFloat3.i1,PerUpdate>
@P Index: InputUInt<ShaderFX.InputValueUInt,PerUpdate>
***************************
*****     Sources     *****
***************************
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    GPUDamperVector3Piv_ShaderFX => b6108c6250ed771473753b46c8c3f6e2
@S    ComputeFloat3 => fcd85992058d53e05e3805fecfe8c7a7
@S    ComputeUInt => 707f4166cd9f83784b42c78a0cc57287
@S    InputFloat3 => 8982608ad2ca3465dcfa300c570359d5
@S    DeclFloat3 => f8ad0be4bea340b9223aeec02eb4c744
@S    InputUInt => e8bcca0c5de594d673cd9669b7bdad68
@S    DeclUInt => a5c3b92d01d17f67ecdac3662ed6737d
***************************
*****     Stages      *****
***************************
@G    Vertex => 7ae935036a1b3058f70dafa629ea5dea
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
vs_5_0
dcl_globalFlags refactoringAllowed

#line 17 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_ShaderFXEffect_247cdab31663ff927296e12e1bddaa16.hlsl"
ret 
// Approximately 1 instruction slots used
***************************
*************************/
struct VS_STREAMS 
{
};
struct VS_INPUT 
{
};
cbuffer PerUpdate 
{
    float3 InputValue_id18;
    uint InputValue_id19;
    float3 InputValue_id20;
};
RWStructuredBuffer<float3> LastValue_id17;
void VSMain()
{
    VS_STREAMS streams = (VS_STREAMS)0;
}
