/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ShaderFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin FuseGeometryBumpExtension_ShaderFX [{bumpAmt = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}, {bumpgrad = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {ShadingColor0 = ComputeColor}]
@P bumpgrad: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
@P bumpAmt: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P ShadingColor0: ComputeColor
***************************
*****     Sources     *****
***************************
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    FuseGeometryBumpExtension_ShaderFX => c70cb7edea67a7580a27bc945a4045e2
@S    MaterialExtension => bd314d2afed93384fa52af5d242de440
@S    ShadingBase => b0f11f286acc22f5586417a8311cb632
@S    ComputeColor => c875a0e093379dd74cd9a5a73aca830f
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    NormalBase => b2b31addde884722f942622026837c39
@S    NormalUpdate => 6fd3c9b8fa943d9951400645fe40502e
@S    NormalStream => ea68512133899a045766d21afb59733a
@S    TransformationBase => 21981c533d88209fdcf07f258ddf01c2
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    FuseGeometryMeshSurfaceStream => eef9b71305af04b043dd2e3c65f6602b
@S    ComputeFloat4 => bc345c7d961ff4b1766c5b1d5e15bd5a
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => c4ed34ce963d036cd6b247d2e25215e8
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION_WS              0   xyzw        0     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// NORMALWS                 0   xyz         0     NONE   float   xyz 
// POSITION_WS              0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyzw
dcl_output o0.xyz
dcl_output o1.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.PositionWS_id16.x; v0.y <- __input__.PositionWS_id16.y; v0.z <- __input__.PositionWS_id16.z; v0.w <- __input__.PositionWS_id16.w; 
//   o1.x <- <VSMain return value>.PositionWS_id16.x; o1.y <- <VSMain return value>.PositionWS_id16.y; o1.z <- <VSMain return value>.PositionWS_id16.z; o1.w <- <VSMain return value>.PositionWS_id16.w; 
//   o0.x <- <VSMain return value>.normalWS_id21.x; o0.y <- <VSMain return value>.normalWS_id21.y; o0.z <- <VSMain return value>.normalWS_id21.z
//
#line 246 "C:\Program Files\vvvv\vvvv_gamma_2022.5.0-0485-g8f46e4a34a\log\shader_ShaderFXEffect_49979da865b61c7f1543835ce0062bbc.hlsl"
mov o0.xyz, l(0,0,0,0)
mov o1.xyzw, v0.xyzw
ret 
// Approximately 3 instruction slots used
@G    Pixel => 0c34834b86c06e7b539e69815e8e4f41
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// NORMALWS                 0   xyz         0     NONE   float       
// POSITION_WS              0   xyzw        1     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.normalWS_id21.x; v0.y <- __input__.normalWS_id21.y; v0.z <- __input__.normalWS_id21.z; 
//   v1.x <- __input__.PositionWS_id16.x; v1.y <- __input__.PositionWS_id16.y; v1.z <- __input__.PositionWS_id16.z; v1.w <- __input__.PositionWS_id16.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 235 "C:\Program Files\vvvv\vvvv_gamma_2022.5.0-0485-g8f46e4a34a\log\shader_ShaderFXEffect_49979da865b61c7f1543835ce0062bbc.hlsl"
mov o0.xyzw, l(0,0,0,0)
ret 
// Approximately 2 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 PositionWS_id16;
    float3 normalWS_id21;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float3 normalWS_id21 : NORMALWS;
    float4 PositionWS_id16 : POSITION_WS;
};
struct VS_STREAMS 
{
    float4 PositionWS_id16;
    float3 normalWS_id21;
};
struct VS_OUTPUT 
{
    float3 normalWS_id21 : NORMALWS;
    float4 PositionWS_id16 : POSITION_WS;
};
struct VS_INPUT 
{
    float4 PositionWS_id16 : POSITION_WS;
};
struct MeshSurface 
{
    float3 p;
    float3 n;
    float2 uv;
};
cbuffer PerDraw 
{
    float4x4 World_id30;
    float4x4 WorldInverse_id31;
    float4x4 WorldInverseTranspose_id32;
    float4x4 WorldView_id33;
    float4x4 WorldViewInverse_id34;
    float4x4 WorldViewProjection_id35;
    float3 WorldScale_id36;
    float4 EyeMS_id37;
};
cbuffer PerUpdate 
{
    float InputValue_id101;
    float4 InputValue_id102;
};
cbuffer PerView 
{
    float4x4 View_id23;
    float4x4 ViewInverse_id24;
    float4x4 Projection_id25;
    float4x4 ProjectionInverse_id26;
    float4x4 ViewProjection_id27;
    float2 ProjScreenRay_id28;
    float4 Eye_id29;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id39;
    float2 Texture1TexelSize_id41;
    float2 Texture2TexelSize_id43;
    float2 Texture3TexelSize_id45;
    float2 Texture4TexelSize_id47;
    float2 Texture5TexelSize_id49;
    float2 Texture6TexelSize_id51;
    float2 Texture7TexelSize_id53;
    float2 Texture8TexelSize_id55;
    float2 Texture9TexelSize_id57;
};
Texture2D Texture0_id38;
Texture2D Texture1_id40;
Texture2D Texture2_id42;
Texture2D Texture3_id44;
Texture2D Texture4_id46;
Texture2D Texture5_id48;
Texture2D Texture6_id50;
Texture2D Texture7_id52;
Texture2D Texture8_id54;
Texture2D Texture9_id56;
TextureCube TextureCube0_id58;
TextureCube TextureCube1_id59;
TextureCube TextureCube2_id60;
TextureCube TextureCube3_id61;
Texture3D Texture3D0_id62;
Texture3D Texture3D1_id63;
Texture3D Texture3D2_id64;
Texture3D Texture3D3_id65;
SamplerState Sampler_id66;
SamplerState PointSampler_id67 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id68 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id69 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id70 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id71 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id72 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id73 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id74 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id75 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id76;
SamplerState Sampler1_id77;
SamplerState Sampler2_id78;
SamplerState Sampler3_id79;
SamplerState Sampler4_id80;
SamplerState Sampler5_id81;
SamplerState Sampler6_id82;
SamplerState Sampler7_id83;
SamplerState Sampler8_id84;
SamplerState Sampler9_id85;
float4 Compute_id20()
{
    return 0;
}
float4 Shading_id2()
{
    return Compute_id20();
}
float4 Shading_id16()
{
    return Shading_id2();
}
float Compute_id22()
{
    return InputValue_id101;
}
float4 Compute_id21()
{
    return InputValue_id102;
}
float4 Shading_id19(inout PS_STREAMS streams)
{
    float3 p = streams.PositionWS_id16.xyz;
    float3 n = streams.normalWS_id21.xyz;
    float4 bumpAndGradient = Compute_id21();
    float bump = bumpAndGradient.x;
    float3 grad = bumpAndGradient.yzw;
    float bumpFactor = Compute_id22();
    p += bump * n * bumpFactor;
    n += grad * bumpFactor;
    n = normalize(n);
    streams.PositionWS_id16.xyz = p;
    streams.normalWS_id21.xyz = n;
    return Shading_id16();
}
void PSMain_id1()
{
}
void PostTransformPosition_id13()
{
}
void TransformPosition_id12()
{
}
void PreTransformPosition_id11()
{
}
void GenerateNormal_VS_id4(inout VS_STREAMS streams)
{
    streams.normalWS_id21 = 0.0f;
}
void VSMain_id0()
{
}
void PSMain_id3(inout PS_STREAMS streams)
{
    PSMain_id1();
    streams.ColorTarget_id2 = Shading_id19(streams);
}
void GenerateNormal_PS_id5()
{
}
void BaseTransformVS_id15()
{
    PreTransformPosition_id11();
    TransformPosition_id12();
    PostTransformPosition_id13();
}
void VSMain_id10(inout VS_STREAMS streams)
{
    VSMain_id0();
    GenerateNormal_VS_id4(streams);
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.normalWS_id21 = __input__.normalWS_id21;
    streams.PositionWS_id16 = __input__.PositionWS_id16;
    GenerateNormal_PS_id5();
    PSMain_id3(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.PositionWS_id16 = __input__.PositionWS_id16;
    VSMain_id10(streams);
    BaseTransformVS_id15();
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.normalWS_id21 = streams.normalWS_id21;
    __output__.PositionWS_id16 = streams.PositionWS_id16;
    return __output__;
}
