/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:1 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin LineFromToMesh_ComputeFX [{Color = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}, {RibbonUp = InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>}, {TubeUp = InputFloat3<ShaderFX.InputValueFloat3.i1,PerUpdate>}, {Width = InputFloat<ShaderFX.InputValueFloat,PerUpdate>}]
@P Width: InputFloat<ShaderFX.InputValueFloat,PerUpdate>
@P Color: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
@P RibbonUp: InputFloat3<ShaderFX.InputValueFloat3,PerUpdate>
@P TubeUp: InputFloat3<ShaderFX.InputValueFloat3.i1,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 112]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    Radius_id46 => LineFromToMesh_ComputeFX.Radius
@C    ThicknessSpace_id47 => LineFromToMesh_ComputeFX.ThicknessSpace
@C    MeshType_id48 => LineFromToMesh_ComputeFX.MeshType
@C    Transform_id49 => LineFromToMesh_ComputeFX.Transform
@C    Resolution_id50 => LineFromToMesh_ComputeFX.Resolution
@C    ViewAlign_id51 => LineFromToMesh_ComputeFX.ViewAlign
@C    NormalBend_id52 => LineFromToMesh_ComputeFX.NormalBend
cbuffer PerUpdate [Size: 48]
@C    InputValue_id57 => ShaderFX.InputValueFloat4
@C    InputValue_id58 => ShaderFX.InputValueFloat3
@C    InputValue_id59 => ShaderFX.InputValueFloat3.i1
@C    InputValue_id60 => ShaderFX.InputValueFloat
cbuffer PerView [Size: 384]
@C    View_id11 => Transformation.View
@C    ViewInverse_id12 => Transformation.ViewInverse
@C    Projection_id13 => Transformation.Projection
@C    ProjectionInverse_id14 => Transformation.ProjectionInverse
@C    ViewProjection_id15 => Transformation.ViewProjection
@C    ProjScreenRay_id16 => Transformation.ProjScreenRay
@C    Eye_id17 => Transformation.Eye
@C    NearClipPlane_id26 => Camera.NearClipPlane
@C    FarClipPlane_id27 => Camera.FarClipPlane
@C    ZProjection_id28 => Camera.ZProjection
@C    ViewSize_id29 => Camera.ViewSize
@C    AspectRatio_id30 => Camera.AspectRatio
***************************
******  Resources    ******
***************************
@R    FromBuffer_id43 => LineFromToMesh_ComputeFX.FromBuffer [Stage: Compute, Slot: (0-0)]
@R    ToBuffer_id44 => LineFromToMesh_ComputeFX.ToBuffer [Stage: Compute, Slot: (1-1)]
@R    outputBuffer_id45 => LineFromToMesh_ComputeFX.outputBuffer [Stage: Compute, Slot: (0-0)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Compute, Slot: (1-1)]
@R    PerView => PerView [Stage: Compute, Slot: (2-2)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    LineFromToMesh_ComputeFX => a625652729b220f1afdda377ef8fa693
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    FuseCommonBuffer => 65b35e271cc4ebdf63ebebd0f53f481c
@S    FuseCommonTypes => 294db151085426350495bb436e7480dd
@S    LineAttributeStream => c7aed8089f4a7eedb3fda14d4c26e4b9
@S    LineCommon => 6f3c9bb0f15c5b291748baebfb4315ac
@S    FuseCoreMath => fdeacca3b2f02b9acb6430ed603f50b4
@S    Pos3Norm3Col4Tex2Tan4Vertex => fbfbdc4d1671a224b444e9e4cfddfd89
@S    ComputeFloat => 3607bb1fa125ec30a7afa60be79c4817
@S    ComputeFloat4 => bc345c7d961ff4b1766c5b1d5e15bd5a
@S    ComputeFloat3 => fcd85992058d53e05e3805fecfe8c7a7
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
@S    InputFloat3 => 8982608ad2ca3465dcfa300c570359d5
@S    DeclFloat3 => f8ad0be4bea340b9223aeec02eb4c744
@S    InputFloat => f487ac725dafb0434d14d0273ee628a8
@S    DeclFloat => 75bf7e6f5246ed3d7aa33ab3c7183aa4
***************************
*****     Stages      *****
***************************
@G    Compute => ac25c5116599aa9a992153faf58a74be
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   float Radius_id46;                 // Offset:   12 Size:     4
//      = 0x3e19999a 
//   int ThicknessSpace_id47;           // Offset:   16 Size:     4
//      = 0x00000000 
//   int MeshType_id48;                 // Offset:   20 Size:     4
//      = 0x00000000 
//   float4x4 Transform_id49;           // Offset:   32 Size:    64
//   int Resolution_id50;               // Offset:   96 Size:     4
//   bool ViewAlign_id51;               // Offset:  100 Size:     4
//   bool NormalBend_id52;              // Offset:  104 Size:     4
//
// }
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id57;            // Offset:    0 Size:    16
//   float3 InputValue_id58;            // Offset:   16 Size:    12
//   float3 InputValue_id59;            // Offset:   32 Size:    12
//   float InputValue_id60;             // Offset:   44 Size:     4
//
// }
//
// cbuffer PerView
// {
//
//   float4x4 View_id11;                // Offset:    0 Size:    64 [unused]
//   float4x4 ViewInverse_id12;         // Offset:   64 Size:    64
//   float4x4 Projection_id13;          // Offset:  128 Size:    64 [unused]
//   float4x4 ProjectionInverse_id14;   // Offset:  192 Size:    64
//   float4x4 ViewProjection_id15;      // Offset:  256 Size:    64 [unused]
//   float2 ProjScreenRay_id16;         // Offset:  320 Size:     8 [unused]
//   float4 Eye_id17;                   // Offset:  336 Size:    16 [unused]
//   float NearClipPlane_id26;          // Offset:  352 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id27;           // Offset:  356 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id28;           // Offset:  360 Size:     8 [unused]
//   float2 ViewSize_id29;              // Offset:  368 Size:     8 [unused]
//   float AspectRatio_id30;            // Offset:  376 Size:     4 [unused]
//
// }
//
// Resource bind info for FromBuffer_id43
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for ToBuffer_id44
// {
//
//   float3 $Element;                   // Offset:    0 Size:    12
//
// }
//
// Resource bind info for outputBuffer_id45
// {
//
//   struct Pos3Norm3Col4Tex2Tan4Id2
//   {
//       
//       float3 Position;               // Offset:    0
//       float3 Normal;                 // Offset:   12
//       float4 Color;                  // Offset:   24
//       float2 TexCoord;               // Offset:   40
//       float4 Tangent;                // Offset:   48
//       uint LineId;                   // Offset:   64
//       uint SegmentId;                // Offset:   68
//
//   } $Element;                        // Offset:    0 Size:    72
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// FromBuffer_id43                   texture  struct         r/o             t0      1 
// ToBuffer_id44                     texture  struct         r/o             t1      1 
// outputBuffer_id45                     UAV  struct         r/w             u0      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
// PerUpdate                         cbuffer      NA          NA            cb1      1 
// PerView                           cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[7], immediateIndexed
dcl_constantbuffer CB1[3], immediateIndexed
dcl_constantbuffer CB2[14], immediateIndexed
dcl_resource_structured t0, 12
dcl_resource_structured t1, 12
dcl_uav_structured u0, 72
dcl_input vThreadID.x
dcl_temps 29
dcl_thread_group 1, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 212 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_ComputeFXEffect_b1196ba0444b1d4473de5464cbb2f8a1.hlsl"
bufinfo_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.x, t0.xyzw  // r0.x <- count
bufinfo_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.y, t1.yxzw  // r0.y <- count

#line 218
umin r0.x, r0.y, r0.x  // r0.x <- n

#line 221
ult r0.x, vThreadID.x, r0.x
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t0.xyzx
  mov r0.w, l(1.000000)
  dp4 r1.x, r0.xyzw, cb0[2].xyzw  // r1.x <- from.x
  dp4 r1.y, r0.xyzw, cb0[3].xyzw  // r1.y <- from.y
  dp4 r1.z, r0.xyzw, cb0[4].xyzw  // r1.z <- from.z

#line 222
  ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.xyz, vThreadID.x, l(0), t1.xyzx
  mov r0.w, l(1.000000)
  dp4 r2.x, r0.xyzw, cb0[2].xyzw  // r2.x <- to.x
  dp4 r2.y, r0.xyzw, cb0[3].xyzw  // r2.y <- to.y
  dp4 r2.z, r0.xyzw, cb0[4].xyzw  // r2.z <- to.z

#line 223
  add r0.xyz, -r1.xyzx, r2.xyzx  // r0.x <- t.x; r0.y <- t.y; r0.z <- t.z

#line 227
  mov r3.x, cb2[4].w
  mov r3.y, cb2[5].w
  mov r3.z, cb2[6].w
  add r4.xyz, -r1.xyzx, r3.xyzx  // r4.x <- fromViewDir.x; r4.y <- fromViewDir.y; r4.z <- fromViewDir.z

#line 228
  add r3.xyz, -r2.xyzx, r3.xyzx  // r3.x <- toViewDir.x; r3.y <- toViewDir.y; r3.z <- toViewDir.z

#line 239
  ieq r1.w, cb0[1].x, l(1)

#line 231
  mov r5.x, cb2[4].z
  mov r5.y, cb2[5].z
  mov r5.z, cb2[6].z
  dp3 r6.x, r5.xyzx, r4.xyzx

#line 232
  mov r6.yw, l(0,1.000000,0,1.000000)

#line 231
  dp4 r2.w, r6.xxxy, cb2[13].xyzw
  mul r2.w, r2.w, l(0.200000)
  movc r2.w, r1.w, r2.w, l(1.000000)  // r2.w <- fromScale

#line 232
  dp3 r6.z, r5.xyzx, r3.xyzx
  dp4 r3.w, r6.zzzw, cb2[13].xyzw
  mul r3.w, r3.w, l(0.200000)
  movc r1.w, r1.w, r3.w, l(1.000000)  // r1.w <- toScale

#line 233
  mul r2.w, r2.w, cb1[2].w

#line 234
  mul r1.w, r1.w, cb1[2].w

#line 239
  if_z cb0[1].y

#line 235
    dp3 r3.w, r4.xyzx, r4.xyzx
    rsq r3.w, r3.w
    mul r4.xyz, r3.wwww, r4.xyzx

#line 236
    dp3 r3.w, r3.xyzx, r3.xyzx
    rsq r3.w, r3.w
    mul r3.xyz, r3.wwww, r3.xyzx

#line 241
    movc r4.xyz, cb0[6].yyyy, r4.xyzx, cb1[1].xyzx
    movc r3.xyz, cb0[6].yyyy, r3.xyzx, cb1[1].xyzx

#line 117
    mul r5.xyz, r0.zxyz, r4.yzxy
    mad r5.xyz, r0.yzxy, r4.zxyz, -r5.xyzx
    dp3 r3.w, r5.xyzx, r5.xyzx
    rsq r3.w, r3.w
    mul r6.xyz, r3.wwww, r5.xyzx  // r6.x <- dir.x; r6.y <- dir.y; r6.z <- dir.z

#line 118
    mul r7.xyz, r0.zxyz, r3.yzxy
    mad r7.xyz, r0.yzxy, r3.zxyz, -r7.xyzx
    dp3 r4.w, r7.xyzx, r7.xyzx
    rsq r4.w, r4.w
    mul r8.xyz, r4.wwww, r7.xyzx  // r8.x <- dirNext.x; r8.y <- dirNext.y; r8.z <- dirNext.z

#line 119
    mul r9.xyz, r6.xyzx, cb0[0].wwww
    mul r9.xyz, r2.wwww, r9.xyzx
    mad r10.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r10.x <- v0.Position.x; r10.y <- v0.Position.y; r10.z <- v0.Position.z

#line 120
    mul r11.xyz, r8.xyzx, cb0[0].wwww
    mul r11.xyz, r1.wwww, r11.xyzx
    mad r12.xyz, r11.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xyzx  // r12.x <- v1.Position.x; r12.y <- v1.Position.y; r12.z <- v1.Position.z

#line 121
    mad r9.xyz, -r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r9.x <- v2.Position.x; r9.y <- v2.Position.y; r9.z <- v2.Position.z

#line 122
    mad r11.xyz, -r11.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xyzx  // r11.x <- v3.Position.x; r11.y <- v3.Position.y; r11.z <- v3.Position.z

#line 123
    movc r5.w, cb0[6].z, l(0.500000), l(1.000000)  // r5.w <- t

#line 124
    mad r13.xyz, -r5.xyzx, r3.wwww, r4.xyzx
    mad r13.xyz, r5.wwww, r13.xyzx, r6.xyzx
    dp3 r6.w, r13.xyzx, r13.xyzx
    rsq r6.w, r6.w
    mul r13.xyz, r6.wwww, r13.yzxy  // r13.x <- v0.Normal.y; r13.y <- v0.Normal.z; r13.z <- v0.Normal.x

#line 125
    mad r14.xyz, -r7.xyzx, r4.wwww, r3.xyzx
    mad r14.xyz, r5.wwww, r14.xyzx, r8.xyzx
    dp3 r6.w, r14.xyzx, r14.xyzx
    rsq r6.w, r6.w
    mul r14.xyz, r6.wwww, r14.yzxy  // r14.x <- v1.Normal.y; r14.y <- v1.Normal.z; r14.z <- v1.Normal.x

#line 126
    mad r4.xyz, r5.xyzx, r3.wwww, r4.xyzx
    mad r4.xyz, r5.wwww, r4.xyzx, -r6.xyzx
    dp3 r3.w, r4.xyzx, r4.xyzx
    rsq r3.w, r3.w
    mul r6.xyz, r3.wwww, r4.yzxy  // r6.x <- v2.Normal.y; r6.y <- v2.Normal.z; r6.z <- v2.Normal.x

#line 127
    mad r3.xyz, r7.xyzx, r4.wwww, r3.xyzx
    mad r3.xyz, r5.wwww, r3.xyzx, -r8.xyzx
    dp3 r3.w, r3.xyzx, r3.xyzx
    rsq r3.w, r3.w
    mul r3.xyz, r3.wwww, r3.yzxy  // r3.x <- v3.Normal.y; r3.y <- v3.Normal.z; r3.z <- v3.Normal.x

#line 133
    utof r4.x, vThreadID.x
    mul r4.z, r4.x, l(0.500000)  // r4.z <- v0.TexCoord.x

#line 134
    iadd r5.x, vThreadID.x, l(1)
    utof r5.x, r5.x
    mul r5.z, r5.x, l(0.500000)  // r5.z <- v1.TexCoord.x

#line 140
    imul null, r7.x, vThreadID.x, l(6)
    mov r9.w, r6.z
    store_structured u0.xyzw, r7.x, l(0), r9.xyzw
    mov r6.zw, cb1[0].xxxy
    store_structured u0.xyzw, r7.x, l(16), r6.xyzw
    mov r4.xy, cb1[0].zwzz
    mov r4.w, l(0)
    store_structured u0.xyzw, r7.x, l(32), r4.xyzw
    mov r0.w, l(-1.000000)
    store_structured u0.xyzw, r7.x, l(48), r0.xyzw

#line 141
    mov r8.xz, vThreadID.xxxx
    mov r8.yw, l(0,0,0,1)

#line 140
    store_structured u0.xy, r7.x, l(64), r8.xyxx

#line 141
    imad r7.y, vThreadID.x, l(6), l(1)
    mov r12.w, r14.z
    store_structured u0.xyzw, r7.y, l(0), r12.xyzw
    mov r14.zw, cb1[0].xxxy
    store_structured u0.xyzw, r7.y, l(16), r14.xyzw
    mov r5.xy, cb1[0].zwzz
    mov r5.w, l(1.000000)
    store_structured u0.xyzw, r7.y, l(32), r5.xyzw
    store_structured u0.xyzw, r7.y, l(48), r0.xyzw
    store_structured u0.xy, r7.y, l(64), r8.zwzz

#line 145
    imad r15.xyzw, vThreadID.xxxx, l(6, 6, 6, 6), l(2, 3, 4, 5)

#line 142
    mov r10.w, r13.z
    store_structured u0.xyzw, r15.x, l(0), r10.xyzw
    mov r13.zw, cb1[0].xxxy
    store_structured u0.xyzw, r15.x, l(16), r13.xyzw
    mov r10.xyw, r5.xyxw
    mov r10.z, r4.z
    store_structured u0.xyzw, r15.x, l(32), r10.xyzw
    store_structured u0.xyzw, r15.x, l(48), r0.xyzw
    store_structured u0.xy, r15.x, l(64), r8.xyxx

#line 143
    store_structured u0.xyzw, r15.y, l(0), r9.xyzw
    store_structured u0.xyzw, r15.y, l(16), r6.xyzw
    store_structured u0.xyzw, r15.y, l(32), r4.xyzw
    store_structured u0.xyzw, r15.y, l(48), r0.xyzw
    store_structured u0.xy, r15.y, l(64), r8.xyxx

#line 144
    mov r11.w, r3.z
    store_structured u0.xyzw, r15.z, l(0), r11.xyzw
    mov r3.zw, cb1[0].xxxy
    store_structured u0.xyzw, r15.z, l(16), r3.xyzw
    mov r3.xyz, r5.xyzx
    mov r3.w, l(0)
    store_structured u0.xyzw, r15.z, l(32), r3.xyzw
    store_structured u0.xyzw, r15.z, l(48), r0.xyzw
    store_structured u0.xy, r15.z, l(64), r8.zwzz

#line 145
    store_structured u0.xyzw, r15.w, l(0), r12.xyzw
    store_structured u0.xyzw, r15.w, l(16), r14.xyzw
    store_structured u0.xyzw, r15.w, l(32), r5.xyzw
    store_structured u0.xyzw, r15.w, l(48), r0.xyzw
    store_structured u0.xy, r15.w, l(64), r8.zwzz

#line 242
  else   // Prior locations: r4.x <- fromViewDir.x; r4.y <- fromViewDir.y; r4.z <- fromViewDir.z; r3.x <- toViewDir.x; r3.y <- toViewDir.y; r3.z <- toViewDir.z

#line 154
    mul r3.xyz, r0.xyzx, cb1[2].zxyz
    mad r3.xyz, r0.zxyz, cb1[2].xyzx, -r3.xyzx
    mul r4.xyz, r0.zxyz, r3.xyzx
    mad r3.xyz, r0.yzxy, r3.yzxy, -r4.xyzx
    dp3 r3.w, r3.xyzx, r3.xyzx
    rsq r3.w, r3.w
    mul r3.xyz, r3.wwww, r3.xyzx  // r3.x <- dir.x; r3.y <- dir.y; r3.z <- dir.z

#line 156
    dp3 r3.w, r0.xyzx, r0.xyzx
    rsq r3.w, r3.w
    mul r4.xyz, r0.zxyz, r3.wwww
    itof r3.w, cb0[6].x
    div r4.w, l(6.283185), r3.w

#line 107
    sincos r5.x, r6.x, r4.w  // r6.x <- c; r5.x <- s

#line 108
    add r4.w, -r6.x, l(1.000000)  // r4.w <- t

#line 112
    mul r7.xyzw, r4.yyyz, r4.wwww
    mul r5.xyz, r4.xyzx, r5.xxxx
    mad r8.xy, r7.zyzz, r4.xzxx, r5.zxzz  // r8.x <- <rot3D_id50 return value>._m02; r8.y <- <rot3D_id50 return value>._m10
    mad r9.xy, r7.xwxx, r4.yzyy, r6.xxxx  // r9.x <- <rot3D_id50 return value>._m00; r9.y <- <rot3D_id50 return value>._m11
    mad r8.z, r7.w, r4.x, -r5.y  // r8.z <- <rot3D_id50 return value>._m12
    mad r10.xy, r7.yzyy, r4.zxzz, -r5.xzxx  // r10.x <- <rot3D_id50 return value>._m01; r10.y <- <rot3D_id50 return value>._m20
    mad r10.z, r7.w, r4.x, r5.y  // r10.z <- <rot3D_id50 return value>._m21
    mul r4.x, r4.x, r4.x
    mad r8.w, r4.x, r4.w, r6.x  // r8.w <- <rot3D_id50 return value>._m22

#line 158
    mul r4.xyz, r3.xyzx, cb0[0].wwww
    mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    mad r5.xyz, r4.xyzx, r2.wwww, r1.xyzx  // r5.x <- v0.Position.x; r5.y <- v0.Position.y; r5.z <- v0.Position.z

#line 159
    mad r4.xyz, r4.xyzx, r1.wwww, r2.xyzx  // r4.x <- v1.Position.x; r4.y <- v1.Position.y; r4.z <- v1.Position.z

#line 165
    div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w  // r3.w <- divY

#line 166
    utof r4.w, vThreadID.x
    mul r6.z, r4.w, l(0.500000)  // r6.z <- v0.TexCoord.x

#line 167
    iadd r4.w, vThreadID.x, l(1)
    utof r4.w, r4.w
    mul r7.z, r4.w, l(0.500000)  // r7.z <- v1.TexCoord.x

#line 184
    imul null, r4.w, vThreadID.x, cb0[6].x

#line 176
    mov r9.z, r8.y
    mov r9.w, r10.y
    mov r10.w, r9.y

#line 185
    mov r11.zw, cb1[0].xxxy
    mov r6.xy, cb1[0].zwzz
    mov r0.w, l(-1.000000)

#line 186
    mov r12.zw, cb1[0].xxxy
    mov r13.xy, cb1[0].zwzz
    mov r14.xz, vThreadID.xxxx
    mov r14.yw, l(0,0,0,1)

#line 187
    mov r15.zw, cb1[0].xxxy
    mov r16.xy, cb1[0].zwzz

#line 189
    mov r17.zw, cb1[0].xxxy

#line 172
    mov r18.xyz, r5.xyzx  // r18.x <- v0.Position.x; r18.y <- v0.Position.y; r18.z <- v0.Position.z
    mov r18.w, r6.z  // r18.w <- v0.TexCoord.x
    mov r19.x, l(0)  // r19.x <- v0.TexCoord.y
    mov r19.yzw, r4.xxyz  // r19.y <- v1.Position.x; r19.z <- v1.Position.y; r19.w <- v1.Position.z
    mov r20.xyz, r3.xyzx  // r20.x <- dir.x; r20.y <- dir.y; r20.z <- dir.z
    mov r21.xyz, r3.xyzx  // r21.x <- dirNext.x; r21.y <- dirNext.y; r21.z <- dirNext.z
    mov r13.z, r7.z  // r13.z <- v1.TexCoord.x
    mov r13.w, l(0)  // r13.w <- v1.TexCoord.y
    mov r5.w, l(0)  // r5.w <- i
    loop 
      uge r8.y, r5.w, cb0[6].x
      breakc_nz r8.y

#line 176
      dp3 r22.x, r20.xyzx, r9.xzwx  // r22.x <- dir.x
      dp3 r22.y, r20.xzyx, r10.xzwx  // r22.y <- dir.y
      dp3 r22.z, r20.xyzx, r8.xzwx  // r22.z <- dir.z

#line 177
      dp3 r23.x, r21.xyzx, r9.xzwx  // r23.x <- dirNext.x
      dp3 r23.y, r21.xzyx, r10.xzwx  // r23.y <- dirNext.y
      dp3 r23.z, r21.xyzx, r8.xzwx  // r23.z <- dirNext.z

#line 178
      mul r24.xyz, r22.xyzx, cb0[0].wwww
      mul r24.xyz, r2.wwww, r24.xyzx
      mad r24.xyz, r24.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx  // r24.x <- v2.Position.x; r24.y <- v2.Position.y; r24.z <- v2.Position.z

#line 179
      mul r25.xyz, r23.xyzx, cb0[0].wwww
      mul r25.xyz, r1.wwww, r25.xyzx
      mad r25.xyz, r25.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xyzx  // r25.x <- v3.Position.x; r25.y <- v3.Position.y; r25.z <- v3.Position.z

#line 182
      iadd r8.y, r5.w, l(1)
      utof r9.y, r8.y
      mul r6.w, r3.w, r9.y  // r6.w <- v2.TexCoord.y

#line 184
      imul null, r9.y, r5.w, l(6)
      imad r9.y, r4.w, l(6), r9.y  // r9.y <- offset

#line 185
      mov r24.w, r22.x
      store_structured u0.xyzw, r9.y, l(0), r24.xyzw
      mov r11.xy, r22.yzyy
      store_structured u0.xyzw, r9.y, l(16), r11.xyzw
      store_structured u0.xyzw, r9.y, l(32), r6.xyzw
      store_structured u0.xyzw, r9.y, l(48), r0.xyzw
      store_structured u0.xy, r9.y, l(64), r14.xyxx

#line 186
      iadd r10.y, r9.y, l(1)
      mov r26.xyz, r19.yzwy
      mov r26.w, r21.x
      store_structured u0.xyzw, r10.y, l(0), r26.xyzw
      mov r12.xy, r21.yzyy
      store_structured u0.xyzw, r10.y, l(16), r12.xyzw
      store_structured u0.xyzw, r10.y, l(32), r13.xyzw
      store_structured u0.xyzw, r10.y, l(48), r0.xyzw
      store_structured u0.xy, r10.y, l(64), r14.zwzz

#line 190
      iadd r27.xyzw, r9.yyyy, l(2, 3, 4, 5)

#line 187
      mov r28.xyz, r18.xyzx
      mov r28.w, r20.x
      store_structured u0.xyzw, r27.x, l(0), r28.xyzw
      mov r15.xy, r20.yzyy
      store_structured u0.xyzw, r27.x, l(16), r15.xyzw
      mov r16.z, r18.w
      mov r16.w, r19.x
      store_structured u0.xyzw, r27.x, l(32), r16.xyzw
      store_structured u0.xyzw, r27.x, l(48), r0.xyzw
      store_structured u0.xy, r27.x, l(64), r14.xyxx

#line 188
      store_structured u0.xyzw, r27.y, l(0), r24.xyzw
      store_structured u0.xyzw, r27.y, l(16), r11.xyzw
      store_structured u0.xyzw, r27.y, l(32), r6.xyzw
      store_structured u0.xyzw, r27.y, l(48), r0.xyzw
      store_structured u0.xy, r27.y, l(64), r14.xyxx

#line 189
      mov r25.w, r23.x
      store_structured u0.xyzw, r27.z, l(0), r25.xyzw
      mov r17.xy, r23.yzyy
      store_structured u0.xyzw, r27.z, l(16), r17.xyzw
      mov r7.xyw, r6.xyxw
      store_structured u0.xyzw, r27.z, l(32), r7.xyzw
      store_structured u0.xyzw, r27.z, l(48), r0.xyzw
      store_structured u0.xy, r27.z, l(64), r14.zwzz

#line 190
      store_structured u0.xyzw, r27.w, l(0), r26.xyzw
      store_structured u0.xyzw, r27.w, l(16), r12.xyzw
      store_structured u0.xyzw, r27.w, l(32), r13.xyzw
      store_structured u0.xyzw, r27.w, l(48), r0.xyzw
      store_structured u0.xy, r27.w, l(64), r14.zwzz

#line 195
      mov r18.xyz, r24.xyzx
      mov r18.w, r6.z
      mov r19.x, r7.w
      mov r19.yzw, r25.xxyz
      mov r20.xyz, r22.xyzx  // r20.x <- dir.x; r20.y <- dir.y; r20.z <- dir.z
      mov r21.xyz, r23.xyzx  // r21.x <- dirNext.x; r21.y <- dirNext.y; r21.z <- dirNext.z
      mov r13.zw, r7.zzzw
      mov r5.w, r8.y
    endloop 

#line 246
  endif 
endif 

#line 261
ret 
// Approximately 275 instruction slots used
***************************
*************************/
static const float PI_id34 = 3.1415926535897;
static const float TWOPI_id37 = 6.28318531;
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
    float3 LinePosition_id31;
    uint LineId_id32;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct Matrix4x4 
{
    float4x4 Matrix;
};
struct Ray 
{
    float3 ro, rd, sp, sn;
};
struct LineAttribute 
{
    float w;
    float4 c;
};
struct LineInfo 
{
    int id;
    int start;
    int count;
};
struct Pos3Norm3Col4Tex2 
{
    float3 Position;
    float3 Normal;
    float4 Color;
    float2 TexCoord;
};
struct Pos3Norm3Col4Tex2Tan4Id2 
{
    float3 Position;
    float3 Normal;
    float4 Color;
    float2 TexCoord;
    float4 Tangent;
    uint LineId;
    uint SegmentId;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    float Radius_id46 = .15;
    int ThicknessSpace_id47 = 0;
    int MeshType_id48 = 0;
    float4x4 Transform_id49;
    int Resolution_id50;
    bool ViewAlign_id51;
    bool NormalBend_id52;
};
cbuffer PerDraw 
{
    float4x4 World_id18;
    float4x4 WorldInverse_id19;
    float4x4 WorldInverseTranspose_id20;
    float4x4 WorldView_id21;
    float4x4 WorldViewInverse_id22;
    float4x4 WorldViewProjection_id23;
    float3 WorldScale_id24;
    float4 EyeMS_id25;
};
cbuffer PerUpdate 
{
    float4 InputValue_id57;
    float3 InputValue_id58;
    float3 InputValue_id59;
    float InputValue_id60;
};
cbuffer PerView 
{
    float4x4 View_id11;
    float4x4 ViewInverse_id12;
    float4x4 Projection_id13;
    float4x4 ProjectionInverse_id14;
    float4x4 ViewProjection_id15;
    float2 ProjScreenRay_id16;
    float4 Eye_id17;
    float NearClipPlane_id26 = 1.0f;
    float FarClipPlane_id27 = 100.0f;
    float2 ZProjection_id28;
    float2 ViewSize_id29;
    float AspectRatio_id30;
};
StructuredBuffer<float3> FromBuffer_id43;
StructuredBuffer<float3> ToBuffer_id44;
RWStructuredBuffer<Pos3Norm3Col4Tex2Tan4Id2> outputBuffer_id45;
float3x3 rot3D_id50(float3 axis, float angle)
{
    float c, s;
    sincos(angle, s, c);
    float t = 1 - c;
    float x = axis.x;
    float y = axis.y;
    float z = axis.z;
    return float3x3(t * x * x + c, t * x * y - s * z, t * x * z + s * y, t * x * y + s * z, t * y * y + c, t * y * z - s * x, t * x * z - s * y, t * y * z + s * x, t * z * z + c);
}
void FlatMeshLine_id51(RWStructuredBuffer<Pos3Norm3Col4Tex2Tan4Id2> outputBuffer, uint id, float3 pos, float3 tan, float scale, float4 color, float3 posNext, float3 tanNext, float scaleNext, float4 colorNext, float radius, int sampleCnt, bool normalBend, float3 up = float3(0, 1, 0), float3 upNext = float3(0, 1, 0))
{
    Pos3Norm3Col4Tex2Tan4Id2 v0, v1, v2, v3;
    float3 dir = normalize(cross(tan, up));
    float3 dirNext = normalize(cross(tanNext, upNext));
    v0.Position = pos + dir * radius * .5 * scale;
    v1.Position = posNext + dirNext * radius * .5 * scaleNext;
    v2.Position = pos - dir * radius * .5 * scale;
    v3.Position = posNext - dirNext * radius * .5 * scaleNext;
    float t = normalBend ? .5 : 1;
    v0.Normal = normalize(lerp(dir, up, t));
    v1.Normal = normalize(lerp(dirNext, upNext, t));
    v2.Normal = normalize(lerp(-dir, up, t));
    v3.Normal = normalize(lerp(-dirNext, upNext, t));
    v0.Color = v2.Color = color;
    v1.Color = v3.Color = colorNext;
    v0.Tangent = v2.Tangent = float4(tan, -1);
    v1.Tangent = v3.Tangent = float4(tanNext, -1);
    float div = 1.0 / sampleCnt;
    v0.TexCoord = float2(div * id, 1);
    v1.TexCoord = float2(div * (id + 1), 1);
    v2.TexCoord = float2(div * id, 0);
    v3.TexCoord = float2(div * (id + 1), 0);
    v0.LineId = v1.LineId = v2.LineId = v3.LineId = id;
    v0.SegmentId = v2.SegmentId = 0;
    v1.SegmentId = v3.SegmentId = 1;
    outputBuffer[id * 6 + 0] = v2;
    outputBuffer[id * 6 + 1] = v1;
    outputBuffer[id * 6 + 2] = v0;
    outputBuffer[id * 6 + 3] = v2;
    outputBuffer[id * 6 + 4] = v3;
    outputBuffer[id * 6 + 5] = v1;
}
float3 Compute_id59()
{
    return InputValue_id58;
}
void TubeMeshLine_id53(RWStructuredBuffer<Pos3Norm3Col4Tex2Tan4Id2> outputBuffer, uint id, float3 pos, float3 tan, float scale, float4 color, float3 posNext, float3 tanNext, float scaleNext, float4 colorNext, float radius, int sampleCnt, int resolution, float3 up = float3(0, 1, 0))
{
    Pos3Norm3Col4Tex2Tan4Id2 v0, v1, v2, v3;
    float3 dir = normalize(cross(tan, cross(tan, up)));
    float3 dirNext = normalize(cross(tanNext, cross(tanNext, up)));
    float3x3 r = rot3D_id50(normalize(tan), TWOPI_id37 / resolution);
    float3x3 rNext = rot3D_id50(normalize(tanNext), TWOPI_id37 / resolution);
    v0.Position = pos + dir * radius * .5 * scale;
    v1.Position = posNext + dirNext * radius * .5 * scaleNext;
    v0.Color = v2.Color = color;
    v1.Color = v3.Color = colorNext;
    v0.Tangent = v2.Tangent = float4(tan, -1);
    v1.Tangent = v3.Tangent = float4(tanNext, -1);
    float divX = 1.0 / (float)sampleCnt;
    float divY = 1.0 / resolution;
    v0.TexCoord = float2(divX * id, 0);
    v1.TexCoord = float2(divX * (id + 1), 0);
    v0.LineId = v1.LineId = v2.LineId = v3.LineId = id;
    v0.SegmentId = v2.SegmentId = 0;
    v1.SegmentId = v3.SegmentId = 1;

    for (uint i = 0; i < resolution; i++)
    {
        v0.Normal = dir;
        v1.Normal = dirNext;
        dir = mul(dir, r);
        dirNext = mul(dirNext, rNext);
        v2.Position = pos + dir * radius * .5 * scale;
        v3.Position = posNext + dirNext * radius * .5 * scaleNext;
        v2.Normal = dir;
        v3.Normal = dirNext;
        v2.TexCoord = float2(divX * id, divY * (i + 1));
        v3.TexCoord = float2(divX * (id + 1), divY * (i + 1));
        uint offset = id * 6 * resolution + 6 * i;
        outputBuffer[offset + 0] = v2;
        outputBuffer[offset + 1] = v1;
        outputBuffer[offset + 2] = v0;
        outputBuffer[offset + 3] = v2;
        outputBuffer[offset + 4] = v3;
        outputBuffer[offset + 5] = v1;
        v0.Position = v2.Position;
        v1.Position = v3.Position;
        v0.TexCoord = v2.TexCoord;
        v1.TexCoord = v3.TexCoord;
    }
}
float3 Compute_id58()
{
    return InputValue_id59;
}
float4 Compute_id57()
{
    return InputValue_id57;
}
float Compute_id56()
{
    return InputValue_id60;
}
uint sbSize3_id5(StructuredBuffer<float3> sBuffer)
{
    uint count, dummy;
    sBuffer.GetDimensions(count, dummy);
    return count;
}
void Compute_id55(inout CS_STREAMS streams)
{
    uint dtid = streams.DispatchThreadId_id1.x;
    uint n = min(sbSize3_id5(FromBuffer_id43), sbSize3_id5(ToBuffer_id44));
    if (dtid >= n)
        return;
    float3 from = mul(float4(FromBuffer_id43[dtid], 1), Transform_id49).xyz;
    float3 to = mul(float4(ToBuffer_id44[dtid], 1), Transform_id49).xyz;
    float3 t = to - from;
    streams.LinePosition_id31 = (from + to) * .5;
    streams.LineId_id32 = dtid;
    float3 viewFront = ViewInverse_id12[2].xyz;
    float3 fromViewDir = ViewInverse_id12[3].xyz - from;
    float3 toViewDir = ViewInverse_id12[3].xyz - to;
    float width = Compute_id56();
    float4 color = Compute_id57();
    float fromScale = ThicknessSpace_id47 == 1 ? mul(float4(dot(viewFront, fromViewDir).xxx, 1.0), ProjectionInverse_id14).y * .2 : 1;
    float toScale = ThicknessSpace_id47 == 1 ? mul(float4(dot(viewFront, toViewDir).xxx, 1.0), ProjectionInverse_id14).y * .2 : 1;
    fromScale *= width;
    toScale *= width;
    fromViewDir = normalize(fromViewDir);
    toViewDir = normalize(toViewDir);
    float3 fromDir = normalize(cross(t, fromViewDir));
    float3 toDir = normalize(cross(t, toViewDir));
    if (MeshType_id48 == 0)
    {
        FlatMeshLine_id51(outputBuffer_id45, dtid, from, t, fromScale, color, to, t, toScale, color, Radius_id46, 2, NormalBend_id52, ViewAlign_id51 ? normalize(fromViewDir) : Compute_id59(), ViewAlign_id51 ? normalize(toViewDir) : Compute_id59());
    }
    else
    {
        TubeMeshLine_id53(outputBuffer_id45, dtid, from, t, fromScale, color, to, t, toScale, color, Radius_id46, 2, Resolution_id50, Compute_id58());
    }
}
[numthreads(1, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 1;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 1 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id55(streams);
}
