/**************************
***** Compiler Parameters *****
***************************
@P EffectName: TextureFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin Metallica_TextureFX [{Control = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}]
@P Control: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer PerUpdate [Size: 16]
@C    InputValue_id97 => ShaderFX.InputValueFloat4
cbuffer PerView [Size: 32]
@C    NearClipPlane_id74 => Camera.NearClipPlane
@C    FarClipPlane_id75 => Camera.FarClipPlane
@C    ZProjection_id76 => Camera.ZProjection
@C    ViewSize_id77 => Camera.ViewSize
@C    AspectRatio_id78 => Camera.AspectRatio
cbuffer Globals [Size: 160]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
@C    ColorA_id88 => Metallica_TextureFX.ColorA
@C    ColorB_id89 => Metallica_TextureFX.ColorB
@C    Angle_id90 => Metallica_TextureFX.Angle
@C    BumpAmount_id91 => Metallica_TextureFX.BumpAmount
@C    BumpGamma_id92 => Metallica_TextureFX.BumpGamma
@C    Brightness_id93 => Metallica_TextureFX.Brightness
@C    Emboss_id94 => Metallica_TextureFX.Emboss
@C    Shape_id95 => Metallica_TextureFX.Shape
@C    MaxRadius_id96 => Metallica_TextureFX.MaxRadius
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Sampler0_id52 => Texturing.Sampler0 [Stage: Pixel, Slot: (0-0)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    PerUpdate => PerUpdate [Stage: Pixel, Slot: (0-0)]
@R    PerView => PerView [Stage: Pixel, Slot: (1-1)]
@R    Globals => Globals [Stage: Pixel, Slot: (2-2)]
***************************
*****     Sources     *****
***************************
@S    Metallica_TextureFX => d49a34ce929f126dfc1df23b1ca57708
@S    FilterBase => 5bd9cb7e7eb80aa436e148c74d845c07
@S    TextureFX => 27bb4f1f808a5eedf6dfeaa75c669c29
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    Camera => f5d1a113ef7a27319900e8cc2e11ae0d
@S    ShaderUtils => 27e27e08e991883f970444d1aebe3b58
@S    ComputeFloat4 => bc345c7d961ff4b1766c5b1d5e15bd5a
@S    InputFloat4 => f6891eacc9ea2d912dcfded49ea96a71
@S    DeclFloat4 => 03cb445d0e450d0a37ad5f24c8a93feb
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 214 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_b81886a450be06b56ac03d1a9670ec89.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 218
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 9c05b3ab873634b9569fd9a5623d83da
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerUpdate
// {
//
//   float4 InputValue_id97;            // Offset:    0 Size:    16
//
// }
//
// cbuffer PerView
// {
//
//   float NearClipPlane_id74;          // Offset:    0 Size:     4 [unused]
//      = 0x3f800000 
//   float FarClipPlane_id75;           // Offset:    4 Size:     4 [unused]
//      = 0x42c80000 
//   float2 ZProjection_id76;           // Offset:    8 Size:     8 [unused]
//   float2 ViewSize_id77;              // Offset:   16 Size:     8
//   float AspectRatio_id78;            // Offset:   24 Size:     4 [unused]
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//   float4 ColorA_id88;                // Offset:   80 Size:    16
//      = 0x3f19999a 0x3f7d70a4 0x3f75c28f 0x3f800000 
//   float4 ColorB_id89;                // Offset:   96 Size:    16
//      = 0x3f11eb85 0x3ed1eb85 0x3d8f5c29 0x3f800000 
//   float2 Angle_id90;                 // Offset:  112 Size:     8
//      = 0x00000000 0x00000000 
//   float2 BumpAmount_id91;            // Offset:  120 Size:     8
//      = 0x3f800000 0x3f800000 
//   float2 BumpGamma_id92;             // Offset:  128 Size:     8
//      = 0x00000000 0x00000000 
//   float2 Brightness_id93;            // Offset:  136 Size:     8
//      = 0x00000000 0x00000000 
//   float Emboss_id94;                 // Offset:  144 Size:     4
//      = 0x3f800000 
//   float Shape_id95;                  // Offset:  148 Size:     4
//      = 0x00000000 
//   float MaxRadius_id96;              // Offset:  152 Size:     4
//      = 0x3f800000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Sampler0_id52                     sampler      NA          NA             s0      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// PerUpdate                         cbuffer      NA          NA            cb0      1 
// PerView                           cbuffer      NA          NA            cb1      1 
// Globals                           cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB1[2], immediateIndexed
dcl_constantbuffer CB2[10], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 8
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 193 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_TextureFXEffect_b81886a450be06b56ac03d1a9670ec89.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r0.x <- <InTex0_id26 return value>.x; r0.y <- <InTex0_id26 return value>.y; r0.z <- <InTex0_id26 return value>.z; r0.w <- <InTex0_id26 return value>.w

#line 165
max r1.x, cb1[1].y, cb1[1].x
log r1.y, r1.x  // r1.y <- lod

#line 168
mad r1.z, -cb2[9].z, r1.y, l(1.000000)
add r1.z, -r1.z, r1.y
min r1.z, r1.z, l(14.000000)

#line 175
div r2.xy, cb1[1].xxxx, cb1[1].xyxx
sqrt r2.xy, r2.xyxx

#line 168
mov r2.zw, l(0,0,0,0)  // r2.z <- col.x; r2.w <- col.y
mov r1.w, l(0)  // r1.w <- col.z
mov r3.xy, l(0,0,0,0)  // r3.x <- kk; r3.y <- i
loop 
  ge r3.z, r3.y, r1.z
  breakc_nz r3.z

#line 170
  exp r3.z, r3.y
  div r3.z, r3.z, r1.x  // r3.z <- off.x

#line 172
  mad r3.w, r3.y, cb2[9].y, -r1.y
  exp r3.w, r3.w
  div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  mad_sat r4.x, cb2[9].z, r1.y, -r3.y
  mul r4.y, r3.w, r4.x  // r4.y <- k

#line 174
  mad r5.xyzw, -r3.zzzz, l(0.500000, 0.000000, 0.000000, 0.500000), v1.xyxy

#line 173
  sample_l_indexable(texture2d)(float,float,float,float) r6.xyz, r5.xyxx, t0.xyzw, s0, r3.y

#line 154
  max r4.z, r6.z, r6.y
  max r4.z, r4.z, r6.x  // r4.z <- <mx_id29 return value>

#line 174
  mad r6.xyzw, r3.zzzz, l(0.500000, 0.000000, 0.000000, 0.500000), v1.xyxy

#line 173
  sample_l_indexable(texture2d)(float,float,float,float) r7.xyz, r6.xyxx, t0.xyzw, s0, r3.y

#line 154
  max r3.z, r7.z, r7.y
  max r3.z, r3.z, r7.x  // r3.z <- <mx_id29 return value>

#line 173
  add r5.x, -r3.z, r4.z  // r5.x <- dx

#line 174
  sample_l_indexable(texture2d)(float,float,float,float) r7.xyz, r5.zwzz, t0.xyzw, s0, r3.y

#line 154
  max r3.z, r7.z, r7.y
  max r3.z, r3.z, r7.x  // r3.z <- <mx_id29 return value>

#line 174
  sample_l_indexable(texture2d)(float,float,float,float) r6.xyz, r6.zwzz, t0.xyzw, s0, r3.y

#line 154
  max r4.z, r6.z, r6.y
  max r4.z, r4.z, r6.x  // r4.z <- <mx_id29 return value>

#line 174
  add r5.y, r3.z, -r4.z  // r5.y <- dy

#line 175
  mul r4.zw, r2.xxxy, r5.xxxy
  mad r2.zw, r4.zzzw, r4.yyyy, r2.zzzw

#line 176
  mul r4.yz, r4.yyyy, r5.xxyx
  dp2 r3.z, r4.yzyy, r4.yzyy
  sqrt r3.z, r3.z
  add r1.w, r1.w, r3.z

#line 177
  mad r3.x, r3.w, r4.x, r3.x

#line 178
  add r3.y, r3.y, l(1.000000)
endloop 

#line 179
mul r1.x, |r1.w|, l(0.100000)
log r1.x, r1.x
mul r1.x, r1.x, l(0.300000)
exp r1.x, r1.x
mad r1.x, r1.x, l(10.000000), l(0.000000)
div r1.xy, r2.zwzz, r1.xxxx  // r1.x <- col.x; r1.y <- col.y

#line 180
log r1.z, |r3.x|
mul r1.z, r1.z, l(0.700000)
exp r1.z, r1.z
div r1.z, cb2[9].x, r1.z
mul r1.z, r1.z, l(8.000000)  // r1.z <- dd

#line 182
mul r1.xy, r1.zzzz, r1.xyxx

#line 185
lt r1.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r1.xxxy
lt r2.xy, r1.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r1.zw, -r1.zzzw, r2.xxxy
itof r1.zw, r1.zzzw
min r2.xy, |r1.xyxx|, l(1.000000, 1.000000, 0.000000, 0.000000)
mad r2.zw, r2.xxxy, l(0.000000, 0.000000, -2.000000, -2.000000), l(0.000000, 0.000000, 3.000000, 3.000000)
mul r2.xy, r2.xyxx, r2.xyxx
mul r2.xy, r2.xyxx, r2.zwzz
sqrt r2.xy, r2.xyxx
mul r2.xy, r2.xyxx, cb2[8].xyxx
exp r2.xy, r2.xyxx
log r1.xy, |r1.xyxx|
mul r1.xy, r1.xyxx, r2.xyxx
exp r1.xy, r1.xyxx
mul r1.xy, r1.xyxx, r1.zwzz
mul r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)  // r1.x <- dir.x; r1.y <- dir.y

#line 187
exp r1.zw, cb2[8].zzzw

#line 186
mul r2.xyz, r1.zzzz, cb2[5].xyzx

#line 149
mul r1.z, cb2[7].x, l(6.283185)  // r1.z <- a

#line 150
sincos r3.x, r4.x, r1.z
mul r1.z, r1.y, r3.x
mad r1.z, r4.x, r1.x, r1.z  // r1.z <- <r2d_id30 return value>.x

#line 186
mad r2.w, r1.z, cb2[7].z, l(0.500000)
mad r2.xyz, r2.wwww, -r2.xyzx, r2.xyzx  // r2.x <- col.x; r2.y <- col.y; r2.z <- col.z

#line 187
mul r3.xyz, r1.wwww, cb2[6].xyzx
add r1.w, cb2[7].y, l(0.250000)

#line 149
mul r1.w, r1.w, l(6.283185)

#line 150
sincos r4.x, r5.x, r1.w
mul r1.y, r1.y, r4.x
mad r1.x, r5.x, r1.x, r1.y  // r1.x <- <r2d_id30 return value>.x

#line 187
mad r1.x, r1.x, cb2[7].w, l(0.500000)
mad r1.xyw, r1.xxxx, -r3.xyxz, r3.xyxz
add r1.z, -|r1.z|, l(1.000000)
mad r1.xyz, r1.xywx, r1.zzzz, r2.xyzx  // r1.x <- col.x; r1.y <- col.y; r1.z <- col.z

#line 198
add r1.xyz, -r0.xyzx, r1.xyzx
mov r1.w, l(0)
mad o0.xyzw, cb0[0].xyzw, r1.xyzw, r0.xyzw

#line 207
ret 
// Approximately 96 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer PerUpdate 
{
    float4 InputValue_id97;
};
cbuffer PerView 
{
    float NearClipPlane_id74 = 1.0f;
    float FarClipPlane_id75 = 100.0f;
    float2 ZProjection_id76;
    float2 ViewSize_id77;
    float AspectRatio_id78;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
    float4 ColorA_id88 = float4(0.60f, 0.99f, 0.96f, 1.0f);
    float4 ColorB_id89 = float4(0.57f, 0.41f, 0.07f, 1.0f);
    float2 Angle_id90 = float2(0.0f, 0.0f);
    float2 BumpAmount_id91 = float2(1.0f, 1.0f);
    float2 BumpGamma_id92 = float2(0.0f, 0.0f);
    float2 Brightness_id93 = float2(0.0f, 0.0f);
    float Emboss_id94 = 1.0f;
    float Shape_id95 = 0.0f;
    float MaxRadius_id96 = 1.0f;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float2 r2d_id30(float2 x, float a)
{
    a *= acos(-1) * 2;
    return float2(cos(a) * x.x + sin(a) * x.y, cos(a) * x.y - sin(a) * x.x);
}
float mx_id29(float3 p)
{
    return max(p.x, max(p.y, p.z));
}
float4 Compute_id32()
{
    return InputValue_id97;
}
float4 Filter_id31(inout PS_STREAMS streams, float4 tex0col)
{
    float2 uv = streams.TexCoord_id62;
    float2 R = ViewSize_id77;
    float4 col = 0;
    float lod = log2(max(R.x, R.y));
    float kk = 0;

    for (float i = 0; i < min(lod - (1 - MaxRadius_id96 * lod), 14); i++)
    {
        float2 off = pow(2, i) / max(R.x, R.y);
        off *= 0.5;
        float k = 1. / pow(2, i * Shape_id95 - lod) * saturate(MaxRadius_id96 * lod - i);
        float dx = (mx_id29(Texture0_id14.SampleLevel(Sampler0_id52, uv - off * float2(1, 0), i).xyz) - mx_id29(Texture0_id14.SampleLevel(Sampler0_id52, uv + off * float2(1, 0), i).xyz));
        float dy = (mx_id29(Texture0_id14.SampleLevel(Sampler0_id52, uv - off * float2(0, 1), i).xyz) - mx_id29(Texture0_id14.SampleLevel(Sampler0_id52, uv + off * float2(0, 1), i).xyz));
        col.xy += float2(dx, dy) * sqrt(R.x / R) * k;
        col.z += length(float2(dx, dy) * k);
        kk += k;
    }
    col.xy /= pow(abs(col.z) * .1, .3) / .1 + .00000001;
    float dd = Emboss_id94 / pow(abs(kk), .7) * 8;
    col.z = pow(saturate(1 - dd * length(col.xy)), .5);
    col.xy = col.xy * dd;
    float2 dir = col.xy;
    col = 0;
    dir = sign(dir) * pow(abs(dir), (pow(2, BumpGamma_id92 * sqrt(smoothstep(0, 1, 1 * abs(dir)))))) / 2;
    col += lerp(ColorA_id88 * pow(2, Brightness_id93.x), 0, r2d_id30(dir, Angle_id90.x).x * BumpAmount_id91.x + .5);
    col += lerp(ColorB_id89 * pow(2, Brightness_id93.y), 0, r2d_id30(dir, Angle_id90.y + .25).x * BumpAmount_id91.y + .5) * (1 - abs(r2d_id30(dir, Angle_id90.x).x));
    col.a = Texture0_id14.SampleLevel(Sampler0_id52, uv, 0).a;
    return col;
}
float4 InTex0_id26(inout PS_STREAMS streams)
{
    return Texture0_id14.SampleLevel(Sampler0_id52, streams.TexCoord_id62, 0);
}
float4 Shading_id28(inout PS_STREAMS streams)
{
    float4 col = InTex0_id26(streams);
    return lerp(col, Filter_id31(streams, col), Compute_id32());
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id28(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
