/**************************
***** Compiler Parameters *****
***************************
@P EffectName: SSLRCombinePass
***************************
****  ConstantBuffers  ****
***************************
cbuffer Data [Size: 192]
@C    MaxColorMiplevel_id74 => SSLRCommon.MaxColorMiplevel
@C    TraceSizeMax_id75 => SSLRCommon.TraceSizeMax
@C    MaxTraceSamples_id76 => SSLRCommon.MaxTraceSamples
@C    RoughnessFade_id77 => SSLRCommon.RoughnessFade
@C    TemporalTime_id78 => SSLRCommon.TemporalTime
@C    BRDFBias_id79 => SSLRCommon.BRDFBias
@C    ViewFarPlane_id80 => SSLRCommon.ViewFarPlane
@C    ViewInfo_id81 => SSLRCommon.ViewInfo
@C    CameraPosWS_id82 => SSLRCommon.CameraPosWS
@C    WorldAntiSelfOcclusionBias_id83 => SSLRCommon.WorldAntiSelfOcclusionBias
@C    V_id84 => SSLRCommon.V
@C    IVP_id85 => SSLRCommon.IVP
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id73 => SpriteBase.MatrixTransform
cbuffer Globals [Size: 80]
@C    Texture0TexelSize_id15 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id17 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id19 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id21 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id23 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id25 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id27 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id29 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id31 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id33 => Texturing.Texture9TexelSize
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    PointSampler_id43 => Texturing.PointSampler [Stage: Pixel, Slot: (0-0)]
@R    LinearSampler_id44 => Texturing.LinearSampler [Stage: Pixel, Slot: (1-1)]
@R    Texture0_id14 => Texturing.Texture0 [Stage: Pixel, Slot: (0-0)]
@R    Texture1_id16 => Texturing.Texture1 [Stage: Pixel, Slot: (1-1)]
@R    Texture2_id18 => Texturing.Texture2 [Stage: Pixel, Slot: (2-2)]
@R    Texture3_id20 => Texturing.Texture3 [Stage: Pixel, Slot: (3-3)]
@R    Texture4_id22 => Texturing.Texture4 [Stage: Pixel, Slot: (4-4)]
@R    Data => Data [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (1-1)]
***************************
*****     Sources     *****
***************************
@S    SSLRCombinePass => a15414de7133d76021a4e780a4642b96
@S    ImageEffectShader => 8064e30cc02e5eb4052f420259dbf05e
@S    SpriteBase => 5a7aa9dfd5b5c7613053f4f66c79ca0d
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    SSLRCommon => 161d9b8711411c56906b0b0d551faeae
@S    Utilities => d8e15010fb2006b8edf6bdc952dd31f0
@S    NormalPack => af1a18518fb63b6295c012c18fe9f9c0
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id73;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id72.x; v0.y <- __input__.Position_id72.y; v0.z <- __input__.Position_id72.z; v0.w <- __input__.Position_id72.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o1.x <- <VSMain return value>.TexCoord_id62.x; o1.y <- <VSMain return value>.TexCoord_id62.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 216 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_SSLRCombinePass_408b7839b3d48902227979aa949fb79a.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 220
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 52bf1148225420849a9ef16b945fd1a6
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Data
// {
//
//   float MaxColorMiplevel_id74;       // Offset:    0 Size:     4 [unused]
//   float TraceSizeMax_id75;           // Offset:    4 Size:     4 [unused]
//   float MaxTraceSamples_id76;        // Offset:    8 Size:     4 [unused]
//   float RoughnessFade_id77;          // Offset:   12 Size:     4 [unused]
//   float TemporalTime_id78;           // Offset:   16 Size:     4 [unused]
//   float BRDFBias_id79;               // Offset:   20 Size:     4 [unused]
//   float ViewFarPlane_id80;           // Offset:   24 Size:     4 [unused]
//   float4 ViewInfo_id81;              // Offset:   32 Size:    16 [unused]
//   float3 CameraPosWS_id82;           // Offset:   48 Size:    12
//   float WorldAntiSelfOcclusionBias_id83;// Offset:   60 Size:     4 [unused]
//   float4x4 V_id84;                   // Offset:   64 Size:    64 [unused]
//   float4x4 IVP_id85;                 // Offset:  128 Size:    64
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id15;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id17;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id19;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id21;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id23;     // Offset:   32 Size:     8
//   float2 Texture5TexelSize_id25;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id27;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id29;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id31;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id33;     // Offset:   72 Size:     8 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PointSampler_id43                 sampler      NA          NA             s0      1 
// LinearSampler_id44                sampler      NA          NA             s1      1 
// Texture0_id14                     texture  float4          2d             t0      1 
// Texture1_id16                     texture  float4          2d             t1      1 
// Texture2_id18                     texture  float4          2d             t2      1 
// Texture3_id20                     texture  float4          2d             t3      1 
// Texture4_id22                     texture  float4          2d             t4      1 
// Data                              cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[12], immediateIndexed
dcl_constantbuffer CB1[3], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.TexCoord_id62.x; v1.y <- __input__.TexCoord_id62.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 155 "H:\JHH_SpaceMusic\SpaceMusicZH\vvvv-binaries\vvvv_gamma\log\shader_SSLRCombinePass_408b7839b3d48902227979aa949fb79a.hlsl"
sample_l_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t1.yzxw, s0, l(0.000000)  // r0.z <- <SampleZ_id12 return value>

#line 150
mad r0.xy, v1.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb0[8].xyzw  // r1.x <- pos.x
dp4 r1.y, r0.xyzw, cb0[9].xyzw  // r1.y <- pos.y
dp4 r1.z, r0.xyzw, cb0[10].xyzw  // r1.z <- pos.z
dp4 r0.x, r0.xyzw, cb0[11].xyzw  // r0.x <- pos.w

#line 151
div r0.xyz, r1.xyzx, r0.xxxx  // r0.x <- <ComputeWorldPosition_id17 return value>.x; r0.y <- <ComputeWorldPosition_id17 return value>.y; r0.z <- <ComputeWorldPosition_id17 return value>.z

#line 197
add r0.xyz, -r0.xyzx, cb0[3].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- viewVector.x; r0.y <- viewVector.y; r0.z <- viewVector.z

#line 191
sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t2.xyzw, s0, l(0.000000)  // r1.x <- normalsBuffer.x; r1.y <- normalsBuffer.y; r1.z <- normalsBuffer.z

#line 168
mad r1.xyz, r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx  // r1.x <- <DecodeNormal_id11 return value>.x; r1.y <- <DecodeNormal_id11 return value>.y; r1.z <- <DecodeNormal_id11 return value>.z

#line 198
dp3_sat r0.x, r1.xyzx, r0.xyzx  // r0.x <- NoV

#line 162
mul r0.x, r0.x, l(-9.280000)
exp r0.x, r0.x

#line 194
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t3.xyzw, s0, l(0.000000)  // r1.x <- specularRoughnessBuffer.x; r1.y <- specularRoughnessBuffer.y; r1.z <- specularRoughnessBuffer.z; r1.w <- specularRoughnessBuffer.w

#line 161
mad r2.xyzw, r1.wwww, l(-1.000000, -0.027500, -0.572000, 0.022000), l(1.000000, 0.042500, 1.040000, -0.040000)  // r2.x <- r.x; r2.y <- r.y; r2.z <- r.z; r2.w <- r.w

#line 162
mul r0.y, r2.x, r2.x
min r0.x, r0.x, r0.y
mad r0.x, r0.x, r2.x, r2.y  // r0.x <- a004

#line 163
mad r0.xy, r0.xxxx, l(-1.040000, 1.040000, 0.000000, 0.000000), r2.zwzz  // r0.x <- AB.x; r0.y <- AB.y

#line 164
mul_sat r0.z, r1.y, l(50.000000)
mul r0.y, r0.y, r0.z
mad r0.xyz, r1.xyzx, r0.xxxx, r0.yyyy  // r0.x <- <EnvBRDFApprox_id25 return value>.x; r0.y <- <EnvBRDFApprox_id25 return value>.y; r0.z <- <EnvBRDFApprox_id25 return value>.z

#line 177
sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t4.xyzw, s1, l(0.000000)  // r1.x <- ssr.x; r1.y <- ssr.y; r1.z <- ssr.z

#line 180
mov r2.xw, l(0,0,0,0)
mov r2.yz, cb1[2].yyxy
add r3.xyzw, r2.xyzw, v1.xyxy

#line 181
add r2.xyzw, -r2.xyzw, v1.xyxy

#line 178
sample_l_indexable(texture2d)(float,float,float,float) r4.xyz, r3.xyxx, t4.xyzw, s1, l(0.000000)

#line 180
sample_l_indexable(texture2d)(float,float,float,float) r3.xyz, r3.zwzz, t4.xyzw, s1, l(0.000000)

#line 178
add r1.xyz, r1.xyzx, r4.xyzx

#line 179
sample_l_indexable(texture2d)(float,float,float,float) r4.xyz, r2.xyxx, t4.xyzw, s1, l(0.000000)

#line 181
sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, r2.zwzz, t4.xyzw, s1, l(0.000000)

#line 179
add r1.xyz, r1.xyzx, r4.xyzx

#line 180
add r1.xyz, r3.xyzx, r1.xyzx

#line 181
add r1.xyz, r2.xyzx, r1.xyzx

#line 182
mul r1.xyz, r1.xyzx, l(0.200000, 0.200000, 0.200000, 0.000000)

#line 188
sample_l_indexable(texture2d)(float,float,float,float) r2.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)  // r2.x <- sceneColor.x; r2.y <- sceneColor.y; r2.z <- sceneColor.z; r2.w <- sceneColor.w

#line 199
mad o0.xyz, r1.xyzx, r0.xyzx, r2.xyzx

#line 209
mov o0.w, r2.w
ret 
// Approximately 47 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float2 TexCoord_id62;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id72;
    float2 TexCoord_id62;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float2 TexCoord_id62 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id72 : POSITION;
    float2 TexCoord_id62 : TEXCOORD0;
};
typedef uint Half2;
typedef uint2 Half4;
cbuffer Data 
{
    float MaxColorMiplevel_id74;
    float TraceSizeMax_id75;
    float MaxTraceSamples_id76;
    float RoughnessFade_id77;
    float TemporalTime_id78;
    float BRDFBias_id79;
    float ViewFarPlane_id80;
    float4 ViewInfo_id81;
    float3 CameraPosWS_id82;
    float WorldAntiSelfOcclusionBias_id83;
    float4x4 V_id84;
    float4x4 IVP_id85;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id73;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id15;
    float2 Texture1TexelSize_id17;
    float2 Texture2TexelSize_id19;
    float2 Texture3TexelSize_id21;
    float2 Texture4TexelSize_id23;
    float2 Texture5TexelSize_id25;
    float2 Texture6TexelSize_id27;
    float2 Texture7TexelSize_id29;
    float2 Texture8TexelSize_id31;
    float2 Texture9TexelSize_id33;
};
Texture2D Texture0_id14;
Texture2D Texture1_id16;
Texture2D Texture2_id18;
Texture2D Texture3_id20;
Texture2D Texture4_id22;
Texture2D Texture5_id24;
Texture2D Texture6_id26;
Texture2D Texture7_id28;
Texture2D Texture8_id30;
Texture2D Texture9_id32;
TextureCube TextureCube0_id34;
TextureCube TextureCube1_id35;
TextureCube TextureCube2_id36;
TextureCube TextureCube3_id37;
Texture3D Texture3D0_id38;
Texture3D Texture3D1_id39;
Texture3D Texture3D2_id40;
Texture3D Texture3D3_id41;
SamplerState Sampler_id42;
SamplerState PointSampler_id43 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id44 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id46 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id47 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id48 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id49 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id51 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id52;
SamplerState Sampler1_id53;
SamplerState Sampler2_id54;
SamplerState Sampler3_id55;
SamplerState Sampler4_id56;
SamplerState Sampler5_id57;
SamplerState Sampler6_id58;
SamplerState Sampler7_id59;
SamplerState Sampler8_id60;
SamplerState Sampler9_id61;
float2 UvToClip_id16(float2 uv)
{
    return uv * float2(2, -2) + float2(-1, 1);
}
float3 ComputeWorldPosition_id17(float2 uv, float rawDepth)
{
    float4 clipPos = float4(UvToClip_id16(uv), rawDepth, 1);
    float4 pos = mul(clipPos, IVP_id85);
    return pos.xyz / pos.w;
}
float SampleZ_id12(in float2 uv)
{
    return Texture1_id16.SampleLevel(PointSampler_id43, uv, 0).r;
}
float3 EnvBRDFApprox_id25(float3 specularColor, float roughness, float NoV)
{
    const half4 c0 = { -1, -0.0275, -0.572, 0.022};
    const half4 c1 = { 1, 0.0425, 1.04, -0.04};
    half4 r = roughness * c0 + c1;
    half a004 = min(r.x * r.x, exp2(-9.28 * NoV)) * r.x + r.y;
    half2 AB = half2(-1.04, 1.04) * a004 + r.zw;
    return specularColor * AB.x + saturate(50.0 * specularColor.g) * AB.y;
}
float3 DecodeNormal_id11(float3 enc)
{
    return normalize(enc * 2 - 1);
}
float3 ComputeWorldPosition_id18(float2 uv)
{
    float rawDepth = SampleZ_id12(uv);
    return ComputeWorldPosition_id17(uv, rawDepth);
}
float3 SampleSSR_id24(float2 uv)
{
    float4 ssr = Texture4_id22.SampleLevel(LinearSampler_id44, uv, 0);
    ssr += Texture4_id22.SampleLevel(LinearSampler_id44, uv + float2(0, Texture4TexelSize_id23.y), 0);
    ssr += Texture4_id22.SampleLevel(LinearSampler_id44, uv - float2(0, Texture4TexelSize_id23.y), 0);
    ssr += Texture4_id22.SampleLevel(LinearSampler_id44, uv + float2(Texture4TexelSize_id23.x, 0), 0);
    ssr += Texture4_id22.SampleLevel(LinearSampler_id44, uv - float2(Texture4TexelSize_id23.x, 0), 0);
    ssr *= (1.0f / 5.0f);
    return ssr;
}
float4 Shading_id26(inout PS_STREAMS streams)
{
    float2 uv = streams.TexCoord_id62;
    float4 sceneColor = Texture0_id14.SampleLevel(PointSampler_id43, uv, 0);
    float3 ssr = SampleSSR_id24(uv);
    float3 positionWS = ComputeWorldPosition_id18(uv);
    float4 normalsBuffer = Texture2_id18.SampleLevel(PointSampler_id43, uv, 0);
    float3 normalWS = DecodeNormal_id11(normalsBuffer.rgb);
    float3 normalVS = mul(normalWS, (float3x3)V_id84);
    float4 specularRoughnessBuffer = Texture3_id20.SampleLevel(PointSampler_id43, uv, 0);
    float3 specularColor = specularRoughnessBuffer.rgb;
    float roughness = specularRoughnessBuffer.a;
    float3 viewVector = normalize(CameraPosWS_id82.xyz - positionWS);
    float NoV = saturate(dot(normalWS, viewVector));
    sceneColor.rgb += ssr * EnvBRDFApprox_id25(specularColor, roughness, NoV);
    return sceneColor;
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ColorTarget_id2 = Shading_id26(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id72 = __input__.Position_id72;
    streams.TexCoord_id62 = __input__.TexCoord_id62;
    streams.ShadingPosition_id0 = mul(streams.Position_id72, MatrixTransform_id73);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.TexCoord_id62 = streams.TexCoord_id62;
    return __output__;
}
